# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2021       Christopher Horn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Profile Options
"""

CONFIGSETTINGS = (
    ######################################################################
    # Active State
    ######################################################################
    ("preferences.profile.active.last_object", "None"),
    ######################################################################
    # Additional Color Schemes
    ######################################################################
    # Confidence Color Scheme
    ('preferences.profile.colors.confidence.very-high', ["#99c1f1","#304918"]),
    ('preferences.profile.colors.confidence.high', ["#8ff0a4","#454545"]),
    ('preferences.profile.colors.confidence.normal', ["#f9f06b","#454545"]),
    ('preferences.profile.colors.confidence.low', ["#ffbe6f","#454545"]),
    ('preferences.profile.colors.confidence.very-low', ["#f66161","#454545"]),
    ('preferences.profile.colors.confidence.border-very-high', ["#1a5fb4","#000000"]),
    ('preferences.profile.colors.confidence.border-high', ["#26a269","#000000"]),
    ('preferences.profile.colors.confidence.border-normal', ["#e5a50a","#000000"]),
    ('preferences.profile.colors.confidence.border-low', ["#c64600","#000000"]),
    ('preferences.profile.colors.confidence.border-very-low', ["#a51d2d","#000000"]),
    # Relationship Color Scheme
    ('preferences.profile.colors.relations.active', ["#bbe68e","#304918"]),
    ('preferences.profile.colors.relations.spouse', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.father', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.mother', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.brother', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.sister', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.son', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.daughter', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.none', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.border-active', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-spouse', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-father', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-mother', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-brother', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-sister', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-son', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-daughter', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-none', ["#cccccc","#000000"]),
    # Event Category Color Scheme
    ('preferences.profile.colors.events.vital', ["#bbe68e","#304918"]),
    ('preferences.profile.colors.events.family', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.religious', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.vocational', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.academic', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.travel', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.legal', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.residence', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.other', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.custom', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.border-vital', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-family', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-religious', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-vocational', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-academic', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-travel', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-legal', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-residence', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-other', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-custom', ["#cccccc","#000000"]),
    ######################################################################
    # Person Page Options
    ######################################################################
    # Layout
    ("preferences.profile.person.layout.enable-tooltips", True),
    ("preferences.profile.person.layout.enable-warnings", True),
    ("preferences.profile.person.layout.pinned-header", True),
    ("preferences.profile.person.layout.spouses-left", True),
    ("preferences.profile.person.layout.families-stacked", False),
    ("preferences.profile.person.layout.show-timeline", True),
    ("preferences.profile.person.layout.show-citations", False),
    ("preferences.profile.person.layout.border-width", 2),
    ("preferences.profile.person.layout.use-color-scheme", True),
    ("preferences.profile.person.layout.use-smaller-detail-font", True),
    ("preferences.profile.person.layout.sort-tags-by-name", False),
    ("preferences.profile.person.layout.include-child-notes", False),
    ("preferences.profile.person.layout.right-to-left", False),
    # Active Person
    ("preferences.profile.person.active.event-format", 1),
    ("preferences.profile.person.active.show-age", True),
    ("preferences.profile.person.active.sex-mode", 1),
    ("preferences.profile.person.active.image-mode", 3),
    ("preferences.profile.person.active.tag-format", 1),
    ("preferences.profile.person.active.tag-width", 10),
    ("preferences.profile.person.active.facts-field-skip-birth-alternates", False),
    ("preferences.profile.person.active.facts-field-skip-death-alternates", False),
    ("preferences.profile.person.active.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.active.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.active.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.active.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.active.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.active.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.active.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.active.facts-field-8", "None"),
    ("preferences.profile.person.active.extra-field-skip-birth-alternates", False),
    ("preferences.profile.person.active.extra-field-skip-death-alternates", False),
    ("preferences.profile.person.active.extra-field-1", "None"),
    ("preferences.profile.person.active.extra-field-2", "None"),
    ("preferences.profile.person.active.extra-field-3", "None"),
    ("preferences.profile.person.active.extra-field-4", "None"),
    ("preferences.profile.person.active.extra-field-5", "None"),
    ("preferences.profile.person.active.extra-field-6", "None"),
    ("preferences.profile.person.active.extra-field-7", "None"),
    ("preferences.profile.person.active.extra-field-8", "None"),
    ("preferences.profile.person.active.metadata-attribute-1", "None"),
    ("preferences.profile.person.active.metadata-attribute-2", "None"),
    ("preferences.profile.person.active.metadata-attribute-3", "None"),
    ("preferences.profile.person.active.metadata-attribute-4", "None"),
    ("preferences.profile.person.active.metadata-attribute-5", "None"),
    ("preferences.profile.person.active.metadata-attribute-6", "None"),
    ("preferences.profile.person.active.metadata-attribute-7", "None"),
    ("preferences.profile.person.active.metadata-attribute-8", "None"),
    # Parents
    ("preferences.profile.person.parent.event-format", 1),
    ("preferences.profile.person.parent.show-age", False),
    ("preferences.profile.person.parent.sex-mode", 1),
    ("preferences.profile.person.parent.image-mode", 1),
    ("preferences.profile.person.parent.tag-format", 1),
    ("preferences.profile.person.parent.tag-width", 10),
    ("preferences.profile.person.parent.show-matrilineal", False),
    ("preferences.profile.person.parent.expand-children", True),
    ("preferences.profile.person.parent.show-divorce", True),
    ("preferences.profile.person.parent.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.parent.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.parent.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.parent.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.parent.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.parent.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.parent.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.parent.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.parent.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.parent.facts-field-8", "None"),
    ("preferences.profile.person.parent.metadata-attribute-1", "None"),
    ("preferences.profile.person.parent.metadata-attribute-2", "None"),
    ("preferences.profile.person.parent.metadata-attribute-3", "None"),
    ("preferences.profile.person.parent.metadata-attribute-4", "None"),
    ("preferences.profile.person.parent.metadata-attribute-5", "None"),
    ("preferences.profile.person.parent.metadata-attribute-6", "None"),
    ("preferences.profile.person.parent.metadata-attribute-7", "None"),
    ("preferences.profile.person.parent.metadata-attribute-8", "None"),
    # Spouses
    ("preferences.profile.person.spouse.event-format", 1),
    ("preferences.profile.person.spouse.show-age", False),
    ("preferences.profile.person.spouse.sex-mode", 1),
    ("preferences.profile.person.spouse.image-mode", 3),
    ("preferences.profile.person.spouse.tag-format", 1),
    ("preferences.profile.person.spouse.tag-width", 10),
    ("preferences.profile.person.spouse.expand-children", True),
    ("preferences.profile.person.spouse.show-spouse-only", True),
    ("preferences.profile.person.spouse.show-divorce", True),
    ("preferences.profile.person.spouse.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.spouse.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.spouse.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.spouse.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.spouse.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.spouse.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.spouse.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.spouse.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.spouse.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.spouse.facts-field-8", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-1", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-2", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-3", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-4", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-5", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-6", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-7", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-8", "None"),
    # Children
    ("preferences.profile.person.child.event-format", 1),
    ("preferences.profile.person.child.show-age", False),
    ("preferences.profile.person.child.sex-mode", 1),
    ("preferences.profile.person.child.image-mode", 3),
    ("preferences.profile.person.child.tag-format", 1),
    ("preferences.profile.person.child.tag-width", 10),
    ("preferences.profile.person.child.number-children", True),
    ("preferences.profile.person.child.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.child.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.child.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.child.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.child.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.child.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.child.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.child.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.child.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.child.facts-field-8", "None"),
    ("preferences.profile.person.child.metadata-attribute-1", "None"),
    ("preferences.profile.person.child.metadata-attribute-2", "None"),
    ("preferences.profile.person.child.metadata-attribute-3", "None"),
    ("preferences.profile.person.child.metadata-attribute-4", "None"),
    ("preferences.profile.person.child.metadata-attribute-5", "None"),
    ("preferences.profile.person.child.metadata-attribute-6", "None"),
    ("preferences.profile.person.child.metadata-attribute-7", "None"),
    ("preferences.profile.person.child.metadata-attribute-8", "None"),
    # Siblings
    ("preferences.profile.person.sibling.event-format", 1),
    ("preferences.profile.person.sibling.show-age", False),
    ("preferences.profile.person.sibling.sex-mode", 1),
    ("preferences.profile.person.sibling.image-mode", 1),
    ("preferences.profile.person.sibling.tag-format", 1),
    ("preferences.profile.person.sibling.tag-width", 10),
    ("preferences.profile.person.sibling.number-children", True),
    ("preferences.profile.person.sibling.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.sibling.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.sibling.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.sibling.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.sibling.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.sibling.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.sibling.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.sibling.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.sibling.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.sibling.facts-field-8", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-1", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-2", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-3", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-4", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-5", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-6", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-7", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-8", "None"),
    # Person Timeline
    ("preferences.profile.person.timeline.tag-format", 1),
    ("preferences.profile.person.timeline.tag-width", 10),
    ("preferences.profile.person.timeline.image-mode", 0),
    ("preferences.profile.person.timeline.color-scheme", 0),
    ("preferences.profile.person.timeline.show-description", True),
    ("preferences.profile.person.timeline.show-participants", True),
    ("preferences.profile.person.timeline.show-role-always", False),
    ("preferences.profile.person.timeline.show-source-count", True),
    ("preferences.profile.person.timeline.show-citation-count", True),
    ("preferences.profile.person.timeline.show-best-confidence", True),
    ("preferences.profile.person.timeline.show-age", True),
    ("preferences.profile.person.timeline.metadata-attribute-1", "None"),
    ("preferences.profile.person.timeline.metadata-attribute-2", "None"),
    ("preferences.profile.person.timeline.metadata-attribute-3", "None"),
    ("preferences.profile.person.timeline.metadata-attribute-4", "None"),
    ("preferences.profile.person.timeline.show-class-vital", True),
    ("preferences.profile.person.timeline.show-class-family", True),
    ("preferences.profile.person.timeline.show-class-religious", True),
    ("preferences.profile.person.timeline.show-class-vocational", True),
    ("preferences.profile.person.timeline.show-class-academic", True),
    ("preferences.profile.person.timeline.show-class-travel", True),
    ("preferences.profile.person.timeline.show-class-legal", True),
    ("preferences.profile.person.timeline.show-class-residence", True),
    ("preferences.profile.person.timeline.show-class-other", True),
    ("preferences.profile.person.timeline.show-class-custom", True),
    ("preferences.profile.person.timeline.generations-ancestors", 1),
    ("preferences.profile.person.timeline.generations-offspring", 1),
    ("preferences.profile.person.timeline.show-family-father", True),
    ("preferences.profile.person.timeline.show-family-mother", True),
    ("preferences.profile.person.timeline.show-family-brother", True),
    ("preferences.profile.person.timeline.show-family-sister", True),
    ("preferences.profile.person.timeline.show-family-wife", True),
    ("preferences.profile.person.timeline.show-family-husband", True),
    ("preferences.profile.person.timeline.show-family-son", True),
    ("preferences.profile.person.timeline.show-family-daughter", True),
    ("preferences.profile.person.timeline.show-family-class-vital", False),
    ("preferences.profile.person.timeline.show-family-class-family", False),
    ("preferences.profile.person.timeline.show-family-class-religious", False),
    ("preferences.profile.person.timeline.show-family-class-vocational", False),
    ("preferences.profile.person.timeline.show-family-class-academic", False),
    ("preferences.profile.person.timeline.show-family-class-travel", False),
    ("preferences.profile.person.timeline.show-family-class-legal", False),
    ("preferences.profile.person.timeline.show-family-class-residence", False),
    ("preferences.profile.person.timeline.show-family-class-other", False),
    ("preferences.profile.person.timeline.show-family-class-custom", False),
    # Supporting Citations
    ("preferences.profile.person.citation.tag-format", 1),
    ("preferences.profile.person.citation.tag-width", 10),
    ("preferences.profile.person.citation.image-mode", 0),
    ("preferences.profile.person.citation.sort-by-date", False),
    ("preferences.profile.person.citation.include-indirect", True),
    ("preferences.profile.person.citation.include-parent-family", True),
    ("preferences.profile.person.citation.include-family", True),
    ("preferences.profile.person.citation.include-family-indirect", True),
    ("preferences.profile.person.citation.show-date", True),
    ("preferences.profile.person.citation.show-publisher", True),
    ("preferences.profile.person.citation.show-reference-type", True),
    ("preferences.profile.person.citation.show-reference-description", True),
    ("preferences.profile.person.citation.show-confidence", True),
    ("preferences.profile.person.citation.metadata-attribute-1", "None"),
    ("preferences.profile.person.citation.metadata-attribute-2", "None"),
    ("preferences.profile.person.citation.metadata-attribute-3", "None"),
    ("preferences.profile.person.citation.metadata-attribute-4", "None"),
    ######################################################################
    # Event Page Options
    ######################################################################
    # Layout
    ("preferences.profile.event.layout.enable-tooltips", True),
    ("preferences.profile.event.layout.enable-warnings", True),
    ("preferences.profile.event.layout.pinned-header", True),
    ("preferences.profile.event.layout.border-width", 2),
    ("preferences.profile.event.layout.use-color-scheme", True),
    ("preferences.profile.event.layout.use-smaller-detail-font", True),
    ("preferences.profile.event.layout.sort-tags-by-name", False),
    ("preferences.profile.event.layout.include-child-notes", False),
    ("preferences.profile.event.layout.right-to-left", False),
    # Active Event
    ("preferences.profile.event.active.event-format", 1),
    ("preferences.profile.event.active.image-mode", 3),
    ("preferences.profile.event.active.tag-format", 1),
    ("preferences.profile.event.active.tag-width", 10),
    ("preferences.profile.event.active.metadata-attribute-1", "None"),
    ("preferences.profile.event.active.metadata-attribute-2", "None"),
    ("preferences.profile.event.active.metadata-attribute-3", "None"),
    ("preferences.profile.event.active.metadata-attribute-4", "None"),
    # Individual Participants
    ("preferences.profile.event.people.event-format", 1),
    ("preferences.profile.event.people.show-age", False),
    ("preferences.profile.event.people.sex-mode", 1),
    ("preferences.profile.event.people.image-mode", 1),
    ("preferences.profile.event.people.tag-format", 1),
    ("preferences.profile.event.people.tag-width", 10),
    ("preferences.profile.event.people.facts-field-skip-birth-alternates", True),
    ("preferences.profile.event.people.facts-field-skip-death-alternates", True),
    ("preferences.profile.event.people.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.event.people.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.event.people.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.event.people.facts-field-4", "Event:Death:False"),
    ("preferences.profile.event.people.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.event.people.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.event.people.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.event.people.facts-field-8", "None"),
    ("preferences.profile.event.people.metadata-attribute-1", "None"),
    ("preferences.profile.event.people.metadata-attribute-2", "None"),
    ("preferences.profile.event.people.metadata-attribute-3", "None"),
    ("preferences.profile.event.people.metadata-attribute-4", "None"),
    ("preferences.profile.event.people.metadata-attribute-5", "None"),
    ("preferences.profile.event.people.metadata-attribute-6", "None"),
    ("preferences.profile.event.people.metadata-attribute-7", "None"),
    ("preferences.profile.event.people.metadata-attribute-8", "None"),
    # Family Participants
    ("preferences.profile.event.family.event-format", 1),
    ("preferences.profile.event.family.image-mode", 1),
    ("preferences.profile.event.family.tag-format", 1),
    ("preferences.profile.event.family.tag-width", 10),
    ("preferences.profile.event.family.metadata-attribute-1", "None"),
    ("preferences.profile.event.family.metadata-attribute-2", "None"),
    ("preferences.profile.event.family.metadata-attribute-3", "None"),
    ("preferences.profile.event.family.metadata-attribute-4", "None"),
    ######################################################################
    # Source Page Options
    ######################################################################
    # Layout
    ("preferences.profile.source.layout.enable-tooltips", True),
    ("preferences.profile.source.layout.enable-warnings", True),
    ("preferences.profile.source.layout.pinned-header", True),
    ("preferences.profile.source.layout.border-width", 2),
    ("preferences.profile.source.layout.use-color-scheme", True),
    ("preferences.profile.source.layout.use-smaller-detail-font", True),
    ("preferences.profile.source.layout.sort-tags-by-name", False),
    ("preferences.profile.source.layout.include-child-notes", False),
    ("preferences.profile.source.layout.right-to-left", False),
    # Active Source
    ("preferences.profile.source.active.event-format", 1),
    ("preferences.profile.source.active.image-mode", 3),
    ("preferences.profile.source.active.tag-format", 1),
    ("preferences.profile.source.active.tag-width", 10),
    ("preferences.profile.source.active.metadata-attribute-1", "None"),
    ("preferences.profile.source.active.metadata-attribute-2", "None"),
    ("preferences.profile.source.active.metadata-attribute-3", "None"),
    ("preferences.profile.source.active.metadata-attribute-4", "None"),
    # Source Citations
    ("preferences.profile.source.citation.tag-format", 1),
    ("preferences.profile.source.citation.tag-width", 10),
    ("preferences.profile.source.citation.image-mode", 0),
    ("preferences.profile.source.citation.sort-by-date", False),
    ("preferences.profile.source.citation.show-date", True),
    ("preferences.profile.source.citation.show-publisher", True),
    ("preferences.profile.source.citation.show-reference-type", True),
    ("preferences.profile.source.citation.show-reference-description", True),
    ("preferences.profile.source.citation.show-confidence", True),
    ("preferences.profile.source.citation.metadata-attribute-1", "None"),
    ("preferences.profile.source.citation.metadata-attribute-2", "None"),
    ("preferences.profile.source.citation.metadata-attribute-3", "None"),
    ("preferences.profile.source.citation.metadata-attribute-4", "None"),
    # People Referenced
    ("preferences.profile.source.people.event-format", 1),
    ("preferences.profile.source.people.show-age", False),
    ("preferences.profile.source.people.sex-mode", 1),
    ("preferences.profile.source.people.image-mode", 1),
    ("preferences.profile.source.people.tag-format", 1),
    ("preferences.profile.source.people.tag-width", 10),
    ("preferences.profile.source.people.facts-field-skip-birth-alternates", True),
    ("preferences.profile.source.people.facts-field-skip-death-alternates", True),
    ("preferences.profile.source.people.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.source.people.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.source.people.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.source.people.facts-field-4", "Event:Death:False"),
    ("preferences.profile.source.people.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.source.people.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.source.people.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.source.people.facts-field-8", "None"),
    ("preferences.profile.source.people.metadata-attribute-1", "None"),
    ("preferences.profile.source.people.metadata-attribute-2", "None"),
    ("preferences.profile.source.people.metadata-attribute-3", "None"),
    ("preferences.profile.source.people.metadata-attribute-4", "None"),
    ("preferences.profile.source.people.metadata-attribute-5", "None"),
    ("preferences.profile.source.people.metadata-attribute-6", "None"),
    ("preferences.profile.source.people.metadata-attribute-7", "None"),
    ("preferences.profile.source.people.metadata-attribute-8", "None"),
    # Events Referenced
    ("preferences.profile.source.events.tag-format", 1),
    ("preferences.profile.source.events.tag-width", 10),
    ("preferences.profile.source.events.image-mode", 0),
    ("preferences.profile.source.events.color-scheme", 0),
    ("preferences.profile.source.events.show-description", True),
    ("preferences.profile.source.events.show-participants", True),
    ("preferences.profile.source.events.show-role-always", False),
    ("preferences.profile.source.events.show-source-count", True),
    ("preferences.profile.source.events.show-citation-count", True),
    ("preferences.profile.source.events.show-best-confidence", True),
    ("preferences.profile.source.events.metadata-attribute-1", "None"),
    ("preferences.profile.source.events.metadata-attribute-2", "None"),
    ("preferences.profile.source.events.metadata-attribute-3", "None"),
    ("preferences.profile.source.events.metadata-attribute-4", "None"),

)
