# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2021       Christopher Horn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Profile Options
"""

CONFIGSETTINGS = (
    ######################################################################
    # Active State
    ######################################################################
    ("preferences.profile.active.last_object", "None"),
    ######################################################################
    # Additional Color Schemes
    ######################################################################
    # Confidence Color Scheme
    ('preferences.profile.colors.confidence.very-high', ["#99c1f1","#304918"]),
    ('preferences.profile.colors.confidence.high', ["#8ff0a4","#454545"]),
    ('preferences.profile.colors.confidence.normal', ["#f9f06b","#454545"]),
    ('preferences.profile.colors.confidence.low', ["#ffbe6f","#454545"]),
    ('preferences.profile.colors.confidence.very-low', ["#f66161","#454545"]),
    ('preferences.profile.colors.confidence.border-very-high', ["#1a5fb4","#000000"]),
    ('preferences.profile.colors.confidence.border-high', ["#26a269","#000000"]),
    ('preferences.profile.colors.confidence.border-normal', ["#e5a50a","#000000"]),
    ('preferences.profile.colors.confidence.border-low', ["#c64600","#000000"]),
    ('preferences.profile.colors.confidence.border-very-low', ["#a51d2d","#000000"]),
    # Relationship Color Scheme
    ('preferences.profile.colors.relations.active', ["#bbe68e","#304918"]),
    ('preferences.profile.colors.relations.spouse', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.father', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.mother', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.brother', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.sister', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.son', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.daughter', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.none', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.relations.border-active', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-spouse', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-father', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-mother', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-brother', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-sister', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-son', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-daughter', ["#cccccc","#000000"]),
    ('preferences.profile.colors.relations.border-none', ["#cccccc","#000000"]),
    # Event Category Color Scheme
    ('preferences.profile.colors.events.vital', ["#bbe68e","#304918"]),
    ('preferences.profile.colors.events.family', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.religious', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.vocational', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.academic', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.travel', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.legal', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.residence', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.other', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.custom', ["#eeeeee","#454545"]),
    ('preferences.profile.colors.events.border-vital', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-family', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-religious', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-vocational', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-academic', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-travel', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-legal', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-residence', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-other', ["#cccccc","#000000"]),
    ('preferences.profile.colors.events.border-custom', ["#cccccc","#000000"]),
    ######################################################################
    # Person Page Options
    ######################################################################
    # Layout
    ("preferences.profile.person.layout.tabbed", False),
    ("preferences.profile.person.layout.columns", "parent,timeline,citation,spouse"),
    ("preferences.profile.person.layout.parent.visible", True),
    ("preferences.profile.person.layout.parent.stacked", False),
    ("preferences.profile.person.layout.spouse.visible", True),
    ("preferences.profile.person.layout.spouse.stacked", False),
    ("preferences.profile.person.layout.timeline.visible", True),
    ("preferences.profile.person.layout.timeline.stacked", False),
    ("preferences.profile.person.layout.citation.visible", True),
    ("preferences.profile.person.layout.citation.stacked", False),
    ("preferences.profile.person.layout.note.visible", False),
    ("preferences.profile.person.layout.note.stacked", False),
    ("preferences.profile.person.layout.media.visible", False),
    ("preferences.profile.person.layout.media.stacked", False),
    # Old Layout
    ("preferences.profile.person.page.enable-tooltips", True),
    ("preferences.profile.person.page.enable-warnings", True),
    ("preferences.profile.person.page.pinned-header", True),
    ("preferences.profile.person.page.spouses-left", True),
    ("preferences.profile.person.page.families-stacked", False),
    ("preferences.profile.person.page.show-timeline", True),
    ("preferences.profile.person.page.show-citations", False),
    ("preferences.profile.person.page.show-media", True),
    ("preferences.profile.person.page.show-notes", True),
    ("preferences.profile.person.page.border-width", 2),
    ("preferences.profile.person.page.use-color-scheme", True),
    ("preferences.profile.person.page.use-smaller-detail-font", True),
    ("preferences.profile.person.page.sort-tags-by-name", False),
    ("preferences.profile.person.page.include-child-notes", False),
    ("preferences.profile.person.page.right-to-left", False),
    # Active Person
    ("preferences.profile.person.active.event-format", 1),
    ("preferences.profile.person.active.show-age", True),
    ("preferences.profile.person.active.sex-mode", 1),
    ("preferences.profile.person.active.image-mode", 3),
    ("preferences.profile.person.active.tag-format", 1),
    ("preferences.profile.person.active.tag-width", 10),
    ("preferences.profile.person.active.facts-field-skip-birth-alternates", False),
    ("preferences.profile.person.active.facts-field-skip-death-alternates", False),
    ("preferences.profile.person.active.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.active.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.active.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.active.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.active.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.active.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.active.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.active.facts-field-8", "None"),
    ("preferences.profile.person.active.extra-field-skip-birth-alternates", False),
    ("preferences.profile.person.active.extra-field-skip-death-alternates", False),
    ("preferences.profile.person.active.extra-field-1", "None"),
    ("preferences.profile.person.active.extra-field-2", "None"),
    ("preferences.profile.person.active.extra-field-3", "None"),
    ("preferences.profile.person.active.extra-field-4", "None"),
    ("preferences.profile.person.active.extra-field-5", "None"),
    ("preferences.profile.person.active.extra-field-6", "None"),
    ("preferences.profile.person.active.extra-field-7", "None"),
    ("preferences.profile.person.active.extra-field-8", "None"),
    ("preferences.profile.person.active.metadata-attribute-1", "None"),
    ("preferences.profile.person.active.metadata-attribute-2", "None"),
    ("preferences.profile.person.active.metadata-attribute-3", "None"),
    ("preferences.profile.person.active.metadata-attribute-4", "None"),
    ("preferences.profile.person.active.metadata-attribute-5", "None"),
    ("preferences.profile.person.active.metadata-attribute-6", "None"),
    ("preferences.profile.person.active.metadata-attribute-7", "None"),
    ("preferences.profile.person.active.metadata-attribute-8", "None"),
    # Parents
    ("preferences.profile.person.parent.event-format", 1),
    ("preferences.profile.person.parent.show-age", False),
    ("preferences.profile.person.parent.sex-mode", 1),
    ("preferences.profile.person.parent.image-mode", 1),
    ("preferences.profile.person.parent.tag-format", 1),
    ("preferences.profile.person.parent.tag-width", 10),
    ("preferences.profile.person.parent.show-matrilineal", False),
    ("preferences.profile.person.parent.expand-children", True),
    ("preferences.profile.person.parent.show-divorce", True),
    ("preferences.profile.person.parent.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.parent.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.parent.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.parent.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.parent.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.parent.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.parent.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.parent.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.parent.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.parent.facts-field-8", "None"),
    ("preferences.profile.person.parent.metadata-attribute-1", "None"),
    ("preferences.profile.person.parent.metadata-attribute-2", "None"),
    ("preferences.profile.person.parent.metadata-attribute-3", "None"),
    ("preferences.profile.person.parent.metadata-attribute-4", "None"),
    ("preferences.profile.person.parent.metadata-attribute-5", "None"),
    ("preferences.profile.person.parent.metadata-attribute-6", "None"),
    ("preferences.profile.person.parent.metadata-attribute-7", "None"),
    ("preferences.profile.person.parent.metadata-attribute-8", "None"),
    # Spouses
    ("preferences.profile.person.spouse.event-format", 1),
    ("preferences.profile.person.spouse.show-age", False),
    ("preferences.profile.person.spouse.sex-mode", 1),
    ("preferences.profile.person.spouse.image-mode", 3),
    ("preferences.profile.person.spouse.tag-format", 1),
    ("preferences.profile.person.spouse.tag-width", 10),
    ("preferences.profile.person.spouse.expand-children", True),
    ("preferences.profile.person.spouse.show-spouse-only", True),
    ("preferences.profile.person.spouse.show-divorce", True),
    ("preferences.profile.person.spouse.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.spouse.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.spouse.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.spouse.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.spouse.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.spouse.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.spouse.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.spouse.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.spouse.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.spouse.facts-field-8", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-1", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-2", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-3", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-4", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-5", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-6", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-7", "None"),
    ("preferences.profile.person.spouse.metadata-attribute-8", "None"),
    # Children
    ("preferences.profile.person.child.event-format", 1),
    ("preferences.profile.person.child.show-age", False),
    ("preferences.profile.person.child.sex-mode", 1),
    ("preferences.profile.person.child.image-mode", 3),
    ("preferences.profile.person.child.tag-format", 1),
    ("preferences.profile.person.child.tag-width", 10),
    ("preferences.profile.person.child.number-children", True),
    ("preferences.profile.person.child.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.child.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.child.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.child.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.child.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.child.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.child.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.child.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.child.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.child.facts-field-8", "None"),
    ("preferences.profile.person.child.metadata-attribute-1", "None"),
    ("preferences.profile.person.child.metadata-attribute-2", "None"),
    ("preferences.profile.person.child.metadata-attribute-3", "None"),
    ("preferences.profile.person.child.metadata-attribute-4", "None"),
    ("preferences.profile.person.child.metadata-attribute-5", "None"),
    ("preferences.profile.person.child.metadata-attribute-6", "None"),
    ("preferences.profile.person.child.metadata-attribute-7", "None"),
    ("preferences.profile.person.child.metadata-attribute-8", "None"),
    # Siblings
    ("preferences.profile.person.sibling.event-format", 1),
    ("preferences.profile.person.sibling.show-age", False),
    ("preferences.profile.person.sibling.sex-mode", 1),
    ("preferences.profile.person.sibling.image-mode", 1),
    ("preferences.profile.person.sibling.tag-format", 1),
    ("preferences.profile.person.sibling.tag-width", 10),
    ("preferences.profile.person.sibling.number-children", True),
    ("preferences.profile.person.sibling.facts-field-skip-birth-alternates", True),
    ("preferences.profile.person.sibling.facts-field-skip-death-alternates", True),
    ("preferences.profile.person.sibling.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.person.sibling.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.person.sibling.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.person.sibling.facts-field-4", "Event:Death:False"),
    ("preferences.profile.person.sibling.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.person.sibling.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.person.sibling.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.person.sibling.facts-field-8", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-1", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-2", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-3", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-4", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-5", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-6", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-7", "None"),
    ("preferences.profile.person.sibling.metadata-attribute-8", "None"),
    # Person Timeline
    ("preferences.profile.person.timeline.tag-format", 1),
    ("preferences.profile.person.timeline.tag-width", 10),
    ("preferences.profile.person.timeline.image-mode", 0),
    ("preferences.profile.person.timeline.color-scheme", 0),
    ("preferences.profile.person.timeline.show-description", True),
    ("preferences.profile.person.timeline.show-participants", True),
    ("preferences.profile.person.timeline.show-role-always", False),
    ("preferences.profile.person.timeline.show-source-count", True),
    ("preferences.profile.person.timeline.show-citation-count", True),
    ("preferences.profile.person.timeline.show-best-confidence", True),
    ("preferences.profile.person.timeline.show-age", True),
    ("preferences.profile.person.timeline.metadata-attribute-1", "None"),
    ("preferences.profile.person.timeline.metadata-attribute-2", "None"),
    ("preferences.profile.person.timeline.metadata-attribute-3", "None"),
    ("preferences.profile.person.timeline.metadata-attribute-4", "None"),
    ("preferences.profile.person.timeline.show-class-vital", True),
    ("preferences.profile.person.timeline.show-class-family", True),
    ("preferences.profile.person.timeline.show-class-religious", True),
    ("preferences.profile.person.timeline.show-class-vocational", True),
    ("preferences.profile.person.timeline.show-class-academic", True),
    ("preferences.profile.person.timeline.show-class-travel", True),
    ("preferences.profile.person.timeline.show-class-legal", True),
    ("preferences.profile.person.timeline.show-class-residence", True),
    ("preferences.profile.person.timeline.show-class-other", True),
    ("preferences.profile.person.timeline.show-class-custom", True),
    ("preferences.profile.person.timeline.generations-ancestors", 1),
    ("preferences.profile.person.timeline.generations-offspring", 1),
    ("preferences.profile.person.timeline.show-family-father", True),
    ("preferences.profile.person.timeline.show-family-mother", True),
    ("preferences.profile.person.timeline.show-family-brother", True),
    ("preferences.profile.person.timeline.show-family-sister", True),
    ("preferences.profile.person.timeline.show-family-wife", True),
    ("preferences.profile.person.timeline.show-family-husband", True),
    ("preferences.profile.person.timeline.show-family-son", True),
    ("preferences.profile.person.timeline.show-family-daughter", True),
    ("preferences.profile.person.timeline.show-family-class-vital", False),
    ("preferences.profile.person.timeline.show-family-class-family", False),
    ("preferences.profile.person.timeline.show-family-class-religious", False),
    ("preferences.profile.person.timeline.show-family-class-vocational", False),
    ("preferences.profile.person.timeline.show-family-class-academic", False),
    ("preferences.profile.person.timeline.show-family-class-travel", False),
    ("preferences.profile.person.timeline.show-family-class-legal", False),
    ("preferences.profile.person.timeline.show-family-class-residence", False),
    ("preferences.profile.person.timeline.show-family-class-other", False),
    ("preferences.profile.person.timeline.show-family-class-custom", False),
    # Supporting Citations
    ("preferences.profile.person.citation.tag-format", 1),
    ("preferences.profile.person.citation.tag-width", 10),
    ("preferences.profile.person.citation.image-mode", 0),
    ("preferences.profile.person.citation.sort-by-date", False),
    ("preferences.profile.person.citation.include-indirect", True),
    ("preferences.profile.person.citation.include-parent-family", True),
    ("preferences.profile.person.citation.include-family", True),
    ("preferences.profile.person.citation.include-family-indirect", True),
    ("preferences.profile.person.citation.show-date", True),
    ("preferences.profile.person.citation.show-publisher", True),
    ("preferences.profile.person.citation.show-reference-type", True),
    ("preferences.profile.person.citation.show-reference-description", True),
    ("preferences.profile.person.citation.show-confidence", True),
    ("preferences.profile.person.citation.metadata-attribute-1", "None"),
    ("preferences.profile.person.citation.metadata-attribute-2", "None"),
    ("preferences.profile.person.citation.metadata-attribute-3", "None"),
    ("preferences.profile.person.citation.metadata-attribute-4", "None"),
    # Media
    ("preferences.profile.person.media.tag-format", 1),
    ("preferences.profile.person.media.tag-width", 10),
    ("preferences.profile.person.media.image-mode", 2),
    ("preferences.profile.person.media.sort-by-date", False),
    ("preferences.profile.person.media.show-date", True),
    ("preferences.profile.person.media.metadata-attribute-1", "None"),
    ("preferences.profile.person.media.metadata-attribute-2", "None"),
    ("preferences.profile.person.media.metadata-attribute-3", "None"),
    ("preferences.profile.person.media.metadata-attribute-4", "None"),
    # Note
    ("preferences.profile.person.note.tag-format", 1),
    ("preferences.profile.person.note.tag-width", 10),
    ######################################################################
    # Family Page Options
    ######################################################################
    # Layout
    ("preferences.profile.family.layout.tabbed", False),
    ("preferences.profile.family.layout.columns", "child,timeline,citation"),
    ("preferences.profile.family.layout.child.visible", True),
    ("preferences.profile.family.layout.child.stacked", False),
    ("preferences.profile.family.layout.timeline.visible", True),
    ("preferences.profile.family.layout.timeline.stacked", False),
    ("preferences.profile.family.layout.citation.visible", True),
    ("preferences.profile.family.layout.citation.stacked", False),
    ("preferences.profile.family.layout.note.visible", False),
    ("preferences.profile.family.layout.note.stacked", False),
    ("preferences.profile.family.layout.media.visible", False),
    ("preferences.profile.family.layout.media.stacked", False),
    # Old Layout
    ("preferences.profile.family.page.enable-tooltips", True),
    ("preferences.profile.family.page.enable-warnings", True),
    ("preferences.profile.family.page.show-timeline", True),
    ("preferences.profile.family.page.show-citations", False),
    ("preferences.profile.family.page.show-media", False),
    ("preferences.profile.family.page.show-notes", False),
    ("preferences.profile.family.page.border-width", 2),
    ("preferences.profile.family.page.use-color-scheme", True),
    ("preferences.profile.family.page.use-smaller-detail-font", True),
    ("preferences.profile.family.page.sort-tags-by-name", False),
    ("preferences.profile.family.page.include-child-notes", False),
    ("preferences.profile.family.page.right-to-left", False),
    # Active Family
    ("preferences.profile.family.active.event-format", 1),
    ("preferences.profile.family.active.show-age", True),
    ("preferences.profile.family.active.sex-mode", 1),
    ("preferences.profile.family.active.image-mode", 3),
    ("preferences.profile.family.active.tag-format", 1),
    ("preferences.profile.family.active.tag-width", 10),
    ("preferences.profile.family.active.facts-field-skip-birth-alternates", False),
    ("preferences.profile.family.active.facts-field-skip-death-alternates", False),
    ("preferences.profile.family.active.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.family.active.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.family.active.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.family.active.facts-field-4", "Event:Death:False"),
    ("preferences.profile.family.active.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.family.active.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.family.active.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.family.active.facts-field-8", "None"),
    ("preferences.profile.family.active.metadata-attribute-1", "None"),
    ("preferences.profile.family.active.metadata-attribute-2", "None"),
    ("preferences.profile.family.active.metadata-attribute-3", "None"),
    ("preferences.profile.family.active.metadata-attribute-4", "None"),
    ("preferences.profile.family.active.metadata-attribute-5", "None"),
    ("preferences.profile.family.active.metadata-attribute-6", "None"),
    ("preferences.profile.family.active.metadata-attribute-7", "None"),
    ("preferences.profile.family.active.metadata-attribute-8", "None"),
    # Parents
    ("preferences.profile.family.parent.event-format", 1),
    ("preferences.profile.family.parent.show-age", False),
    ("preferences.profile.family.parent.sex-mode", 1),
    ("preferences.profile.family.parent.image-mode", 1),
    ("preferences.profile.family.parent.tag-format", 1),
    ("preferences.profile.family.parent.tag-width", 10),
    ("preferences.profile.family.parent.show-matrilineal", False),
    ("preferences.profile.family.parent.expand-children", True),
    ("preferences.profile.family.parent.show-divorce", True),
    ("preferences.profile.family.parent.facts-field-skip-birth-alternates", True),
    ("preferences.profile.family.parent.facts-field-skip-death-alternates", True),
    ("preferences.profile.family.parent.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.family.parent.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.family.parent.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.family.parent.facts-field-4", "Event:Death:False"),
    ("preferences.profile.family.parent.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.family.parent.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.family.parent.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.family.parent.facts-field-8", "None"),
    ("preferences.profile.family.parent.metadata-attribute-1", "None"),
    ("preferences.profile.family.parent.metadata-attribute-2", "None"),
    ("preferences.profile.family.parent.metadata-attribute-3", "None"),
    ("preferences.profile.family.parent.metadata-attribute-4", "None"),
    ("preferences.profile.family.parent.metadata-attribute-5", "None"),
    ("preferences.profile.family.parent.metadata-attribute-6", "None"),
    ("preferences.profile.family.parent.metadata-attribute-7", "None"),
    ("preferences.profile.family.parent.metadata-attribute-8", "None"),
    # Children
    ("preferences.profile.family.child.event-format", 1),
    ("preferences.profile.family.child.show-age", False),
    ("preferences.profile.family.child.sex-mode", 1),
    ("preferences.profile.family.child.image-mode", 3),
    ("preferences.profile.family.child.tag-format", 1),
    ("preferences.profile.family.child.tag-width", 10),
    ("preferences.profile.family.child.number-children", True),
    ("preferences.profile.family.child.facts-field-skip-birth-alternates", True),
    ("preferences.profile.family.child.facts-field-skip-death-alternates", True),
    ("preferences.profile.family.child.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.family.child.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.family.child.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.family.child.facts-field-4", "Event:Death:False"),
    ("preferences.profile.family.child.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.family.child.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.family.child.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.family.child.facts-field-8", "None"),
    ("preferences.profile.family.child.metadata-attribute-1", "None"),
    ("preferences.profile.family.child.metadata-attribute-2", "None"),
    ("preferences.profile.family.child.metadata-attribute-3", "None"),
    ("preferences.profile.family.child.metadata-attribute-4", "None"),
    ("preferences.profile.family.child.metadata-attribute-5", "None"),
    ("preferences.profile.family.child.metadata-attribute-6", "None"),
    ("preferences.profile.family.child.metadata-attribute-7", "None"),
    ("preferences.profile.family.child.metadata-attribute-8", "None"),
    # Family Timeline
    ("preferences.profile.family.timeline.tag-format", 1),
    ("preferences.profile.family.timeline.tag-width", 10),
    ("preferences.profile.family.timeline.image-mode", 0),
    ("preferences.profile.family.timeline.color-scheme", 0),
    ("preferences.profile.family.timeline.show-description", True),
    ("preferences.profile.family.timeline.show-participants", True),
    ("preferences.profile.family.timeline.show-role-always", False),
    ("preferences.profile.family.timeline.show-source-count", True),
    ("preferences.profile.family.timeline.show-citation-count", True),
    ("preferences.profile.family.timeline.show-best-confidence", True),
    ("preferences.profile.family.timeline.show-age", True),
    ("preferences.profile.family.timeline.metadata-attribute-1", "None"),
    ("preferences.profile.family.timeline.metadata-attribute-2", "None"),
    ("preferences.profile.family.timeline.metadata-attribute-3", "None"),
    ("preferences.profile.family.timeline.metadata-attribute-4", "None"),
    ("preferences.profile.family.timeline.show-class-vital", True),
    ("preferences.profile.family.timeline.show-class-family", True),
    ("preferences.profile.family.timeline.show-class-religious", True),
    ("preferences.profile.family.timeline.show-class-vocational", True),
    ("preferences.profile.family.timeline.show-class-academic", True),
    ("preferences.profile.family.timeline.show-class-travel", True),
    ("preferences.profile.family.timeline.show-class-legal", True),
    ("preferences.profile.family.timeline.show-class-residence", True),
    ("preferences.profile.family.timeline.show-class-other", True),
    ("preferences.profile.family.timeline.show-class-custom", True),
    ("preferences.profile.family.timeline.generations-ancestors", 1),
    ("preferences.profile.family.timeline.generations-offspring", 1),
    # Supporting Citations
    ("preferences.profile.family.citation.tag-format", 1),
    ("preferences.profile.family.citation.tag-width", 10),
    ("preferences.profile.family.citation.image-mode", 0),
    ("preferences.profile.family.citation.sort-by-date", False),
    ("preferences.profile.family.citation.include-indirect", True),
    ("preferences.profile.family.citation.include-parent-family", True),
    ("preferences.profile.family.citation.include-family", True),
    ("preferences.profile.family.citation.include-family-indirect", True),
    ("preferences.profile.family.citation.show-date", True),
    ("preferences.profile.family.citation.show-publisher", True),
    ("preferences.profile.family.citation.show-reference-type", True),
    ("preferences.profile.family.citation.show-reference-description", True),
    ("preferences.profile.family.citation.show-confidence", True),
    ("preferences.profile.family.citation.metadata-attribute-1", "None"),
    ("preferences.profile.family.citation.metadata-attribute-2", "None"),
    ("preferences.profile.family.citation.metadata-attribute-3", "None"),
    ("preferences.profile.family.citation.metadata-attribute-4", "None"),
    # Media
    ("preferences.profile.family.media.tag-format", 1),
    ("preferences.profile.family.media.tag-width", 10),
    ("preferences.profile.family.media.image-mode", 2),
    ("preferences.profile.family.media.sort-by-date", False),
    ("preferences.profile.family.media.show-date", True),
    ("preferences.profile.family.media.metadata-attribute-1", "None"),
    ("preferences.profile.family.media.metadata-attribute-2", "None"),
    ("preferences.profile.family.media.metadata-attribute-3", "None"),
    ("preferences.profile.family.media.metadata-attribute-4", "None"),
    # Note
    ("preferences.profile.family.note.tag-format", 1),
    ("preferences.profile.family.note.tag-width", 10),
    ######################################################################
    # Event Page Options
    ######################################################################
    # Layout
    ("preferences.profile.event.layout.tabbed", False),
    ("preferences.profile.event.layout.columns", "people,family,note,media"),
    ("preferences.profile.event.layout.people.visible", True),
    ("preferences.profile.event.layout.people.stacked", False),
    ("preferences.profile.event.layout.family.visible", True),
    ("preferences.profile.event.layout.family.stacked", False),
    ("preferences.profile.event.layout.citation.visible", True),
    ("preferences.profile.event.layout.citation.stacked", False),
    ("preferences.profile.event.layout.note.visible", False),
    ("preferences.profile.event.layout.note.stacked", False),
    ("preferences.profile.event.layout.media.visible", False),
    ("preferences.profile.event.layout.media.stacked", False),
    # Old Layout
    ("preferences.profile.event.page.show-citations", False),
    ("preferences.profile.event.page.show-media", False),
    ("preferences.profile.event.page.show-notes", False),
    ("preferences.profile.event.page.enable-tooltips", True),
    ("preferences.profile.event.page.enable-warnings", True),
    ("preferences.profile.event.page.pinned-header", True),
    ("preferences.profile.event.page.border-width", 2),
    ("preferences.profile.event.page.use-color-scheme", True),
    ("preferences.profile.event.page.use-smaller-detail-font", True),
    ("preferences.profile.event.page.sort-tags-by-name", False),
    ("preferences.profile.event.page.include-child-notes", False),
    ("preferences.profile.event.page.right-to-left", False),
    # Active Event
    ("preferences.profile.event.active.event-format", 1),
    ("preferences.profile.event.active.image-mode", 3),
    ("preferences.profile.event.active.tag-format", 1),
    ("preferences.profile.event.active.tag-width", 10),
    ("preferences.profile.event.active.metadata-attribute-1", "None"),
    ("preferences.profile.event.active.metadata-attribute-2", "None"),
    ("preferences.profile.event.active.metadata-attribute-3", "None"),
    ("preferences.profile.event.active.metadata-attribute-4", "None"),
    # Individual Participants
    ("preferences.profile.event.people.event-format", 1),
    ("preferences.profile.event.people.show-age", False),
    ("preferences.profile.event.people.sex-mode", 1),
    ("preferences.profile.event.people.image-mode", 1),
    ("preferences.profile.event.people.tag-format", 1),
    ("preferences.profile.event.people.tag-width", 10),
    ("preferences.profile.event.people.facts-field-skip-birth-alternates", True),
    ("preferences.profile.event.people.facts-field-skip-death-alternates", True),
    ("preferences.profile.event.people.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.event.people.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.event.people.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.event.people.facts-field-4", "Event:Death:False"),
    ("preferences.profile.event.people.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.event.people.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.event.people.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.event.people.facts-field-8", "None"),
    ("preferences.profile.event.people.metadata-attribute-1", "None"),
    ("preferences.profile.event.people.metadata-attribute-2", "None"),
    ("preferences.profile.event.people.metadata-attribute-3", "None"),
    ("preferences.profile.event.people.metadata-attribute-4", "None"),
    ("preferences.profile.event.people.metadata-attribute-5", "None"),
    ("preferences.profile.event.people.metadata-attribute-6", "None"),
    ("preferences.profile.event.people.metadata-attribute-7", "None"),
    ("preferences.profile.event.people.metadata-attribute-8", "None"),
    # Family Participants
    ("preferences.profile.event.family.event-format", 1),
    ("preferences.profile.event.family.image-mode", 1),
    ("preferences.profile.event.family.tag-format", 1),
    ("preferences.profile.event.family.tag-width", 10),
    ("preferences.profile.event.family.metadata-attribute-1", "None"),
    ("preferences.profile.event.family.metadata-attribute-2", "None"),
    ("preferences.profile.event.family.metadata-attribute-3", "None"),
    ("preferences.profile.event.family.metadata-attribute-4", "None"),
    # Media
    ("preferences.profile.event.media.tag-format", 1),
    ("preferences.profile.event.media.tag-width", 10),
    ("preferences.profile.event.media.image-mode", 2),
    ("preferences.profile.event.media.sort-by-date", False),
    ("preferences.profile.event.media.show-date", True),
    ("preferences.profile.event.media.metadata-attribute-1", "None"),
    ("preferences.profile.event.media.metadata-attribute-2", "None"),
    ("preferences.profile.event.media.metadata-attribute-3", "None"),
    ("preferences.profile.event.media.metadata-attribute-4", "None"),
    # Note
    ("preferences.profile.event.note.tag-format", 1),
    ("preferences.profile.event.note.tag-width", 10),
    ######################################################################
    # Source Page Options
    ######################################################################
    # Layout
    ("preferences.profile.source.layout.tabbed", False),
    ("preferences.profile.source.layout.columns", "repository,citation,note"),
    ("preferences.profile.source.layout.people.visible", True),
    ("preferences.profile.source.layout.people.stacked", False),
    ("preferences.profile.source.layout.event.visible", True),
    ("preferences.profile.source.layout.event.stacked", False),
    ("preferences.profile.source.layout.repository.visible", True),
    ("preferences.profile.source.layout.repository.stacked", False),
    ("preferences.profile.source.layout.citation.visible", True),
    ("preferences.profile.source.layout.citation.stacked", False),
    ("preferences.profile.source.layout.note.visible", False),
    ("preferences.profile.source.layout.note.stacked", False),
    ("preferences.profile.source.layout.media.visible", False),
    ("preferences.profile.source.layout.media.stacked", False),
    # Old Layout
    ("preferences.profile.source.page.show-media", False),
    ("preferences.profile.source.page.show-notes", True),
    ("preferences.profile.source.page.enable-tooltips", True),
    ("preferences.profile.source.page.enable-warnings", True),
    ("preferences.profile.source.page.pinned-header", True),
    ("preferences.profile.source.page.border-width", 2),
    ("preferences.profile.source.page.use-color-scheme", True),
    ("preferences.profile.source.page.use-smaller-detail-font", True),
    ("preferences.profile.source.page.sort-tags-by-name", False),
    ("preferences.profile.source.page.include-child-notes", False),
    ("preferences.profile.source.page.right-to-left", False),
    # Active Source
    ("preferences.profile.source.active.event-format", 1),
    ("preferences.profile.source.active.image-mode", 3),
    ("preferences.profile.source.active.tag-format", 1),
    ("preferences.profile.source.active.tag-width", 10),
    ("preferences.profile.source.active.metadata-attribute-1", "None"),
    ("preferences.profile.source.active.metadata-attribute-2", "None"),
    ("preferences.profile.source.active.metadata-attribute-3", "None"),
    ("preferences.profile.source.active.metadata-attribute-4", "None"),
    # Repositories
    ("preferences.profile.source.repository.tag-format", 1),
    ("preferences.profile.source.repository.tag-width", 10),
    ("preferences.profile.source.repository.show-call-number", True),
    ("preferences.profile.source.repository.show-media-type", True),
    ("preferences.profile.source.repository.show-repository-type", True),
    # Source Citations
    ("preferences.profile.source.citation.tag-format", 1),
    ("preferences.profile.source.citation.tag-width", 10),
    ("preferences.profile.source.citation.image-mode", 0),
    ("preferences.profile.source.citation.sort-by-date", False),
    ("preferences.profile.source.citation.show-date", True),
    ("preferences.profile.source.citation.show-publisher", True),
    ("preferences.profile.source.citation.show-reference-type", True),
    ("preferences.profile.source.citation.show-reference-description", True),
    ("preferences.profile.source.citation.show-confidence", True),
    ("preferences.profile.source.citation.metadata-attribute-1", "None"),
    ("preferences.profile.source.citation.metadata-attribute-2", "None"),
    ("preferences.profile.source.citation.metadata-attribute-3", "None"),
    ("preferences.profile.source.citation.metadata-attribute-4", "None"),
    # People Referenced
    ("preferences.profile.source.people.event-format", 1),
    ("preferences.profile.source.people.show-age", False),
    ("preferences.profile.source.people.sex-mode", 1),
    ("preferences.profile.source.people.image-mode", 1),
    ("preferences.profile.source.people.tag-format", 1),
    ("preferences.profile.source.people.tag-width", 10),
    ("preferences.profile.source.people.facts-field-skip-birth-alternates", True),
    ("preferences.profile.source.people.facts-field-skip-death-alternates", True),
    ("preferences.profile.source.people.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.source.people.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.source.people.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.source.people.facts-field-4", "Event:Death:False"),
    ("preferences.profile.source.people.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.source.people.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.source.people.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.source.people.facts-field-8", "None"),
    ("preferences.profile.source.people.metadata-attribute-1", "None"),
    ("preferences.profile.source.people.metadata-attribute-2", "None"),
    ("preferences.profile.source.people.metadata-attribute-3", "None"),
    ("preferences.profile.source.people.metadata-attribute-4", "None"),
    ("preferences.profile.source.people.metadata-attribute-5", "None"),
    ("preferences.profile.source.people.metadata-attribute-6", "None"),
    ("preferences.profile.source.people.metadata-attribute-7", "None"),
    ("preferences.profile.source.people.metadata-attribute-8", "None"),
    # Events Referenced
    ("preferences.profile.source.events.tag-format", 1),
    ("preferences.profile.source.events.tag-width", 10),
    ("preferences.profile.source.events.image-mode", 0),
    ("preferences.profile.source.events.color-scheme", 0),
    ("preferences.profile.source.events.show-description", True),
    ("preferences.profile.source.events.show-participants", True),
    ("preferences.profile.source.events.show-role-always", False),
    ("preferences.profile.source.events.show-source-count", True),
    ("preferences.profile.source.events.show-citation-count", True),
    ("preferences.profile.source.events.show-best-confidence", True),
    ("preferences.profile.source.events.metadata-attribute-1", "None"),
    ("preferences.profile.source.events.metadata-attribute-2", "None"),
    ("preferences.profile.source.events.metadata-attribute-3", "None"),
    ("preferences.profile.source.events.metadata-attribute-4", "None"),
    # Media
    ("preferences.profile.source.media.tag-format", 1),
    ("preferences.profile.source.media.tag-width", 10),
    ("preferences.profile.source.media.image-mode", 2),
    ("preferences.profile.source.media.sort-by-date", False),
    ("preferences.profile.source.media.show-date", True),
    ("preferences.profile.source.media.metadata-attribute-1", "None"),
    ("preferences.profile.source.media.metadata-attribute-2", "None"),
    ("preferences.profile.source.media.metadata-attribute-3", "None"),
    ("preferences.profile.source.media.metadata-attribute-4", "None"),
    # Note
    ("preferences.profile.source.note.tag-format", 1),
    ("preferences.profile.source.note.tag-width", 10),
    ######################################################################
    # Citation Page Options
    ######################################################################
    # Layout
    ("preferences.profile.citation.layout.tabbed", False),
    ("preferences.profile.citation.layout.columns", "people,event,note"),
    ("preferences.profile.citation.layout.people.visible", True),
    ("preferences.profile.citation.layout.people.stacked", False),
    ("preferences.profile.citation.layout.event.visible", True),
    ("preferences.profile.citation.layout.event.stacked", False),
    ("preferences.profile.citation.layout.note.visible", False),
    ("preferences.profile.citation.layout.note.stacked", False),
    ("preferences.profile.citation.layout.media.visible", False),
    ("preferences.profile.citation.layout.media.stacked", False),
    # Old Layout
    ("preferences.profile.citation.page.show-media", False),
    ("preferences.profile.citation.page.show-notes", True),
    ("preferences.profile.citation.page.enable-tooltips", True),
    ("preferences.profile.citation.page.enable-warnings", True),
    ("preferences.profile.citation.page.pinned-header", True),
    ("preferences.profile.citation.page.border-width", 2),
    ("preferences.profile.citation.page.use-color-scheme", True),
    ("preferences.profile.citation.page.use-smaller-detail-font", True),
    ("preferences.profile.citation.page.sort-tags-by-name", False),
    ("preferences.profile.citation.page.include-child-notes", False),
    ("preferences.profile.citation.page.right-to-left", False),
    # Active Citation
    ("preferences.profile.citation.active.tag-format", 1),
    ("preferences.profile.citation.active.tag-width", 10),
    ("preferences.profile.citation.active.image-mode", 0),
    ("preferences.profile.citation.active.sort-by-date", False),
    ("preferences.profile.citation.active.show-date", True),
    ("preferences.profile.citation.active.show-publisher", True),
    ("preferences.profile.citation.active.show-reference-type", True),
    ("preferences.profile.citation.active.show-reference-description", True),
    ("preferences.profile.citation.active.show-confidence", True),
    ("preferences.profile.citation.active.metadata-attribute-1", "None"),
    ("preferences.profile.citation.active.metadata-attribute-2", "None"),
    ("preferences.profile.citation.active.metadata-attribute-3", "None"),
    ("preferences.profile.citation.active.metadata-attribute-4", "None"),
    # Source
    ("preferences.profile.citation.source.event-format", 1),
    ("preferences.profile.citation.source.image-mode", 3),
    ("preferences.profile.citation.source.tag-format", 1),
    ("preferences.profile.citation.source.tag-width", 10),
    ("preferences.profile.citation.source.metadata-attribute-1", "None"),
    ("preferences.profile.citation.source.metadata-attribute-2", "None"),
    ("preferences.profile.citation.source.metadata-attribute-3", "None"),
    ("preferences.profile.citation.source.metadata-attribute-4", "None"),
    # Repositories
    ("preferences.profile.citation.repository.tag-format", 1),
    ("preferences.profile.citation.repository.tag-width", 10),
    ("preferences.profile.citation.repository.show-call-number", True),
    ("preferences.profile.citation.repository.show-media-type", True),
    ("preferences.profile.citation.repository.show-repository-type", True),
    # People Referenced
    ("preferences.profile.citation.people.event-format", 1),
    ("preferences.profile.citation.people.show-age", False),
    ("preferences.profile.citation.people.sex-mode", 1),
    ("preferences.profile.citation.people.image-mode", 1),
    ("preferences.profile.citation.people.tag-format", 1),
    ("preferences.profile.citation.people.tag-width", 10),
    ("preferences.profile.citation.people.facts-field-skip-birth-alternates", True),
    ("preferences.profile.citation.people.facts-field-skip-death-alternates", True),
    ("preferences.profile.citation.people.facts-field-1", "Event:Birth:False"),
    ("preferences.profile.citation.people.facts-field-2", "Event:Baptism:False"),
    ("preferences.profile.citation.people.facts-field-3", "Event:Christening:False"),
    ("preferences.profile.citation.people.facts-field-4", "Event:Death:False"),
    ("preferences.profile.citation.people.facts-field-5", "Event:Burial:False"),
    ("preferences.profile.citation.people.facts-field-6", "Event:Cremation:False"),
    ("preferences.profile.citation.people.facts-field-7", "Event:Probate:False"),
    ("preferences.profile.citation.people.facts-field-8", "None"),
    ("preferences.profile.citation.people.metadata-attribute-1", "None"),
    ("preferences.profile.citation.people.metadata-attribute-2", "None"),
    ("preferences.profile.citation.people.metadata-attribute-3", "None"),
    ("preferences.profile.citation.people.metadata-attribute-4", "None"),
    ("preferences.profile.citation.people.metadata-attribute-5", "None"),
    ("preferences.profile.citation.people.metadata-attribute-6", "None"),
    ("preferences.profile.citation.people.metadata-attribute-7", "None"),
    ("preferences.profile.citation.people.metadata-attribute-8", "None"),
    # Events Referenced
    ("preferences.profile.citation.events.tag-format", 1),
    ("preferences.profile.citation.events.tag-width", 10),
    ("preferences.profile.citation.events.image-mode", 0),
    ("preferences.profile.citation.events.color-scheme", 0),
    ("preferences.profile.citation.events.show-description", True),
    ("preferences.profile.citation.events.show-participants", True),
    ("preferences.profile.citation.events.show-role-always", False),
    ("preferences.profile.citation.events.show-source-count", True),
    ("preferences.profile.citation.events.show-citation-count", True),
    ("preferences.profile.citation.events.show-best-confidence", True),
    ("preferences.profile.citation.events.metadata-attribute-1", "None"),
    ("preferences.profile.citation.events.metadata-attribute-2", "None"),
    ("preferences.profile.citation.events.metadata-attribute-3", "None"),
    ("preferences.profile.citation.events.metadata-attribute-4", "None"),
    # Media
    ("preferences.profile.citation.media.tag-format", 1),
    ("preferences.profile.citation.media.tag-width", 10),
    ("preferences.profile.citation.media.image-mode", 2),
    ("preferences.profile.citation.media.sort-by-date", False),
    ("preferences.profile.citation.media.show-date", True),
    ("preferences.profile.citation.media.metadata-attribute-1", "None"),
    ("preferences.profile.citation.media.metadata-attribute-2", "None"),
    ("preferences.profile.citation.media.metadata-attribute-3", "None"),
    ("preferences.profile.citation.media.metadata-attribute-4", "None"),
    # Note
    ("preferences.profile.citation.note.tag-format", 1),
    ("preferences.profile.citation.note.tag-width", 10),
    ######################################################################
    # Repository Page Options
    ######################################################################
    # Layout
    ("preferences.profile.repository.layout.tabbed", False),
    ("preferences.profile.repository.layout.columns", "source,note"),
    ("preferences.profile.repository.layout.source.visible", True),
    ("preferences.profile.repository.layout.source.stacked", False),
    ("preferences.profile.repository.layout.note.visible", False),
    ("preferences.profile.repository.layout.note.stacked", False),
    # Old Layout
    ("preferences.profile.repository.page.show-notes", True),
    ("preferences.profile.repository.page.enable-tooltips", True),
    ("preferences.profile.repository.page.enable-warnings", True),
    ("preferences.profile.repository.page.pinned-header", True),
    ("preferences.profile.repository.page.border-width", 2),
    ("preferences.profile.repository.page.use-color-scheme", True),
    ("preferences.profile.repository.page.use-smaller-detail-font", True),
    ("preferences.profile.repository.page.sort-tags-by-name", False),
    ("preferences.profile.repository.page.include-child-notes", False),
    ("preferences.profile.repository.page.right-to-left", False),
    # Active Repository
    ("preferences.profile.repository.active.tag-format", 1),
    ("preferences.profile.repository.active.tag-width", 10),
    # Sources
    ("preferences.profile.repository.source.image-mode", 3),
    ("preferences.profile.repository.source.tag-format", 1),
    ("preferences.profile.repository.source.tag-width", 10),
    ("preferences.profile.repository.source.metadata-attribute-1", "None"),
    ("preferences.profile.repository.source.metadata-attribute-2", "None"),
    ("preferences.profile.repository.source.metadata-attribute-3", "None"),
    ("preferences.profile.repository.source.metadata-attribute-4", "None"),
    # Note
    ("preferences.profile.repository.note.tag-format", 1),
    ("preferences.profile.repository.note.tag-width", 10),
    ######################################################################
    # Note Page Options
    ######################################################################
    # Layout
    ("preferences.profile.note.layout.tabbed", False),
    ("preferences.profile.note.layout.columns", "reference"),
    ("preferences.profile.note.layout.reference.visible", True),
    ("preferences.profile.note.layout.reference.stacked", False),
    # Old Layout
    ("preferences.profile.note.page.enable-tooltips", True),
    ("preferences.profile.note.page.enable-warnings", True),
    ("preferences.profile.note.page.pinned-header", True),
    ("preferences.profile.note.page.border-width", 2),
    ("preferences.profile.note.page.use-color-scheme", True),
    ("preferences.profile.note.page.use-smaller-detail-font", True),
    ("preferences.profile.note.page.sort-tags-by-name", False),
    ("preferences.profile.note.page.right-to-left", False),
    # Active Note
    ("preferences.profile.note.active.tag-format", 1),
    ("preferences.profile.note.active.tag-width", 10),
    # For Reference Group Objects may need a plethora of options, need
    # to reconsider this.
    ######################################################################
    # Media Page Options
    ######################################################################
    # Layout
    ("preferences.profile.media.layout.tabbed", False),
    ("preferences.profile.media.layout.columns", "reference"),
    ("preferences.profile.media.layout.reference.visible", True),
    ("preferences.profile.media.layout.reference.stacked", False),
    # Old Layout
    ("preferences.profile.media.page.enable-tooltips", True),
    ("preferences.profile.media.page.enable-warnings", True),
    ("preferences.profile.media.page.pinned-header", True),
    ("preferences.profile.media.page.border-width", 2),
    ("preferences.profile.media.page.use-color-scheme", True),
    ("preferences.profile.media.page.use-smaller-detail-font", True),
    ("preferences.profile.media.page.sort-tags-by-name", False),
    ("preferences.profile.media.page.right-to-left", False),
    # Active Media
    ("preferences.profile.media.active.tag-format", 1),
    ("preferences.profile.media.active.tag-width", 10),
    # For Reference Group Objects may need a plethora of options, need
    # to reconsider this.    
    ######################################################################
    # Place Page Options
    ######################################################################
    # Layout
    ("preferences.profile.place.layout.tabbed", False),
    ("preferences.profile.place.layout.columns", "reference"),
    ("preferences.profile.place.layout.reference.visible", True),
    ("preferences.profile.place.layout.reference.stacked", False),
    # Old Layout
    ("preferences.profile.place.page.enable-tooltips", True),
    ("preferences.profile.place.page.enable-warnings", True),
    ("preferences.profile.place.page.pinned-header", True),
    ("preferences.profile.place.page.border-width", 2),
    ("preferences.profile.place.page.use-color-scheme", True),
    ("preferences.profile.place.page.use-smaller-detail-font", True),
    ("preferences.profile.place.page.sort-tags-by-name", False),
    ("preferences.profile.place.page.right-to-left", False),
    # Active Place
    ("preferences.profile.place.active.tag-format", 1),
    ("preferences.profile.place.active.tag-width", 10),
    # For Reference Group Objects may need a plethora of options, need
    # to reconsider this.    
)
