# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2021       Christopher Horn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Profile Options
"""

CONFIGSETTINGS = (
    ######################################################################
    # Active State
    ######################################################################
    ("options.active.last_object", "None"),
    ######################################################################
    # Additional Color Schemes
    ######################################################################
    # Confidence Color Scheme
    ('options.colors.confidence.very-high', ["#99c1f1","#304918"]),
    ('options.colors.confidence.high', ["#8ff0a4","#454545"]),
    ('options.colors.confidence.normal', ["#f9f06b","#454545"]),
    ('options.colors.confidence.low', ["#ffbe6f","#454545"]),
    ('options.colors.confidence.very-low', ["#f66161","#454545"]),
    ('options.colors.confidence.border-very-high', ["#1a5fb4","#000000"]),
    ('options.colors.confidence.border-high', ["#26a269","#000000"]),
    ('options.colors.confidence.border-normal', ["#e5a50a","#000000"]),
    ('options.colors.confidence.border-low', ["#c64600","#000000"]),
    ('options.colors.confidence.border-very-low', ["#a51d2d","#000000"]),
    # Relationship Color Scheme
    ('options.colors.relations.active', ["#bbe68e","#304918"]),
    ('options.colors.relations.spouse', ["#eeeeee","#454545"]),
    ('options.colors.relations.father', ["#eeeeee","#454545"]),
    ('options.colors.relations.mother', ["#eeeeee","#454545"]),
    ('options.colors.relations.brother', ["#eeeeee","#454545"]),
    ('options.colors.relations.sister', ["#eeeeee","#454545"]),
    ('options.colors.relations.son', ["#eeeeee","#454545"]),
    ('options.colors.relations.daughter', ["#eeeeee","#454545"]),
    ('options.colors.relations.none', ["#eeeeee","#454545"]),
    ('options.colors.relations.border-active', ["#cccccc","#000000"]),
    ('options.colors.relations.border-spouse', ["#cccccc","#000000"]),
    ('options.colors.relations.border-father', ["#cccccc","#000000"]),
    ('options.colors.relations.border-mother', ["#cccccc","#000000"]),
    ('options.colors.relations.border-brother', ["#cccccc","#000000"]),
    ('options.colors.relations.border-sister', ["#cccccc","#000000"]),
    ('options.colors.relations.border-son', ["#cccccc","#000000"]),
    ('options.colors.relations.border-daughter', ["#cccccc","#000000"]),
    ('options.colors.relations.border-none', ["#cccccc","#000000"]),
    # Event Category Color Scheme
    ('options.colors.events.vital', ["#bbe68e","#304918"]),
    ('options.colors.events.family', ["#eeeeee","#454545"]),
    ('options.colors.events.religious', ["#eeeeee","#454545"]),
    ('options.colors.events.vocational', ["#eeeeee","#454545"]),
    ('options.colors.events.academic', ["#eeeeee","#454545"]),
    ('options.colors.events.travel', ["#eeeeee","#454545"]),
    ('options.colors.events.legal', ["#eeeeee","#454545"]),
    ('options.colors.events.residence', ["#eeeeee","#454545"]),
    ('options.colors.events.other', ["#eeeeee","#454545"]),
    ('options.colors.events.custom', ["#eeeeee","#454545"]),
    ('options.colors.events.border-vital', ["#cccccc","#000000"]),
    ('options.colors.events.border-family', ["#cccccc","#000000"]),
    ('options.colors.events.border-religious', ["#cccccc","#000000"]),
    ('options.colors.events.border-vocational', ["#cccccc","#000000"]),
    ('options.colors.events.border-academic', ["#cccccc","#000000"]),
    ('options.colors.events.border-travel', ["#cccccc","#000000"]),
    ('options.colors.events.border-legal', ["#cccccc","#000000"]),
    ('options.colors.events.border-residence', ["#cccccc","#000000"]),
    ('options.colors.events.border-other', ["#cccccc","#000000"]),
    ('options.colors.events.border-custom', ["#cccccc","#000000"]),
    ######################################################################
    # Global Options
    ######################################################################
    ("options.global.use-smaller-detail-font", True),
    ("options.global.border-width", 2),
    ("options.global.link-citation-title-to-source", True),
    ("options.global.sort-tags-by-name", False),
    ("options.global.max-citations-per-group", 100),
    ("options.global.max-references-per-group", 100),
    ("options.global.enable-warnings", True),
    ("options.global.enable-tooltips", True),
    ######################################################################
    # Person Page Options
    ######################################################################
    # Layout Options
    ("options.person.layout.tabbed", False),
    ("options.person.layout.groups", "parent,timeline,citation,note,media,associations,spouse"),
    ("options.person.layout.parent.visible", True),
    ("options.person.layout.parent.stacked", False),
    ("options.person.layout.parent.hideable", False),
    ("options.person.layout.spouse.visible", True),
    ("options.person.layout.spouse.stacked", False),
    ("options.person.layout.spouse.hideable", False),
    ("options.person.layout.association.visible", True),
    ("options.person.layout.association.stacked", False),
    ("options.person.layout.association.hideable", False),
    ("options.person.layout.timeline.visible", True),
    ("options.person.layout.timeline.stacked", False),
    ("options.person.layout.timeline.hideable", False),
    ("options.person.layout.citation.visible", True),
    ("options.person.layout.citation.stacked", False),
    ("options.person.layout.citation.hideable", False),
    ("options.person.layout.note.visible", False),
    ("options.person.layout.note.stacked", False),
    ("options.person.layout.note.hideable", False),
    ("options.person.layout.media.visible", False),
    ("options.person.layout.media.stacked", False),
    ("options.person.layout.media.hideable", False),
    # Page Options
    ("options.person.page.pinned-header", True),
    ("options.person.page.use-color-scheme", True),
    ("options.person.page.include-child-notes", False),
    # Active Person
    ("options.person.active.event-format", 1),
    ("options.person.active.show-age", True),
    ("options.person.active.sex-mode", 1),
    ("options.person.active.image-mode", 3),
    ("options.person.active.tag-format", 1),
    ("options.person.active.tag-width", 10),
    ("options.person.active.facts-field-skip-birth-alternates", False),
    ("options.person.active.facts-field-skip-death-alternates", False),
    ("options.person.active.facts-field-1", "Event:Birth:False"),
    ("options.person.active.facts-field-2", "Event:Baptism:False"),
    ("options.person.active.facts-field-3", "Event:Christening:False"),
    ("options.person.active.facts-field-4", "Event:Death:False"),
    ("options.person.active.facts-field-5", "Event:Burial:False"),
    ("options.person.active.facts-field-6", "Event:Cremation:False"),
    ("options.person.active.facts-field-7", "Event:Probate:False"),
    ("options.person.active.facts-field-8", "None"),
    ("options.person.active.extra-field-skip-birth-alternates", False),
    ("options.person.active.extra-field-skip-death-alternates", False),
    ("options.person.active.extra-field-1", "None"),
    ("options.person.active.extra-field-2", "None"),
    ("options.person.active.extra-field-3", "None"),
    ("options.person.active.extra-field-4", "None"),
    ("options.person.active.extra-field-5", "None"),
    ("options.person.active.extra-field-6", "None"),
    ("options.person.active.extra-field-7", "None"),
    ("options.person.active.extra-field-8", "None"),
    ("options.person.active.metadata-attribute-1", "None"),
    ("options.person.active.metadata-attribute-2", "None"),
    ("options.person.active.metadata-attribute-3", "None"),
    ("options.person.active.metadata-attribute-4", "None"),
    ("options.person.active.metadata-attribute-5", "None"),
    ("options.person.active.metadata-attribute-6", "None"),
    ("options.person.active.metadata-attribute-7", "None"),
    ("options.person.active.metadata-attribute-8", "None"),
    # Parents
    ("options.person.parent.event-format", 1),
    ("options.person.parent.show-age", False),
    ("options.person.parent.sex-mode", 1),
    ("options.person.parent.image-mode", 1),
    ("options.person.parent.tag-format", 1),
    ("options.person.parent.tag-width", 10),
    ("options.person.parent.show-matrilineal", False),
    ("options.person.parent.expand-children", True),
    ("options.person.parent.show-divorce", True),
    ("options.person.parent.facts-field-skip-birth-alternates", True),
    ("options.person.parent.facts-field-skip-death-alternates", True),
    ("options.person.parent.facts-field-1", "Event:Birth:False"),
    ("options.person.parent.facts-field-2", "Event:Baptism:False"),
    ("options.person.parent.facts-field-3", "Event:Christening:False"),
    ("options.person.parent.facts-field-4", "Event:Death:False"),
    ("options.person.parent.facts-field-5", "Event:Burial:False"),
    ("options.person.parent.facts-field-6", "Event:Cremation:False"),
    ("options.person.parent.facts-field-7", "Event:Probate:False"),
    ("options.person.parent.facts-field-8", "None"),
    ("options.person.parent.metadata-attribute-1", "None"),
    ("options.person.parent.metadata-attribute-2", "None"),
    ("options.person.parent.metadata-attribute-3", "None"),
    ("options.person.parent.metadata-attribute-4", "None"),
    ("options.person.parent.metadata-attribute-5", "None"),
    ("options.person.parent.metadata-attribute-6", "None"),
    ("options.person.parent.metadata-attribute-7", "None"),
    ("options.person.parent.metadata-attribute-8", "None"),
    # Spouses
    ("options.person.spouse.event-format", 1),
    ("options.person.spouse.show-age", False),
    ("options.person.spouse.sex-mode", 1),
    ("options.person.spouse.image-mode", 3),
    ("options.person.spouse.tag-format", 1),
    ("options.person.spouse.tag-width", 10),
    ("options.person.spouse.expand-children", True),
    ("options.person.spouse.show-spouse-only", True),
    ("options.person.spouse.show-divorce", True),
    ("options.person.spouse.facts-field-skip-birth-alternates", True),
    ("options.person.spouse.facts-field-skip-death-alternates", True),
    ("options.person.spouse.facts-field-1", "Event:Birth:False"),
    ("options.person.spouse.facts-field-2", "Event:Baptism:False"),
    ("options.person.spouse.facts-field-3", "Event:Christening:False"),
    ("options.person.spouse.facts-field-4", "Event:Death:False"),
    ("options.person.spouse.facts-field-5", "Event:Burial:False"),
    ("options.person.spouse.facts-field-6", "Event:Cremation:False"),
    ("options.person.spouse.facts-field-7", "Event:Probate:False"),
    ("options.person.spouse.facts-field-8", "None"),
    ("options.person.spouse.metadata-attribute-1", "None"),
    ("options.person.spouse.metadata-attribute-2", "None"),
    ("options.person.spouse.metadata-attribute-3", "None"),
    ("options.person.spouse.metadata-attribute-4", "None"),
    ("options.person.spouse.metadata-attribute-5", "None"),
    ("options.person.spouse.metadata-attribute-6", "None"),
    ("options.person.spouse.metadata-attribute-7", "None"),
    ("options.person.spouse.metadata-attribute-8", "None"),
    # Children
    ("options.person.child.event-format", 1),
    ("options.person.child.show-age", False),
    ("options.person.child.sex-mode", 1),
    ("options.person.child.image-mode", 3),
    ("options.person.child.tag-format", 1),
    ("options.person.child.tag-width", 10),
    ("options.person.child.number-children", True),
    ("options.person.child.facts-field-skip-birth-alternates", True),
    ("options.person.child.facts-field-skip-death-alternates", True),
    ("options.person.child.facts-field-1", "Event:Birth:False"),
    ("options.person.child.facts-field-2", "Event:Baptism:False"),
    ("options.person.child.facts-field-3", "Event:Christening:False"),
    ("options.person.child.facts-field-4", "Event:Death:False"),
    ("options.person.child.facts-field-5", "Event:Burial:False"),
    ("options.person.child.facts-field-6", "Event:Cremation:False"),
    ("options.person.child.facts-field-7", "Event:Probate:False"),
    ("options.person.child.facts-field-8", "None"),
    ("options.person.child.metadata-attribute-1", "None"),
    ("options.person.child.metadata-attribute-2", "None"),
    ("options.person.child.metadata-attribute-3", "None"),
    ("options.person.child.metadata-attribute-4", "None"),
    ("options.person.child.metadata-attribute-5", "None"),
    ("options.person.child.metadata-attribute-6", "None"),
    ("options.person.child.metadata-attribute-7", "None"),
    ("options.person.child.metadata-attribute-8", "None"),
    # Siblings
    ("options.person.sibling.event-format", 1),
    ("options.person.sibling.show-age", False),
    ("options.person.sibling.sex-mode", 1),
    ("options.person.sibling.image-mode", 1),
    ("options.person.sibling.tag-format", 1),
    ("options.person.sibling.tag-width", 10),
    ("options.person.sibling.number-children", True),
    ("options.person.sibling.facts-field-skip-birth-alternates", True),
    ("options.person.sibling.facts-field-skip-death-alternates", True),
    ("options.person.sibling.facts-field-1", "Event:Birth:False"),
    ("options.person.sibling.facts-field-2", "Event:Baptism:False"),
    ("options.person.sibling.facts-field-3", "Event:Christening:False"),
    ("options.person.sibling.facts-field-4", "Event:Death:False"),
    ("options.person.sibling.facts-field-5", "Event:Burial:False"),
    ("options.person.sibling.facts-field-6", "Event:Cremation:False"),
    ("options.person.sibling.facts-field-7", "Event:Probate:False"),
    ("options.person.sibling.facts-field-8", "None"),
    ("options.person.sibling.metadata-attribute-1", "None"),
    ("options.person.sibling.metadata-attribute-2", "None"),
    ("options.person.sibling.metadata-attribute-3", "None"),
    ("options.person.sibling.metadata-attribute-4", "None"),
    ("options.person.sibling.metadata-attribute-5", "None"),
    ("options.person.sibling.metadata-attribute-6", "None"),
    ("options.person.sibling.metadata-attribute-7", "None"),
    ("options.person.sibling.metadata-attribute-8", "None"),
    # Associations
    ("options.person.association.event-format", 1),
    ("options.person.association.show-age", False),
    ("options.person.association.sex-mode", 1),
    ("options.person.association.image-mode", 1),
    ("options.person.association.tag-format", 1),
    ("options.person.association.tag-width", 10),
    ("options.person.association.facts-field-skip-birth-alternates", True),
    ("options.person.association.facts-field-skip-death-alternates", True),
    ("options.person.association.facts-field-1", "Event:Birth:False"),
    ("options.person.association.facts-field-2", "Event:Baptism:False"),
    ("options.person.association.facts-field-3", "Event:Christening:False"),
    ("options.person.association.facts-field-4", "Event:Death:False"),
    ("options.person.association.facts-field-5", "Event:Burial:False"),
    ("options.person.association.facts-field-6", "Event:Cremation:False"),
    ("options.person.association.facts-field-7", "Event:Probate:False"),
    ("options.person.association.facts-field-8", "None"),
    ("options.person.association.metadata-attribute-1", "None"),
    ("options.person.association.metadata-attribute-2", "None"),
    ("options.person.association.metadata-attribute-3", "None"),
    ("options.person.association.metadata-attribute-4", "None"),
    ("options.person.association.metadata-attribute-5", "None"),
    ("options.person.association.metadata-attribute-6", "None"),
    ("options.person.association.metadata-attribute-7", "None"),
    ("options.person.association.metadata-attribute-8", "None"),
    # Person Timeline
    ("options.person.timeline.tag-format", 1),
    ("options.person.timeline.tag-width", 10),
    ("options.person.timeline.image-mode", 0),
    ("options.person.timeline.color-scheme", 0),
    ("options.person.timeline.show-description", True),
    ("options.person.timeline.show-participants", True),
    ("options.person.timeline.show-role-always", False),
    ("options.person.timeline.show-source-count", True),
    ("options.person.timeline.show-citation-count", True),
    ("options.person.timeline.show-best-confidence", True),
    ("options.person.timeline.show-age", True),
    ("options.person.timeline.metadata-attribute-1", "None"),
    ("options.person.timeline.metadata-attribute-2", "None"),
    ("options.person.timeline.metadata-attribute-3", "None"),
    ("options.person.timeline.metadata-attribute-4", "None"),
    ("options.person.timeline.show-class-vital", True),
    ("options.person.timeline.show-class-family", True),
    ("options.person.timeline.show-class-religious", True),
    ("options.person.timeline.show-class-vocational", True),
    ("options.person.timeline.show-class-academic", True),
    ("options.person.timeline.show-class-travel", True),
    ("options.person.timeline.show-class-legal", True),
    ("options.person.timeline.show-class-residence", True),
    ("options.person.timeline.show-class-other", True),
    ("options.person.timeline.show-class-custom", True),
    ("options.person.timeline.generations-ancestors", 1),
    ("options.person.timeline.generations-offspring", 1),
    ("options.person.timeline.show-family-father", True),
    ("options.person.timeline.show-family-mother", True),
    ("options.person.timeline.show-family-brother", True),
    ("options.person.timeline.show-family-sister", True),
    ("options.person.timeline.show-family-wife", True),
    ("options.person.timeline.show-family-husband", True),
    ("options.person.timeline.show-family-son", True),
    ("options.person.timeline.show-family-daughter", True),
    ("options.person.timeline.show-family-class-vital", False),
    ("options.person.timeline.show-family-class-family", False),
    ("options.person.timeline.show-family-class-religious", False),
    ("options.person.timeline.show-family-class-vocational", False),
    ("options.person.timeline.show-family-class-academic", False),
    ("options.person.timeline.show-family-class-travel", False),
    ("options.person.timeline.show-family-class-legal", False),
    ("options.person.timeline.show-family-class-residence", False),
    ("options.person.timeline.show-family-class-other", False),
    ("options.person.timeline.show-family-class-custom", False),
    # Supporting Citations
    ("options.person.citation.tag-format", 1),
    ("options.person.citation.tag-width", 10),
    ("options.person.citation.image-mode", 0),
    ("options.person.citation.sort-by-date", False),
    ("options.person.citation.include-indirect", True),
    ("options.person.citation.include-parent-family", True),
    ("options.person.citation.include-family", True),
    ("options.person.citation.include-family-indirect", True),
    ("options.person.citation.show-date", True),
    ("options.person.citation.show-publisher", True),
    ("options.person.citation.show-reference-type", True),
    ("options.person.citation.show-reference-description", True),
    ("options.person.citation.show-confidence", True),
    ("options.person.citation.metadata-attribute-1", "None"),
    ("options.person.citation.metadata-attribute-2", "None"),
    ("options.person.citation.metadata-attribute-3", "None"),
    ("options.person.citation.metadata-attribute-4", "None"),
    # Media
    ("options.person.media.tag-format", 1),
    ("options.person.media.tag-width", 10),
    ("options.person.media.image-mode", 2),
    ("options.person.media.sort-by-date", False),
    ("options.person.media.show-date", True),
    ("options.person.media.metadata-attribute-1", "None"),
    ("options.person.media.metadata-attribute-2", "None"),
    ("options.person.media.metadata-attribute-3", "None"),
    ("options.person.media.metadata-attribute-4", "None"),
    # Note
    ("options.person.note.preview-mode", True),
    ("options.person.note.preview-lines", 4),
    ("options.person.note.tag-format", 1),
    ("options.person.note.tag-width", 10),
    ######################################################################
    # Family Page Options
    ######################################################################
    # Layout Options
    ("options.family.layout.tabbed", False),
    ("options.family.layout.groups", "child,timeline,citation,note,media"),
    ("options.family.layout.child.visible", True),
    ("options.family.layout.child.stacked", False),
    ("options.family.layout.child.hideable", False),
    ("options.family.layout.timeline.visible", True),
    ("options.family.layout.timeline.stacked", False),
    ("options.family.layout.timeline.hideable", False),
    ("options.family.layout.citation.visible", True),
    ("options.family.layout.citation.stacked", False),
    ("options.family.layout.citation.hideable", False),
    ("options.family.layout.note.visible", True),
    ("options.family.layout.note.stacked", False),
    ("options.family.layout.note.hideable", False),
    ("options.family.layout.media.visible", True),
    ("options.family.layout.media.stacked", False),
    ("options.family.layout.media.hideable", False),
    # Page Options
    ("options.family.page.use-color-scheme", True),
    ("options.family.page.include-child-notes", False),
    # Active Family
    ("options.family.active.event-format", 1),
    ("options.family.active.show-age", True),
    ("options.family.active.sex-mode", 1),
    ("options.family.active.image-mode", 3),
    ("options.family.active.tag-format", 1),
    ("options.family.active.tag-width", 10),
    ("options.family.active.facts-field-skip-birth-alternates", False),
    ("options.family.active.facts-field-skip-death-alternates", False),
    ("options.family.active.facts-field-1", "Event:Birth:False"),
    ("options.family.active.facts-field-2", "Event:Baptism:False"),
    ("options.family.active.facts-field-3", "Event:Christening:False"),
    ("options.family.active.facts-field-4", "Event:Death:False"),
    ("options.family.active.facts-field-5", "Event:Burial:False"),
    ("options.family.active.facts-field-6", "Event:Cremation:False"),
    ("options.family.active.facts-field-7", "Event:Probate:False"),
    ("options.family.active.facts-field-8", "None"),
    ("options.family.active.metadata-attribute-1", "None"),
    ("options.family.active.metadata-attribute-2", "None"),
    ("options.family.active.metadata-attribute-3", "None"),
    ("options.family.active.metadata-attribute-4", "None"),
    ("options.family.active.metadata-attribute-5", "None"),
    ("options.family.active.metadata-attribute-6", "None"),
    ("options.family.active.metadata-attribute-7", "None"),
    ("options.family.active.metadata-attribute-8", "None"),
    # Parents
    ("options.family.parent.event-format", 1),
    ("options.family.parent.show-age", False),
    ("options.family.parent.sex-mode", 1),
    ("options.family.parent.image-mode", 1),
    ("options.family.parent.tag-format", 1),
    ("options.family.parent.tag-width", 10),
    ("options.family.parent.show-matrilineal", False),
    ("options.family.parent.expand-children", True),
    ("options.family.parent.show-divorce", True),
    ("options.family.parent.facts-field-skip-birth-alternates", True),
    ("options.family.parent.facts-field-skip-death-alternates", True),
    ("options.family.parent.facts-field-1", "Event:Birth:False"),
    ("options.family.parent.facts-field-2", "Event:Baptism:False"),
    ("options.family.parent.facts-field-3", "Event:Christening:False"),
    ("options.family.parent.facts-field-4", "Event:Death:False"),
    ("options.family.parent.facts-field-5", "Event:Burial:False"),
    ("options.family.parent.facts-field-6", "Event:Cremation:False"),
    ("options.family.parent.facts-field-7", "Event:Probate:False"),
    ("options.family.parent.facts-field-8", "None"),
    ("options.family.parent.metadata-attribute-1", "None"),
    ("options.family.parent.metadata-attribute-2", "None"),
    ("options.family.parent.metadata-attribute-3", "None"),
    ("options.family.parent.metadata-attribute-4", "None"),
    ("options.family.parent.metadata-attribute-5", "None"),
    ("options.family.parent.metadata-attribute-6", "None"),
    ("options.family.parent.metadata-attribute-7", "None"),
    ("options.family.parent.metadata-attribute-8", "None"),
    # Children
    ("options.family.child.event-format", 1),
    ("options.family.child.show-age", False),
    ("options.family.child.sex-mode", 1),
    ("options.family.child.image-mode", 3),
    ("options.family.child.tag-format", 1),
    ("options.family.child.tag-width", 10),
    ("options.family.child.number-children", True),
    ("options.family.child.facts-field-skip-birth-alternates", True),
    ("options.family.child.facts-field-skip-death-alternates", True),
    ("options.family.child.facts-field-1", "Event:Birth:False"),
    ("options.family.child.facts-field-2", "Event:Baptism:False"),
    ("options.family.child.facts-field-3", "Event:Christening:False"),
    ("options.family.child.facts-field-4", "Event:Death:False"),
    ("options.family.child.facts-field-5", "Event:Burial:False"),
    ("options.family.child.facts-field-6", "Event:Cremation:False"),
    ("options.family.child.facts-field-7", "Event:Probate:False"),
    ("options.family.child.facts-field-8", "None"),
    ("options.family.child.metadata-attribute-1", "None"),
    ("options.family.child.metadata-attribute-2", "None"),
    ("options.family.child.metadata-attribute-3", "None"),
    ("options.family.child.metadata-attribute-4", "None"),
    ("options.family.child.metadata-attribute-5", "None"),
    ("options.family.child.metadata-attribute-6", "None"),
    ("options.family.child.metadata-attribute-7", "None"),
    ("options.family.child.metadata-attribute-8", "None"),
    # Family Timeline
    ("options.family.timeline.tag-format", 1),
    ("options.family.timeline.tag-width", 10),
    ("options.family.timeline.image-mode", 0),
    ("options.family.timeline.color-scheme", 0),
    ("options.family.timeline.show-description", True),
    ("options.family.timeline.show-participants", True),
    ("options.family.timeline.show-role-always", False),
    ("options.family.timeline.show-source-count", True),
    ("options.family.timeline.show-citation-count", True),
    ("options.family.timeline.show-best-confidence", True),
    ("options.family.timeline.show-age", True),
    ("options.family.timeline.metadata-attribute-1", "None"),
    ("options.family.timeline.metadata-attribute-2", "None"),
    ("options.family.timeline.metadata-attribute-3", "None"),
    ("options.family.timeline.metadata-attribute-4", "None"),
    ("options.family.timeline.show-class-vital", True),
    ("options.family.timeline.show-class-family", True),
    ("options.family.timeline.show-class-religious", True),
    ("options.family.timeline.show-class-vocational", True),
    ("options.family.timeline.show-class-academic", True),
    ("options.family.timeline.show-class-travel", True),
    ("options.family.timeline.show-class-legal", True),
    ("options.family.timeline.show-class-residence", True),
    ("options.family.timeline.show-class-other", True),
    ("options.family.timeline.show-class-custom", True),
    ("options.family.timeline.generations-ancestors", 1),
    ("options.family.timeline.generations-offspring", 1),
    # Supporting Citations
    ("options.family.citation.tag-format", 1),
    ("options.family.citation.tag-width", 10),
    ("options.family.citation.image-mode", 0),
    ("options.family.citation.sort-by-date", False),
    ("options.family.citation.include-indirect", True),
    ("options.family.citation.include-parent-family", True),
    ("options.family.citation.include-family", True),
    ("options.family.citation.include-family-indirect", True),
    ("options.family.citation.show-date", True),
    ("options.family.citation.show-publisher", True),
    ("options.family.citation.show-reference-type", True),
    ("options.family.citation.show-reference-description", True),
    ("options.family.citation.show-confidence", True),
    ("options.family.citation.metadata-attribute-1", "None"),
    ("options.family.citation.metadata-attribute-2", "None"),
    ("options.family.citation.metadata-attribute-3", "None"),
    ("options.family.citation.metadata-attribute-4", "None"),
    # Media
    ("options.family.media.tag-format", 1),
    ("options.family.media.tag-width", 10),
    ("options.family.media.image-mode", 2),
    ("options.family.media.sort-by-date", False),
    ("options.family.media.show-date", True),
    ("options.family.media.metadata-attribute-1", "None"),
    ("options.family.media.metadata-attribute-2", "None"),
    ("options.family.media.metadata-attribute-3", "None"),
    ("options.family.media.metadata-attribute-4", "None"),
    # Note
    ("options.family.note.preview-mode", True),
    ("options.family.note.preview-lines", 4),
    ("options.family.note.tag-format", 1),
    ("options.family.note.tag-width", 10),
    ######################################################################
    # Event Page Options
    ######################################################################
    # Layout Options
    ("options.event.layout.tabbed", False),
    ("options.event.layout.groups", "people,family,citation,note,media"),
    ("options.event.layout.people.visible", True),
    ("options.event.layout.people.stacked", False),
    ("options.event.layout.people.hideable", False),
    ("options.event.layout.family.visible", True),
    ("options.event.layout.family.stacked", False),
    ("options.event.layout.family.hideable", False),
    ("options.event.layout.citation.visible", True),
    ("options.event.layout.citation.stacked", False),
    ("options.event.layout.citation.hideable", False),
    ("options.event.layout.note.visible", True),
    ("options.event.layout.note.stacked", False),
    ("options.event.layout.note.hideable", False),
    ("options.event.layout.media.visible", True),
    ("options.event.layout.media.stacked", False),
    ("options.event.layout.media.hideable", False),
    # Page Options
    ("options.event.page.pinned-header", True),
    ("options.event.page.use-color-scheme", True),
    ("options.event.page.include-child-notes", False),
    # Active Event
    ("options.event.active.event-format", 1),
    ("options.event.active.image-mode", 3),
    ("options.event.active.tag-format", 1),
    ("options.event.active.tag-width", 10),
    ("options.event.active.metadata-attribute-1", "None"),
    ("options.event.active.metadata-attribute-2", "None"),
    ("options.event.active.metadata-attribute-3", "None"),
    ("options.event.active.metadata-attribute-4", "None"),
    # Individual Participants
    ("options.event.people.event-format", 1),
    ("options.event.people.show-age", False),
    ("options.event.people.sex-mode", 1),
    ("options.event.people.image-mode", 1),
    ("options.event.people.tag-format", 1),
    ("options.event.people.tag-width", 10),
    ("options.event.people.facts-field-skip-birth-alternates", True),
    ("options.event.people.facts-field-skip-death-alternates", True),
    ("options.event.people.facts-field-1", "Event:Birth:False"),
    ("options.event.people.facts-field-2", "Event:Baptism:False"),
    ("options.event.people.facts-field-3", "Event:Christening:False"),
    ("options.event.people.facts-field-4", "Event:Death:False"),
    ("options.event.people.facts-field-5", "Event:Burial:False"),
    ("options.event.people.facts-field-6", "Event:Cremation:False"),
    ("options.event.people.facts-field-7", "Event:Probate:False"),
    ("options.event.people.facts-field-8", "None"),
    ("options.event.people.metadata-attribute-1", "None"),
    ("options.event.people.metadata-attribute-2", "None"),
    ("options.event.people.metadata-attribute-3", "None"),
    ("options.event.people.metadata-attribute-4", "None"),
    ("options.event.people.metadata-attribute-5", "None"),
    ("options.event.people.metadata-attribute-6", "None"),
    ("options.event.people.metadata-attribute-7", "None"),
    ("options.event.people.metadata-attribute-8", "None"),
    # Family Participants
    ("options.event.family.event-format", 1),
    ("options.event.family.image-mode", 1),
    ("options.event.family.tag-format", 1),
    ("options.event.family.tag-width", 10),
    ("options.event.family.metadata-attribute-1", "None"),
    ("options.event.family.metadata-attribute-2", "None"),
    ("options.event.family.metadata-attribute-3", "None"),
    ("options.event.family.metadata-attribute-4", "None"),
    # Media
    ("options.event.media.tag-format", 1),
    ("options.event.media.tag-width", 10),
    ("options.event.media.image-mode", 2),
    ("options.event.media.sort-by-date", False),
    ("options.event.media.show-date", True),
    ("options.event.media.metadata-attribute-1", "None"),
    ("options.event.media.metadata-attribute-2", "None"),
    ("options.event.media.metadata-attribute-3", "None"),
    ("options.event.media.metadata-attribute-4", "None"),
    # Note
    ("options.event.note.preview-mode", True),
    ("options.event.note.preview-lines", 4),
    ("options.event.note.tag-format", 1),
    ("options.event.note.tag-width", 10),
    ######################################################################
    # Source Page Options
    ######################################################################
    # Layout Options
    ("options.source.layout.tabbed", False),
    ("options.source.layout.groups", "repository,citation,note,people,event,media"),
    ("options.source.layout.repository.visible", True),
    ("options.source.layout.repository.stacked", False),
    ("options.source.layout.repository.hideable", False),
    ("options.source.layout.citation.visible", True),
    ("options.source.layout.citation.stacked", False),
    ("options.source.layout.citation.hideable", False),
    ("options.source.layout.note.visible", True),
    ("options.source.layout.note.stacked", False),
    ("options.source.layout.note.hideable", False),
    ("options.source.layout.people.visible", True),
    ("options.source.layout.people.stacked", False),
    ("options.source.layout.people.hideable", False),
    ("options.source.layout.event.visible", True),
    ("options.source.layout.event.stacked", False),
    ("options.source.layout.event.hideable", False),
    ("options.source.layout.media.visible", True),
    ("options.source.layout.media.stacked", False),
    ("options.source.layout.media.hideable", False),
    # Page Options
    ("options.source.page.pinned-header", True),
    ("options.source.page.use-color-scheme", True),
    ("options.source.page.include-child-notes", False),
    # Active Source
    ("options.source.active.event-format", 1),
    ("options.source.active.image-mode", 3),
    ("options.source.active.tag-format", 1),
    ("options.source.active.tag-width", 10),
    ("options.source.active.metadata-attribute-1", "None"),
    ("options.source.active.metadata-attribute-2", "None"),
    ("options.source.active.metadata-attribute-3", "None"),
    ("options.source.active.metadata-attribute-4", "None"),
    # Repositories
    ("options.source.repository.tag-format", 1),
    ("options.source.repository.tag-width", 10),
    ("options.source.repository.show-call-number", True),
    ("options.source.repository.show-media-type", True),
    ("options.source.repository.show-repository-type", True),
    # Source Citations
    ("options.source.citation.tag-format", 1),
    ("options.source.citation.tag-width", 10),
    ("options.source.citation.image-mode", 0),
    ("options.source.citation.sort-by-date", False),
    ("options.source.citation.show-date", True),
    ("options.source.citation.show-publisher", True),
    ("options.source.citation.show-reference-type", True),
    ("options.source.citation.show-reference-description", True),
    ("options.source.citation.show-confidence", True),
    ("options.source.citation.metadata-attribute-1", "None"),
    ("options.source.citation.metadata-attribute-2", "None"),
    ("options.source.citation.metadata-attribute-3", "None"),
    ("options.source.citation.metadata-attribute-4", "None"),
    # People Referenced
    ("options.source.people.event-format", 1),
    ("options.source.people.show-age", False),
    ("options.source.people.sex-mode", 1),
    ("options.source.people.image-mode", 1),
    ("options.source.people.tag-format", 1),
    ("options.source.people.tag-width", 10),
    ("options.source.people.facts-field-skip-birth-alternates", True),
    ("options.source.people.facts-field-skip-death-alternates", True),
    ("options.source.people.facts-field-1", "Event:Birth:False"),
    ("options.source.people.facts-field-2", "Event:Baptism:False"),
    ("options.source.people.facts-field-3", "Event:Christening:False"),
    ("options.source.people.facts-field-4", "Event:Death:False"),
    ("options.source.people.facts-field-5", "Event:Burial:False"),
    ("options.source.people.facts-field-6", "Event:Cremation:False"),
    ("options.source.people.facts-field-7", "Event:Probate:False"),
    ("options.source.people.facts-field-8", "None"),
    ("options.source.people.metadata-attribute-1", "None"),
    ("options.source.people.metadata-attribute-2", "None"),
    ("options.source.people.metadata-attribute-3", "None"),
    ("options.source.people.metadata-attribute-4", "None"),
    ("options.source.people.metadata-attribute-5", "None"),
    ("options.source.people.metadata-attribute-6", "None"),
    ("options.source.people.metadata-attribute-7", "None"),
    ("options.source.people.metadata-attribute-8", "None"),
    # Events Referenced
    ("options.source.events.tag-format", 1),
    ("options.source.events.tag-width", 10),
    ("options.source.events.image-mode", 0),
    ("options.source.events.color-scheme", 0),
    ("options.source.events.show-description", True),
    ("options.source.events.show-participants", True),
    ("options.source.events.show-role-always", False),
    ("options.source.events.show-source-count", True),
    ("options.source.events.show-citation-count", True),
    ("options.source.events.show-best-confidence", True),
    ("options.source.events.metadata-attribute-1", "None"),
    ("options.source.events.metadata-attribute-2", "None"),
    ("options.source.events.metadata-attribute-3", "None"),
    ("options.source.events.metadata-attribute-4", "None"),
    # Media
    ("options.source.media.tag-format", 1),
    ("options.source.media.tag-width", 10),
    ("options.source.media.image-mode", 2),
    ("options.source.media.sort-by-date", False),
    ("options.source.media.show-date", True),
    ("options.source.media.metadata-attribute-1", "None"),
    ("options.source.media.metadata-attribute-2", "None"),
    ("options.source.media.metadata-attribute-3", "None"),
    ("options.source.media.metadata-attribute-4", "None"),
    # Note
    ("options.source.note.preview-mode", True),
    ("options.source.note.preview-lines", 4),
    ("options.source.note.tag-format", 1),
    ("options.source.note.tag-width", 10),
    ######################################################################
    # Citation Page Options
    ######################################################################
    # Layout Options
    ("options.citation.layout.tabbed", False),
    ("options.citation.layout.groups", "reference,note,media"),
    ("options.citation.layout.reference.visible", True),
    ("options.citation.layout.reference.stacked", False),
    ("options.citation.layout.reference.hideable", False),
    ("options.citation.layout.note.visible", True),
    ("options.citation.layout.note.stacked", False),
    ("options.citation.layout.note.hideable", False),
    ("options.citation.layout.media.visible", True),
    ("options.citation.layout.media.stacked", False),
    ("options.citation.layout.media.hideable", False),
    # Page Options
    ("options.citation.page.pinned-header", True),
    ("options.citation.page.use-color-scheme", True),
    ("options.citation.page.include-child-notes", False),
    # Active Citation
    ("options.citation.active.tag-format", 1),
    ("options.citation.active.tag-width", 10),
    ("options.citation.active.image-mode", 0),
    ("options.citation.active.sort-by-date", False),
    ("options.citation.active.show-date", True),
    ("options.citation.active.show-publisher", True),
    ("options.citation.active.show-reference-type", True),
    ("options.citation.active.show-reference-description", True),
    ("options.citation.active.show-confidence", True),
    ("options.citation.active.metadata-attribute-1", "None"),
    ("options.citation.active.metadata-attribute-2", "None"),
    ("options.citation.active.metadata-attribute-3", "None"),
    ("options.citation.active.metadata-attribute-4", "None"),
    # Source
    ("options.citation.source.event-format", 1),
    ("options.citation.source.image-mode", 3),
    ("options.citation.source.tag-format", 1),
    ("options.citation.source.tag-width", 10),
    ("options.citation.source.metadata-attribute-1", "None"),
    ("options.citation.source.metadata-attribute-2", "None"),
    ("options.citation.source.metadata-attribute-3", "None"),
    ("options.citation.source.metadata-attribute-4", "None"),
    # Repositories
    ("options.citation.repository.tag-format", 1),
    ("options.citation.repository.tag-width", 10),
    ("options.citation.repository.show-call-number", True),
    ("options.citation.repository.show-media-type", True),
    ("options.citation.repository.show-repository-type", True),
    # People Referenced
    ("options.citation.people.event-format", 1),
    ("options.citation.people.show-age", False),
    ("options.citation.people.sex-mode", 1),
    ("options.citation.people.image-mode", 1),
    ("options.citation.people.tag-format", 1),
    ("options.citation.people.tag-width", 10),
    ("options.citation.people.facts-field-skip-birth-alternates", True),
    ("options.citation.people.facts-field-skip-death-alternates", True),
    ("options.citation.people.facts-field-1", "Event:Birth:False"),
    ("options.citation.people.facts-field-2", "Event:Baptism:False"),
    ("options.citation.people.facts-field-3", "Event:Christening:False"),
    ("options.citation.people.facts-field-4", "Event:Death:False"),
    ("options.citation.people.facts-field-5", "Event:Burial:False"),
    ("options.citation.people.facts-field-6", "Event:Cremation:False"),
    ("options.citation.people.facts-field-7", "Event:Probate:False"),
    ("options.citation.people.facts-field-8", "None"),
    ("options.citation.people.metadata-attribute-1", "None"),
    ("options.citation.people.metadata-attribute-2", "None"),
    ("options.citation.people.metadata-attribute-3", "None"),
    ("options.citation.people.metadata-attribute-4", "None"),
    ("options.citation.people.metadata-attribute-5", "None"),
    ("options.citation.people.metadata-attribute-6", "None"),
    ("options.citation.people.metadata-attribute-7", "None"),
    ("options.citation.people.metadata-attribute-8", "None"),
    # Events Referenced
    ("options.citation.events.tag-format", 1),
    ("options.citation.events.tag-width", 10),
    ("options.citation.events.image-mode", 0),
    ("options.citation.events.color-scheme", 0),
    ("options.citation.events.show-description", True),
    ("options.citation.events.show-participants", True),
    ("options.citation.events.show-role-always", False),
    ("options.citation.events.show-source-count", True),
    ("options.citation.events.show-citation-count", True),
    ("options.citation.events.show-best-confidence", True),
    ("options.citation.events.metadata-attribute-1", "None"),
    ("options.citation.events.metadata-attribute-2", "None"),
    ("options.citation.events.metadata-attribute-3", "None"),
    ("options.citation.events.metadata-attribute-4", "None"),
    # Media
    ("options.citation.media.tag-format", 1),
    ("options.citation.media.tag-width", 10),
    ("options.citation.media.image-mode", 2),
    ("options.citation.media.sort-by-date", False),
    ("options.citation.media.show-date", True),
    ("options.citation.media.metadata-attribute-1", "None"),
    ("options.citation.media.metadata-attribute-2", "None"),
    ("options.citation.media.metadata-attribute-3", "None"),
    ("options.citation.media.metadata-attribute-4", "None"),
    # Note
    ("options.citation.note.preview-mode", True),
    ("options.citation.note.preview-lines", 4),
    ("options.citation.note.tag-format", 1),
    ("options.citation.note.tag-width", 10),
    ######################################################################
    # Repository Page Options
    ######################################################################
    # Layout Options
    ("options.repository.layout.tabbed", False),
    ("options.repository.layout.groups", "source,note"),
    ("options.repository.layout.source.visible", True),
    ("options.repository.layout.source.stacked", False),
    ("options.repository.layout.source.hideable", False),
    ("options.repository.layout.note.visible", True),
    ("options.repository.layout.note.stacked", False),
    ("options.repository.layout.note.hideable", False),
    # Page Options
    ("options.repository.page.pinned-header", True),
    ("options.repository.page.use-color-scheme", True),
    ("options.repository.page.include-child-notes", False),
    # Active Repository
    ("options.repository.active.tag-format", 1),
    ("options.repository.active.tag-width", 10),
    # Sources
    ("options.repository.source.image-mode", 3),
    ("options.repository.source.tag-format", 1),
    ("options.repository.source.tag-width", 10),
    ("options.repository.source.metadata-attribute-1", "None"),
    ("options.repository.source.metadata-attribute-2", "None"),
    ("options.repository.source.metadata-attribute-3", "None"),
    ("options.repository.source.metadata-attribute-4", "None"),
    # Note
    ("options.repository.note.preview-mode", True),
    ("options.repository.note.preview-lines", 4),
    ("options.repository.note.tag-format", 1),
    ("options.repository.note.tag-width", 10),
    ######################################################################
    # Note Page Options
    ######################################################################
    # Layout Options
    ("options.note.layout.tabbed", False),
    ("options.note.layout.groups", "reference"),
    ("options.note.layout.reference.visible", True),
    ("options.note.layout.reference.stacked", False),
    ("options.note.layout.reference.hideable", False),
    # Page Options
    ("options.note.page.pinned-header", True),
    ("options.note.page.use-color-scheme", True),
    # Active Note
    ("options.note.active.preview-mode", False),
    ("options.note.active.preview-lines", 4),
    ("options.note.active.tag-format", 1),
    ("options.note.active.tag-width", 10),
    # For Reference Group Objects may need a plethora of options, need
    # to reconsider this.
    ######################################################################
    # Media Page Options
    ######################################################################
    # Layout Options
    ("options.media.layout.tabbed", False),
    ("options.media.layout.groups", "citation,note,reference"),
    ("options.media.layout.citation.visible", True),
    ("options.media.layout.citation.stacked", False),
    ("options.media.layout.citation.hideable", False),
    ("options.media.layout.note.visible", True),
    ("options.media.layout.note.stacked", False),
    ("options.media.layout.note.hideable", False),
    ("options.media.layout.reference.visible", True),
    ("options.media.layout.reference.stacked", False),
    ("options.media.layout.reference.hideable", False),
    # Page Options
    ("options.media.page.pinned-header", True),
    ("options.media.page.use-color-scheme", True),
    # Active Media
    ("options.media.active.tag-format", 1),
    ("options.media.active.tag-width", 10),
    # Note
    ("options.media.note.preview-mode", True),
    ("options.media.note.preview-lines", 4),
    ("options.media.note.tag-format", 1),
    ("options.media.note.tag-width", 10),
    # For Reference Group Objects may need a plethora of options, need
    # to reconsider this.    
    ######################################################################
    # Place Page Options
    ######################################################################
    # Layout Options
    ("options.place.layout.tabbed", False),
    ("options.place.layout.groups", "citation,note,media,reference"),
    ("options.place.layout.citation.visible", True),
    ("options.place.layout.citation.stacked", False),
    ("options.place.layout.citation.hideable", False),
    ("options.place.layout.note.visible", True),
    ("options.place.layout.note.stacked", False),
    ("options.place.layout.note.hideable", False),
    ("options.place.layout.media.visible", True),
    ("options.place.layout.media.stacked", False),
    ("options.place.layout.media.hideable", False),
    ("options.place.layout.reference.visible", True),
    ("options.place.layout.reference.stacked", False),
    ("options.place.layout.reference.hideable", False),
    # Page Options
    ("options.place.page.pinned-header", True),
    ("options.place.page.use-color-scheme", True),
    # Active Place
    ("options.place.active.tag-format", 1),
    ("options.place.active.tag-width", 10),
    # Note
    ("options.place.note.preview-mode", True),
    ("options.place.note.preview-lines", 4),
    ("options.place.note.tag-format", 1),
    ("options.place.note.tag-width", 10),
    # Media
    ("options.place.media.tag-format", 1),
    ("options.place.media.tag-width", 10),
    ("options.place.media.image-mode", 2),
    ("options.place.media.sort-by-date", False),
    ("options.place.media.show-date", True),
    ("options.place.media.metadata-attribute-1", "None"),
    ("options.place.media.metadata-attribute-2", "None"),
    ("options.place.media.metadata-attribute-3", "None"),
    ("options.place.media.metadata-attribute-4", "None"),
    # For Reference Group Objects may need a plethora of options, need
    # to reconsider this.    
)
