# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2021       Christopher Horn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Configuration options.
"""

CONFIGSETTINGS = (
    ######################################################################
    # Active State
    ######################################################################
    ("options.active.last_object", "None"),
    #
    ######################################################################
    # Global Options
    #
    ######################################################################
    ## Display Options
    ######################################################################
    ("options.global.display.max-page-windows", 4),
    ("options.global.display.max-group-windows", 4),
    ("options.global.display.pin-header", True),
    ("options.global.display.focal-object-highlight", False),
    ("options.global.display.focal-object-color", ["#bbe68a", "#304918"]),
    (
        "options.global.display.default-background-color",
        ["#eeeeee", "#454545"],
    ),
    ("options.global.display.use-color-scheme", True),
    ("options.global.display.use-smaller-title-font", True),
    ("options.global.display.use-smaller-detail-font", True),
    ("options.global.display.border-width", 2),
    ("options.global.display.icons-active-width", 24),
    ("options.global.display.icons-group-width", 12),
    ######################################################################
    ## General Options
    ######################################################################
    ("options.global.general.image-page-link", True),
    ("options.global.general.link-citation-title-to-source", True),
    ("options.global.general.create-reciprocal-associations", True),
    ("options.global.general.include-child-notes", True),
    ("options.global.general.include-note-urls", True),
    ("options.global.general.enable-warnings", True),
    ######################################################################
    ## Maximum Options
    ######################################################################
    ("options.global.max.events-per-group", 300),
    ("options.global.max.places-per-group", 200),
    ("options.global.max.sources-per-group", 200),
    ("options.global.max.citations-per-group", 200),
    ("options.global.max.media-per-group", 200),
    ("options.global.max.notes-per-group", 200),
    ("options.global.max.references-per-group", 200),
    ######################################################################
    # Basic Indicator Related Options
    ######################################################################
    ("options.global.indicator.gramps-ids", True),
    ("options.global.indicator.privacy", 1),
    ("options.global.indicator.bookmarks", True),
    ("options.global.indicator.home-person", True),
    ("options.global.indicator.tags", True),
    ("options.global.indicator.tags-sort-by-name", False),
    ("options.global.indicator.child-objects", True),
    ("options.global.indicator.child-objects-counts", False),
    ("options.global.indicator.names", True),
    ("options.global.indicator.parents", True),
    ("options.global.indicator.spouses", True),
    ("options.global.indicator.children", True),
    ("options.global.indicator.associations", True),
    ("options.global.indicator.events", True),
    ("options.global.indicator.ordinances", True),
    ("options.global.indicator.media", True),
    ("options.global.indicator.attributes", True),
    ("options.global.indicator.addresses", True),
    ("options.global.indicator.citations", True),
    ("options.global.indicator.notes", True),
    ("options.global.indicator.urls", True),
    ######################################################################
    # Status Indicator Related Options
    ######################################################################
    ("options.global.status.todo", True),
    ("options.global.status.todo-edit", False),
    ("options.global.status.todo-person", False),
    ("options.global.status.todo-family", False),
    ("options.global.status.confidence-ranking", True),
    ("options.global.status.rank-object", True),
    ("options.global.status.rank-names", True),
    ("options.global.status.rank-events", True),
    ("options.global.status.rank-ordinances", True),
    ("options.global.status.rank-attributes", True),
    ("options.global.status.rank-associations", True),
    ("options.global.status.rank-addresses", True),
    ("options.global.status.rank-spouses", True),
    ("options.global.status.rank-children", True),
    ("options.global.status.rank-1", "Event:Baptism"),
    ("options.global.status.rank-2", "Event:Christening"),
    ("options.global.status.rank-3", "Event:Marriage Banns"),
    ("options.global.status.rank-4", "Event:Marriage"),
    ("options.global.status.rank-5", "Event:Divorce"),
    ("options.global.status.rank-6", "Event:Will"),
    ("options.global.status.rank-7", "Event:Burial"),
    ("options.global.status.rank-8", "Event:Cremation"),
    ("options.global.status.rank-9", "Event:Probate"),
    ("options.global.status.rank-10", "None"),
    ("options.global.status.rank-11", "None"),
    ("options.global.status.rank-12", "None"),
    ("options.global.status.citation-alert", True),
    ("options.global.status.citation-alert-edit", True),
    ("options.global.status.citation-alert-minimum", 0),
    ("options.global.status.alert-1", "Event:Birth"),
    ("options.global.status.alert-2", "Event:Baptism"),
    ("options.global.status.alert-3", "Event:Christening"),
    ("options.global.status.alert-4", "Event:Marriage Banns"),
    ("options.global.status.alert-5", "Event:Marriage"),
    ("options.global.status.alert-6", "Event:Divorce"),
    ("options.global.status.alert-7", "Event:Will"),
    ("options.global.status.alert-8", "Event:Death"),
    ("options.global.status.alert-9", "Event:Burial"),
    ("options.global.status.alert-10", "Event:Cremation"),
    ("options.global.status.alert-11", "Event:Probate"),
    ("options.global.status.alert-12", "None"),
    ("options.global.status.missing-alert", True),
    ("options.global.status.missing-1", "Event:Birth"),
    ("options.global.status.missing-2", "Event:Marriage"),
    ("options.global.status.missing-3", "Event:Death"),
    ("options.global.status.missing-4", "Event:Burial"),
    ("options.global.status.missing-5", "None"),
    ("options.global.status.missing-6", "None"),
    ######################################################################
    ## Media Bar Related Options
    ######################################################################
    ("options.global.media-bar.enabled", False),
    ("options.global.media-bar.position", 1),
    ("options.global.media-bar.display-mode", 1),
    ("options.global.media-bar.minimum-required", 1),
    ("options.global.media-bar.sort-by-date", True),
    ("options.global.media-bar.group-by-type", True),
    ("options.global.media-bar.filter-non-photos", False),
    ("options.global.media-bar.page-link", True),
    ######################################################################
    # Frame Level Options
    # These apply when the frame is in the page header and not a group
    #
    ######################################################################
    ## Person Options
    ######################################################################
    ("options.active.person.event-format", 1),
    ("options.active.person.show-age", True),
    ("options.active.person.sex-mode", 1),
    ("options.active.person.image-mode", 3),
    ("options.active.person.lfield-skip-birth-alternates", False),
    ("options.active.person.lfield-skip-death-alternates", False),
    ("options.active.person.lfield-1", "Event:Birth"),
    ("options.active.person.lfield-2", "Event:Baptism"),
    ("options.active.person.lfield-3", "Event:Christening"),
    ("options.active.person.lfield-4", "Event:Death"),
    ("options.active.person.lfield-5", "Event:Burial"),
    ("options.active.person.lfield-6", "Event:Cremation"),
    ("options.active.person.lfield-7", "Event:Probate"),
    ("options.active.person.lfield-8", "Calculated:Duration"),
    ("options.active.person.lfield-9", "None"),
    ("options.active.person.lfield-10", "None"),
    ("options.active.person.mfield-skip-birth-alternates", False),
    ("options.active.person.mfield-skip-death-alternates", False),
    ("options.active.person.mfield-1", "Calculated:Occupations"),
    ("options.active.person.mfield-2", "Calculated:Paternal Progenitors"),
    ("options.active.person.mfield-3", "Calculated:Maternal Progenitors"),
    ("options.active.person.mfield-4", "Calculated:Child Number"),
    ("options.active.person.mfield-5", "None"),
    ("options.active.person.mfield-6", "None"),
    ("options.active.person.mfield-7", "None"),
    ("options.active.person.mfield-8", "None"),
    ("options.active.person.mfield-9", "None"),
    ("options.active.person.mfield-10", "None"),
    ("options.active.person.rfield-show-labels", False),
    ("options.active.person.rfield-1", "None"),
    ("options.active.person.rfield-2", "None"),
    ("options.active.person.rfield-3", "None"),
    ("options.active.person.rfield-4", "None"),
    ("options.active.person.rfield-5", "None"),
    ("options.active.person.rfield-6", "None"),
    ("options.active.person.rfield-7", "None"),
    ("options.active.person.rfield-8", "None"),
    ("options.active.person.rfield-9", "None"),
    ("options.active.person.rfield-10", "None"),
    ######################################################################
    ## Parent Options
    ######################################################################
    ("options.active.parent.event-format", 1),
    ("options.active.parent.show-age", True),
    ("options.active.parent.sex-mode", 1),
    ("options.active.parent.image-mode", 3),
    ("options.active.parent.lfield-skip-birth-alternates", True),
    ("options.active.parent.lfield-skip-death-alternates", True),
    ("options.active.parent.lfield-1", "Event:Birth"),
    ("options.active.parent.lfield-2", "Event:Baptism"),
    ("options.active.parent.lfield-3", "Event:Christening"),
    ("options.active.parent.lfield-4", "Event:Death"),
    ("options.active.parent.lfield-5", "Event:Burial"),
    ("options.active.parent.lfield-6", "Event:Cremation"),
    ("options.active.parent.lfield-7", "Event:Probate"),
    ("options.active.parent.lfield-8", "Calculated:Duration"),
    ("options.active.parent.lfield-9", "None"),
    ("options.active.parent.lfield-10", "None"),
    ("options.active.parent.rfield-show-labels", False),
    ("options.active.parent.rfield-1", "None"),
    ("options.active.parent.rfield-2", "None"),
    ("options.active.parent.rfield-3", "None"),
    ("options.active.parent.rfield-4", "None"),
    ("options.active.parent.rfield-5", "None"),
    ("options.active.parent.rfield-6", "None"),
    ("options.active.parent.rfield-7", "None"),
    ("options.active.parent.rfield-8", "None"),
    ("options.active.parent.rfield-9", "None"),
    ("options.active.parent.rfield-10", "None"),
    ######################################################################
    ## Spouse Options
    ######################################################################
    ("options.active.spouse.event-format", 1),
    ("options.active.spouse.show-age", True),
    ("options.active.spouse.sex-mode", 1),
    ("options.active.spouse.image-mode", 3),
    ("options.active.spouse.lfield-skip-birth-alternates", True),
    ("options.active.spouse.lfield-skip-death-alternates", True),
    ("options.active.spouse.lfield-1", "Event:Birth"),
    ("options.active.spouse.lfield-2", "Event:Baptism"),
    ("options.active.spouse.lfield-3", "Event:Christening"),
    ("options.active.spouse.lfield-4", "Event:Death"),
    ("options.active.spouse.lfield-5", "Event:Burial"),
    ("options.active.spouse.lfield-6", "Event:Cremation"),
    ("options.active.spouse.lfield-7", "Event:Probate"),
    ("options.active.spouse.lfield-8", "Calculated:Duration"),
    ("options.active.spouse.lfield-9", "None"),
    ("options.active.spouse.lfield-10", "None"),
    ("options.active.spouse.rfield-show-labels", False),
    ("options.active.spouse.rfield-1", "None"),
    ("options.active.spouse.rfield-2", "None"),
    ("options.active.spouse.rfield-3", "None"),
    ("options.active.spouse.rfield-4", "None"),
    ("options.active.spouse.rfield-5", "None"),
    ("options.active.spouse.rfield-6", "None"),
    ("options.active.spouse.rfield-7", "None"),
    ("options.active.spouse.rfield-8", "None"),
    ("options.active.spouse.rfield-9", "None"),
    ("options.active.spouse.rfield-10", "None"),
    ######################################################################
    ## Association Options
    ######################################################################
    ("options.active.association.event-format", 1),
    ("options.active.association.show-age", True),
    ("options.active.association.sex-mode", 1),
    ("options.active.association.image-mode", 3),
    ("options.active.association.lfield-skip-birth-alternates", True),
    ("options.active.association.lfield-skip-death-alternates", True),
    ("options.active.association.lfield-1", "Event:Birth"),
    ("options.active.association.lfield-2", "Event:Baptism"),
    ("options.active.association.lfield-3", "Event:Christening"),
    ("options.active.association.lfield-4", "Event:Death"),
    ("options.active.association.lfield-5", "Event:Burial"),
    ("options.active.association.lfield-6", "Event:Cremation"),
    ("options.active.association.lfield-7", "Event:Probate"),
    ("options.active.association.lfield-8", "Calculated:Duration"),
    ("options.active.association.lfield-9", "None"),
    ("options.active.association.lfield-10", "None"),
    ("options.active.association.rfield-show-labels", False),
    ("options.active.association.rfield-1", "None"),
    ("options.active.association.rfield-2", "None"),
    ("options.active.association.rfield-3", "None"),
    ("options.active.association.rfield-4", "None"),
    ("options.active.association.rfield-5", "None"),
    ("options.active.association.rfield-6", "None"),
    ("options.active.association.rfield-7", "None"),
    ("options.active.association.rfield-8", "None"),
    ("options.active.association.rfield-9", "None"),
    ("options.active.association.rfield-10", "None"),
    ######################################################################
    ## Family Options
    ######################################################################
    ("options.active.family.event-format", 1),
    ("options.active.family.image-mode", 3),
    ("options.active.family.compact-mode", False),
    ("options.active.family.show-parents", True),
    ("options.active.family.compact-mode-parents", True),
    ("options.active.family.lfield-skip-marriage-alternates", False),
    ("options.active.family.lfield-skip-divorce-alternates", False),
    ("options.active.family.lfield-1", "Event:Marriage Banns"),
    ("options.active.family.lfield-2", "Event:Marriage License"),
    ("options.active.family.lfield-3", "Event:Marriage Contract"),
    ("options.active.family.lfield-4", "Event:Marriage Settlement"),
    ("options.active.family.lfield-5", "Event:Marriage"),
    ("options.active.family.lfield-6", "Event:Divorce Filing"),
    ("options.active.family.lfield-7", "Event:Divorce"),
    ("options.active.family.lfield-8", "Event:Annulment"),
    ("options.active.family.lfield-9", "Calculated:Duration"),
    ("options.active.family.lfield-10", "None"),
    ("options.active.family.mfield-skip-marriage-alternates", False),
    ("options.active.family.mfield-skip-divorce-alternates", False),
    ("options.active.family.mfield-1", "Calculated:Bride Age"),
    ("options.active.family.mfield-2", "Calculated:Groom Age"),
    ("options.active.family.mfield-3", "Calculated:Relationship"),
    ("options.active.family.mfield-4", "None"),
    ("options.active.family.mfield-5", "None"),
    ("options.active.family.mfield-6", "None"),
    ("options.active.family.mfield-7", "None"),
    ("options.active.family.mfield-8", "None"),
    ("options.active.family.mfield-9", "None"),
    ("options.active.family.mfield-10", "None"),
    ("options.active.family.rfield-show-labels", False),
    ("options.active.family.rfield-1", "None"),
    ("options.active.family.rfield-2", "None"),
    ("options.active.family.rfield-3", "None"),
    ("options.active.family.rfield-4", "None"),
    ("options.active.family.rfield-5", "None"),
    ("options.active.family.rfield-6", "None"),
    ("options.active.family.rfield-7", "None"),
    ("options.active.family.rfield-8", "None"),
    ("options.active.family.rfield-9", "None"),
    ("options.active.family.rfield-10", "None"),
    ######################################################################
    ## Event Options
    ######################################################################
    ("options.active.event.event-format", 1),
    ("options.active.event.image-mode", 3),
    ("options.active.event.color-scheme", 1),
    ("options.active.event.rfield-show-labels", False),
    ("options.active.event.rfield-1", "None"),
    ("options.active.event.rfield-2", "None"),
    ("options.active.event.rfield-3", "None"),
    ("options.active.event.rfield-4", "None"),
    ("options.active.event.rfield-5", "None"),
    ("options.active.event.show-description", True),
    ("options.active.event.show-participants", True),
    ("options.active.event.show-role-always", False),
    ("options.active.event.show-source-count", True),
    ("options.active.event.show-citation-count", True),
    ("options.active.event.show-best-confidence", True),
    ######################################################################
    ## Place Options
    ######################################################################
    ("options.active.place.image-mode", 3),
    ######################################################################
    ## Citation Options
    ######################################################################
    ("options.active.citation.image-mode", 3),
    ("options.active.citation.sort-by-date", False),
    ("options.active.citation.include-indirect", True),
    ("options.active.citation.include-parent-family", True),
    ("options.active.citation.include-family", True),
    ("options.active.citation.include-family-indirect", True),
    ("options.active.citation.show-age", True),
    ("options.active.citation.show-date", True),
    ("options.active.citation.show-publisher", True),
    ("options.active.citation.show-reference-type", True),
    ("options.active.citation.show-reference-description", True),
    ("options.active.citation.show-confidence", True),
    ("options.active.citation.rfield-show-labels", False),
    ("options.active.citation.rfield-1", "None"),
    ("options.active.citation.rfield-2", "None"),
    ("options.active.citation.rfield-3", "None"),
    ("options.active.citation.rfield-4", "None"),
    ("options.active.citation.rfield-5", "None"),
    ######################################################################
    ## Source Options
    ######################################################################
    ("options.active.source.event-format", 1),
    ("options.active.source.image-mode", 3),
    ("options.active.source.rfield-show-labels", False),
    ("options.active.source.rfield-1", "None"),
    ("options.active.source.rfield-2", "None"),
    ("options.active.source.rfield-3", "None"),
    ("options.active.source.rfield-4", "None"),
    ("options.active.source.rfield-5", "None"),
    ######################################################################
    ## Repository Options
    ######################################################################
    ("options.active.repository.show-call-number", True),
    ("options.active.repository.show-media-type", True),
    ("options.active.repository.show-repository-type", True),
    ######################################################################
    ## Media Options
    ######################################################################
    ("options.active.media.image-mode", 3),
    ("options.active.media.show-date", True),
    ("options.active.media.show-path", True),
    ("options.active.media.show-mime-type", True),
    ("options.active.media.rfield-show-labels", False),
    ("options.active.media.rfield-1", "None"),
    ("options.active.media.rfield-2", "None"),
    ("options.active.media.rfield-3", "None"),
    ("options.active.media.rfield-4", "None"),
    ("options.active.media.rfield-5", "None"),
    ######################################################################
    ## Note Options
    ######################################################################
    ("options.active.note.text-on-top", False),
    ("options.active.note.preview-mode", False),
    ("options.active.note.preview-lines", 3),
    ######################################################################
    # Group Level Options
    # These apply when the frame is in a group and not the page header
    #
    ######################################################################
    ## Person Options
    ######################################################################
    ("options.group.person.event-format", 1),
    ("options.group.person.show-age", True),
    ("options.group.person.sex-mode", 1),
    ("options.group.person.image-mode", 1),
    ("options.group.person.lfield-skip-birth-alternates", False),
    ("options.group.person.lfield-skip-death-alternates", False),
    ("options.group.person.lfield-1", "Event:Birth"),
    ("options.group.person.lfield-2", "Event:Baptism"),
    ("options.group.person.lfield-3", "Event:Christening"),
    ("options.group.person.lfield-4", "Event:Death"),
    ("options.group.person.lfield-5", "Event:Burial"),
    ("options.group.person.lfield-6", "Event:Cremation"),
    ("options.group.person.lfield-7", "Event:Probate"),
    ("options.group.person.lfield-8", "Calculated:Duration"),
    ("options.group.person.lfield-9", "None"),
    ("options.group.person.lfield-10", "None"),
    ("options.group.person.mfield-skip-birth-alternates", False),
    ("options.group.person.mfield-skip-death-alternates", False),
    ("options.group.person.mfield-1", "None"),
    ("options.group.person.mfield-2", "None"),
    ("options.group.person.mfield-3", "None"),
    ("options.group.person.mfield-4", "None"),
    ("options.group.person.mfield-5", "None"),
    ("options.group.person.mfield-6", "None"),
    ("options.group.person.mfield-7", "None"),
    ("options.group.person.mfield-8", "None"),
    ("options.group.person.mfield-9", "None"),
    ("options.group.person.mfield-10", "None"),
    ("options.group.person.rfield-show-labels", False),
    ("options.group.person.rfield-1", "None"),
    ("options.group.person.rfield-2", "None"),
    ("options.group.person.rfield-3", "None"),
    ("options.group.person.rfield-4", "None"),
    ("options.group.person.rfield-5", "None"),
    ("options.group.person.rfield-6", "None"),
    ("options.group.person.rfield-7", "None"),
    ("options.group.person.rfield-8", "None"),
    ("options.group.person.rfield-9", "None"),
    ("options.group.person.rfield-10", "None"),
    ######################################################################
    ## Parent Options
    ######################################################################
    ("options.group.parent.event-format", 1),
    ("options.group.parent.show-age", True),
    ("options.group.parent.sex-mode", 1),
    ("options.group.parent.image-mode", 1),
    ("options.group.parent.lfield-skip-birth-alternates", True),
    ("options.group.parent.lfield-skip-death-alternates", True),
    ("options.group.parent.lfield-1", "Event:Birth"),
    ("options.group.parent.lfield-2", "Event:Baptism"),
    ("options.group.parent.lfield-3", "Event:Christening"),
    ("options.group.parent.lfield-4", "Event:Death"),
    ("options.group.parent.lfield-5", "Event:Burial"),
    ("options.group.parent.lfield-6", "Event:Cremation"),
    ("options.group.parent.lfield-7", "Event:Probate"),
    ("options.group.parent.lfield-8", "Calculated:Duration"),
    ("options.group.parent.lfield-9", "None"),
    ("options.group.parent.lfield-10", "None"),
    ("options.group.parent.rfield-show-labels", False),
    ("options.group.parent.rfield-1", "None"),
    ("options.group.parent.rfield-2", "None"),
    ("options.group.parent.rfield-3", "None"),
    ("options.group.parent.rfield-4", "None"),
    ("options.group.parent.rfield-5", "None"),
    ("options.group.parent.rfield-6", "None"),
    ("options.group.parent.rfield-7", "None"),
    ("options.group.parent.rfield-8", "None"),
    ("options.group.parent.rfield-9", "None"),
    ("options.group.parent.rfield-10", "None"),
    ######################################################################
    ## Sibling Options
    ######################################################################
    ("options.group.sibling.event-format", 1),
    ("options.group.sibling.show-age", True),
    ("options.group.sibling.sex-mode", 1),
    ("options.group.sibling.image-mode", 1),
    ("options.group.sibling.number-children", True),
    ("options.group.sibling.reference-mode", 1),
    ("options.group.sibling.lfield-skip-birth-alternates", True),
    ("options.group.sibling.lfield-skip-death-alternates", True),
    ("options.group.sibling.lfield-1", "Event:Birth"),
    ("options.group.sibling.lfield-2", "Event:Baptism"),
    ("options.group.sibling.lfield-3", "Event:Christening"),
    ("options.group.sibling.lfield-4", "Event:Death"),
    ("options.group.sibling.lfield-5", "Event:Burial"),
    ("options.group.sibling.lfield-6", "Event:Cremation"),
    ("options.group.sibling.lfield-7", "Event:Probate"),
    ("options.group.sibling.lfield-8", "Calculated:Duration"),
    ("options.group.sibling.lfield-9", "None"),
    ("options.group.sibling.lfield-10", "None"),
    ("options.group.sibling.rfield-show-labels", False),
    ("options.group.sibling.rfield-1", "None"),
    ("options.group.sibling.rfield-2", "None"),
    ("options.group.sibling.rfield-3", "None"),
    ("options.group.sibling.rfield-4", "None"),
    ("options.group.sibling.rfield-5", "None"),
    ("options.group.sibling.rfield-6", "None"),
    ("options.group.sibling.rfield-7", "None"),
    ("options.group.sibling.rfield-8", "None"),
    ("options.group.sibling.rfield-9", "None"),
    ("options.group.sibling.rfield-10", "None"),
    ######################################################################
    ## Spouse Options
    ######################################################################
    ("options.group.spouse.event-format", 1),
    ("options.group.spouse.show-age", True),
    ("options.group.spouse.sex-mode", 1),
    ("options.group.spouse.image-mode", 1),
    ("options.group.spouse.lfield-skip-birth-alternates", True),
    ("options.group.spouse.lfield-skip-death-alternates", True),
    ("options.group.spouse.lfield-1", "Event:Birth"),
    ("options.group.spouse.lfield-2", "Event:Baptism"),
    ("options.group.spouse.lfield-3", "Event:Christening"),
    ("options.group.spouse.lfield-4", "Event:Death"),
    ("options.group.spouse.lfield-5", "Event:Burial"),
    ("options.group.spouse.lfield-6", "Event:Cremation"),
    ("options.group.spouse.lfield-7", "Event:Probate"),
    ("options.group.spouse.lfield-8", "Calculated:Duration"),
    ("options.group.spouse.lfield-9", "None"),
    ("options.group.spouse.lfield-10", "None"),
    ("options.group.spouse.rfield-show-labels", False),
    ("options.group.spouse.rfield-1", "None"),
    ("options.group.spouse.rfield-2", "None"),
    ("options.group.spouse.rfield-3", "None"),
    ("options.group.spouse.rfield-4", "None"),
    ("options.group.spouse.rfield-5", "None"),
    ("options.group.spouse.rfield-6", "None"),
    ("options.group.spouse.rfield-7", "None"),
    ("options.group.spouse.rfield-8", "None"),
    ("options.group.spouse.rfield-9", "None"),
    ("options.group.spouse.rfield-10", "None"),
    ######################################################################
    ## Child Options
    ######################################################################
    ("options.group.child.event-format", 1),
    ("options.group.child.show-age", True),
    ("options.group.child.sex-mode", 1),
    ("options.group.child.image-mode", 1),
    ("options.group.child.number-children", True),
    ("options.group.child.reference-mode", 1),
    ("options.group.child.lfield-skip-birth-alternates", True),
    ("options.group.child.lfield-skip-death-alternates", True),
    ("options.group.child.lfield-1", "Event:Birth"),
    ("options.group.child.lfield-2", "Event:Baptism"),
    ("options.group.child.lfield-3", "Event:Christening"),
    ("options.group.child.lfield-4", "Event:Death"),
    ("options.group.child.lfield-5", "Event:Burial"),
    ("options.group.child.lfield-6", "Event:Cremation"),
    ("options.group.child.lfield-7", "Event:Probate"),
    ("options.group.child.lfield-8", "Calculated:Duration"),
    ("options.group.child.lfield-9", "None"),
    ("options.group.child.lfield-10", "None"),
    ("options.group.child.rfield-show-labels", False),
    ("options.group.child.rfield-1", "None"),
    ("options.group.child.rfield-2", "None"),
    ("options.group.child.rfield-3", "None"),
    ("options.group.child.rfield-4", "None"),
    ("options.group.child.rfield-5", "None"),
    ("options.group.child.rfield-6", "None"),
    ("options.group.child.rfield-7", "None"),
    ("options.group.child.rfield-8", "None"),
    ("options.group.child.rfield-9", "None"),
    ("options.group.child.rfield-10", "None"),
    ######################################################################
    ## Association Options
    ######################################################################
    ("options.group.association.event-format", 1),
    ("options.group.association.show-age", True),
    ("options.group.association.sex-mode", 1),
    ("options.group.association.image-mode", 1),
    ("options.group.association.reference-mode", 1),
    ("options.group.association.lfield-skip-birth-alternates", True),
    ("options.group.association.lfield-skip-death-alternates", True),
    ("options.group.association.lfield-1", "Event:Birth"),
    ("options.group.association.lfield-2", "Event:Baptism"),
    ("options.group.association.lfield-3", "Event:Christening"),
    ("options.group.association.lfield-4", "Event:Death"),
    ("options.group.association.lfield-5", "Event:Burial"),
    ("options.group.association.lfield-6", "Event:Cremation"),
    ("options.group.association.lfield-7", "Event:Probate"),
    ("options.group.association.lfield-8", "Calculated:Duration"),
    ("options.group.association.lfield-9", "None"),
    ("options.group.association.lfield-10", "None"),
    ("options.group.association.rfield-show-labels", False),
    ("options.group.association.rfield-1", "None"),
    ("options.group.association.rfield-2", "None"),
    ("options.group.association.rfield-3", "None"),
    ("options.group.association.rfield-4", "None"),
    ("options.group.association.rfield-5", "None"),
    ("options.group.association.rfield-6", "None"),
    ("options.group.association.rfield-7", "None"),
    ("options.group.association.rfield-8", "None"),
    ("options.group.association.rfield-9", "None"),
    ("options.group.association.rfield-10", "None"),
    ######################################################################
    ## Name Options
    ######################################################################
    ("options.group.name.show-age", False),
    ######################################################################
    ## Address Options
    ######################################################################
    ("options.group.address.show-age", False),
    ######################################################################
    ## Family Options
    ######################################################################
    ("options.group.family.event-format", 1),
    ("options.group.family.image-mode", 1),
    ("options.group.family.compact-mode", True),
    ("options.group.family.lfield-skip-marriage-alternates", False),
    ("options.group.family.lfield-skip-divorce-alternates", False),
    ("options.group.family.lfield-1", "Calculated:Relationship"),
    ("options.group.family.lfield-2", "Event:Marriage Banns"),
    ("options.group.family.lfield-3", "Event:Marriage License"),
    ("options.group.family.lfield-4", "Event:Marriage Contract"),
    ("options.group.family.lfield-5", "Event:Marriage Settlement"),
    ("options.group.family.lfield-6", "Event:Marriage"),
    ("options.group.family.lfield-7", "Event:Divorce Filing"),
    ("options.group.family.lfield-8", "Event:Divorce"),
    ("options.group.family.lfield-9", "Event:Annulment"),
    ("options.group.family.lfield-10", "Calculated:Duration"),
    ("options.group.family.rfield-show-labels", False),
    ("options.group.family.rfield-1", "None"),
    ("options.group.family.rfield-2", "None"),
    ("options.group.family.rfield-3", "None"),
    ("options.group.family.rfield-4", "None"),
    ("options.group.family.rfield-5", "None"),
    ("options.group.family.rfield-6", "None"),
    ("options.group.family.rfield-7", "None"),
    ("options.group.family.rfield-8", "None"),
    ("options.group.family.rfield-9", "None"),
    ("options.group.family.rfield-10", "None"),
    ######################################################################
    ## Event Options
    ######################################################################
    ("options.group.event.event-format", 1),
    ("options.group.event.show-age", False),
    ("options.group.event.image-mode", 0),
    ("options.group.event.reference-mode", 1),
    ("options.group.event.color-scheme", 1),
    ("options.group.event.rfield-show-labels", False),
    ("options.group.event.rfield-1", "None"),
    ("options.group.event.rfield-2", "None"),
    ("options.group.event.rfield-3", "None"),
    ("options.group.event.rfield-4", "None"),
    ("options.group.event.rfield-5", "None"),
    ("options.group.event.show-description", True),
    ("options.group.event.show-participants", True),
    ("options.group.event.show-role-always", False),
    ("options.group.event.show-source-count", True),
    ("options.group.event.show-citation-count", True),
    ("options.group.event.show-best-confidence", True),
    ######################################################################
    ## Ordinance Options
    ######################################################################
    ("options.group.ldsord.show-age", False),
    ######################################################################
    ## Place Options
    ######################################################################
    ("options.group.place.image-mode", 0),
    ("options.group.place.reference-mode", 1),
    ("options.group.place.show-all-enclosed-places", False),
    ######################################################################
    ## Citation Options
    ######################################################################
    ("options.group.citation.image-mode", 0),
    ("options.group.citation.show-age", False),
    ("options.group.citation.sort-by-date", False),
    ("options.group.citation.include-indirect", True),
    ("options.group.citation.include-parent-family", True),
    ("options.group.citation.include-family", True),
    ("options.group.citation.include-family-indirect", True),
    ("options.group.citation.show-date", True),
    ("options.group.citation.show-publisher", True),
    ("options.group.citation.show-reference-type", True),
    ("options.group.citation.show-reference-description", True),
    ("options.group.citation.show-confidence", True),
    ("options.group.citation.rfield-show-labels", False),
    ("options.group.citation.rfield-1", "None"),
    ("options.group.citation.rfield-2", "None"),
    ("options.group.citation.rfield-3", "None"),
    ("options.group.citation.rfield-4", "None"),
    ("options.group.citation.rfield-5", "None"),
    ######################################################################
    ## Source Options
    ######################################################################
    ("options.group.source.event-format", 1),
    ("options.group.source.image-mode", 0),
    ("options.group.source.rfield-show-labels", False),
    ("options.group.source.rfield-1", "None"),
    ("options.group.source.rfield-2", "None"),
    ("options.group.source.rfield-3", "None"),
    ("options.group.source.rfield-4", "None"),
    ("options.group.source.rfield-5", "None"),
    ######################################################################
    ## Repository Options
    ######################################################################
    ("options.group.repository.reference-mode", 1),
    ("options.group.repository.show-call-number", True),
    ("options.group.repository.show-media-type", True),
    ("options.group.repository.show-repository-type", True),
    ######################################################################
    ## Media Options
    ######################################################################
    ("options.group.media.show-age", False),
    ("options.group.media.sort-by-date", False),
    ("options.group.media.group-by-type", False),
    ("options.group.media.filter-non-photos", False),
    ("options.group.media.image-mode", 2),
    ("options.group.media.reference-mode", 1),
    ("options.group.media.show-date", True),
    ("options.group.media.show-path", True),
    ("options.group.media.show-mime-type", True),
    ("options.group.media.rfield-show-labels", False),
    ("options.group.media.rfield-1", "None"),
    ("options.group.media.rfield-2", "None"),
    ("options.group.media.rfield-3", "None"),
    ("options.group.media.rfield-4", "None"),
    ("options.group.media.rfield-5", "None"),
    ######################################################################
    ## Note Options
    ######################################################################
    ("options.group.note.text-on-top", False),
    ("options.group.note.preview-mode", True),
    ("options.group.note.preview-lines", 3),
    ("options.group.note.include-child-objects", True),
    ######################################################################
    # Timeline Options
    #
    ######################################################################
    ## Person Timeline
    ######################################################################
    ("options.timeline.person.image-mode", 0),
    ("options.timeline.person.reference-mode", 1),
    ("options.timeline.person.color-scheme", 1),
    ("options.timeline.person.include-media", False),
    ("options.timeline.person.include-names", False),
    ("options.timeline.person.include-addresses", False),
    ("options.timeline.person.include-ldsords", False),
    ("options.timeline.person.include-citations", False),
    ("options.timeline.person.show-description", True),
    ("options.timeline.person.show-participants", True),
    ("options.timeline.person.show-role-always", False),
    ("options.timeline.person.show-source-count", True),
    ("options.timeline.person.show-citation-count", True),
    ("options.timeline.person.show-best-confidence", True),
    ("options.timeline.person.show-age", True),
    ("options.timeline.person.rfield-show-labels", False),
    ("options.timeline.person.rfield-1", "None"),
    ("options.timeline.person.rfield-2", "None"),
    ("options.timeline.person.rfield-3", "None"),
    ("options.timeline.person.rfield-4", "None"),
    ("options.timeline.person.rfield-5", "None"),
    ("options.timeline.person.show-class-vital", True),
    ("options.timeline.person.show-class-family", True),
    ("options.timeline.person.show-class-religious", True),
    ("options.timeline.person.show-class-vocational", True),
    ("options.timeline.person.show-class-academic", True),
    ("options.timeline.person.show-class-travel", True),
    ("options.timeline.person.show-class-legal", True),
    ("options.timeline.person.show-class-residence", True),
    ("options.timeline.person.show-class-other", True),
    ("options.timeline.person.show-class-custom", True),
    ("options.timeline.person.generations-ancestors", 1),
    ("options.timeline.person.generations-offspring", 1),
    ("options.timeline.person.show-family-father", True),
    ("options.timeline.person.show-family-mother", True),
    ("options.timeline.person.show-family-brother", True),
    ("options.timeline.person.show-family-sister", True),
    ("options.timeline.person.show-family-wife", True),
    ("options.timeline.person.show-family-husband", True),
    ("options.timeline.person.show-family-son", True),
    ("options.timeline.person.show-family-daughter", True),
    ("options.timeline.person.show-family-class-vital", False),
    ("options.timeline.person.show-family-class-family", False),
    ("options.timeline.person.show-family-class-religious", False),
    ("options.timeline.person.show-family-class-vocational", False),
    ("options.timeline.person.show-family-class-academic", False),
    ("options.timeline.person.show-family-class-travel", False),
    ("options.timeline.person.show-family-class-legal", False),
    ("options.timeline.person.show-family-class-residence", False),
    ("options.timeline.person.show-family-class-other", False),
    ("options.timeline.person.show-family-class-custom", False),
    ######################################################################
    ## Family Timeline
    ######################################################################
    ("options.timeline.family.image-mode", 0),
    ("options.timeline.family.reference-mode", 1),
    ("options.timeline.family.color-scheme", 1),
    ("options.timeline.family.include-media", False),
    ("options.timeline.family.include-ldsords", False),
    ("options.timeline.family.include-citations", False),
    ("options.timeline.family.show-description", True),
    ("options.timeline.family.show-participants", True),
    ("options.timeline.family.show-role-always", False),
    ("options.timeline.family.show-source-count", True),
    ("options.timeline.family.show-citation-count", True),
    ("options.timeline.family.show-best-confidence", True),
    ("options.timeline.family.show-age", True),
    ("options.timeline.family.rfield-show-labels", False),
    ("options.timeline.family.rfield-1", "None"),
    ("options.timeline.family.rfield-2", "None"),
    ("options.timeline.family.rfield-3", "None"),
    ("options.timeline.family.rfield-4", "None"),
    ("options.timeline.family.rfield-5", "None"),
    ("options.timeline.family.show-class-vital", True),
    ("options.timeline.family.show-class-family", True),
    ("options.timeline.family.show-class-religious", True),
    ("options.timeline.family.show-class-vocational", True),
    ("options.timeline.family.show-class-academic", True),
    ("options.timeline.family.show-class-travel", True),
    ("options.timeline.family.show-class-legal", True),
    ("options.timeline.family.show-class-residence", True),
    ("options.timeline.family.show-class-other", True),
    ("options.timeline.family.show-class-custom", True),
    ######################################################################
    ## Place Timeline
    ######################################################################
    ("options.timeline.place.image-mode", 0),
    ("options.timeline.place.reference-mode", 3),
    ("options.timeline.place.color-scheme", 0),
    ("options.timeline.place.include-media", True),
    ("options.timeline.place.include-citations", True),
    ("options.timeline.place.show-description", True),
    ("options.timeline.place.show-participants", True),
    ("options.timeline.place.show-role-always", False),
    ("options.timeline.place.show-source-count", True),
    ("options.timeline.place.show-citation-count", True),
    ("options.timeline.place.show-best-confidence", True),
    ("options.timeline.place.show-age", True),
    ("options.timeline.place.rfield-show-labels", False),
    ("options.timeline.place.rfield-1", "None"),
    ("options.timeline.place.rfield-2", "None"),
    ("options.timeline.place.rfield-3", "None"),
    ("options.timeline.place.rfield-4", "None"),
    ("options.timeline.place.rfield-5", "None"),
    ("options.timeline.place.show-class-vital", True),
    ("options.timeline.place.show-class-family", True),
    ("options.timeline.place.show-class-religious", True),
    ("options.timeline.place.show-class-vocational", True),
    ("options.timeline.place.show-class-academic", True),
    ("options.timeline.place.show-class-travel", True),
    ("options.timeline.place.show-class-legal", True),
    ("options.timeline.place.show-class-residence", True),
    ("options.timeline.place.show-class-other", True),
    ("options.timeline.place.show-class-custom", True),
    ######################################################################
    # Additional Color Schemes
    #
    ######################################################################
    ## Confidence Color Scheme
    ######################################################################
    ("options.colors.confidence.very-high", ["#bbe68a", "#304918"]),
    ("options.colors.confidence.high", ["#b8cee6", "#1f344a"]),
    ("options.colors.confidence.normal", ["#f3dbb6", "#75507b"]),
    ("options.colors.confidence.low", ["#feccf0", "#62242d"]),
    ("options.colors.confidence.very-low", ["#ffdede", "#5c3636"]),
    ("options.colors.confidence.border-very-high", ["#304918", "#bbe68a"]),
    ("options.colors.confidence.border-high", ["#1f4986", "#171d26"]),
    ("options.colors.confidence.border-normal", ["#8e5801", "#8e5801"]),
    ("options.colors.confidence.border-low", ["#861f69", "#261111"]),
    ("options.colors.confidence.border-very-low", ["#ff7373", "#720b0b"]),
    ######################################################################
    ## Relationship Color Scheme
    ######################################################################
    ("options.colors.relations.active", ["#bbe68e", "#304918"]),
    ("options.colors.relations.spouse", ["#bbe68e", "#304918"]),
    ("options.colors.relations.father", ["#feccf0", "#62242d"]),
    ("options.colors.relations.mother", ["#feccf0", "#62242d"]),
    ("options.colors.relations.brother", ["#f3dbb6", "#75507b"]),
    ("options.colors.relations.sister", ["#f3dbb6", "#75507b"]),
    ("options.colors.relations.son", ["#b8cee6", "#1f344a"]),
    ("options.colors.relations.daughter", ["#b8cee6", "#1f344a"]),
    ("options.colors.relations.none", ["#ffdede", "#5c3636"]),
    ("options.colors.relations.border-active", ["#304918", "#bbe68a"]),
    ("options.colors.relations.border-spouse", ["#304918", "#bbe68a"]),
    ("options.colors.relations.border-father", ["#861f69", "#261111"]),
    ("options.colors.relations.border-mother", ["#861f69", "#261111"]),
    ("options.colors.relations.border-brother", ["#8e5801", "#8e5801"]),
    ("options.colors.relations.border-sister", ["#8e5801", "#8e5801"]),
    ("options.colors.relations.border-son", ["#1f4986", "#171d26"]),
    ("options.colors.relations.border-daughter", ["#1f4986", "#171d26"]),
    ("options.colors.relations.border-none", ["#ff7373", "#720b0b"]),
    ######################################################################
    ## Event Category Color Scheme
    ######################################################################
    ("options.colors.events.vital", ["#bbe68e", "#304918"]),
    ("options.colors.events.family", ["#b8cee6", "#1f344a"]),
    ("options.colors.events.religious", ["#bbe68e", "#304918"]),
    ("options.colors.events.vocational", ["#feccf0", "#62242d"]),
    ("options.colors.events.academic", ["#feccf0", "#62242d"]),
    ("options.colors.events.travel", ["#f3dbb6", "#75507b"]),
    ("options.colors.events.legal", ["#f3dbb6", "#75507b"]),
    ("options.colors.events.residence", ["#f3dbb6", "#75507b"]),
    ("options.colors.events.other", ["#ffdede", "#5c3636"]),
    ("options.colors.events.custom", ["#eeeeee", "#454545"]),
    ("options.colors.events.border-vital", ["#304918", "#bbe68a"]),
    ("options.colors.events.border-family", ["#1f4986", "#171d26"]),
    ("options.colors.events.border-religious", ["#304918", "#bbe68a"]),
    ("options.colors.events.border-vocational", ["#861f69", "#261111"]),
    ("options.colors.events.border-academic", ["#861f69", "#261111"]),
    ("options.colors.events.border-travel", ["#8e5801", "#8e5801"]),
    ("options.colors.events.border-legal", ["#8e5801", "#8e5801"]),
    ("options.colors.events.border-residence", ["#8e5801", "#8e5801"]),
    ("options.colors.events.border-other", ["#ff7373", "#720b0b"]),
    ("options.colors.events.border-custom", ["#cccccc", "#252525"]),
    ######################################################################
    ## Event Role Color Scheme
    ######################################################################
    ("options.colors.roles.primary", ["#bbe68e", "#304918"]),
    ("options.colors.roles.secondary", ["#f3dbb6", "#75507b"]),
    ("options.colors.roles.family", ["#b8cee6", "#1f344a"]),
    ("options.colors.roles.implicit", ["#eeeeee", "#454545"]),
    ("options.colors.roles.unknown", ["#ffdede", "#5c3636"]),
    ("options.colors.roles.border-primary", ["#304918", "#bbe68a"]),
    ("options.colors.roles.border-secondary", ["#8e5801", "#8e5801"]),
    ("options.colors.roles.border-family", ["#1f4986", "#171d26"]),
    ("options.colors.roles.border-implicit", ["#cccccc", "#252525"]),
    ("options.colors.roles.border-unknown", ["#ff7373", "#720b0b"]),
    ######################################################################
    # Page Layout Options
    #
    ######################################################################
    ## Name Page Options
    ######################################################################
    ("options.page.name.layout.tabbed", False),
    ("options.page.name.layout.scrolled", False),
    ("options.page.name.layout.groups", "citation,note,url"),
    ("options.page.name.layout.citation.visible", True),
    ("options.page.name.layout.citation.append", False),
    ("options.page.name.layout.note.visible", True),
    ("options.page.name.layout.note.append", False),
    ("options.page.name.layout.url.visible", True),
    ("options.page.name.layout.url.append", False),
    ######################################################################
    ## Attribute Page Options
    ######################################################################
    ("options.page.attribute.layout.tabbed", False),
    ("options.page.attribute.layout.scrolled", False),
    ("options.page.attribute.layout.groups", "citation,note,url"),
    ("options.page.attribute.layout.citation.visible", True),
    ("options.page.attribute.layout.citation.append", False),
    ("options.page.attribute.layout.note.visible", True),
    ("options.page.attribute.layout.note.append", False),
    ("options.page.attribute.layout.url.visible", True),
    ("options.page.attribute.layout.url.append", False),
    ######################################################################
    ## Address Page Options
    ######################################################################
    ("options.page.address.layout.tabbed", False),
    ("options.page.address.layout.scrolled", False),
    ("options.page.address.layout.groups", "citation,note,url"),
    ("options.page.address.layout.citation.visible", True),
    ("options.page.address.layout.citation.append", False),
    ("options.page.address.layout.note.visible", True),
    ("options.page.address.layout.note.append", False),
    ("options.page.address.layout.url.visible", True),
    ("options.page.address.layout.url.append", False),
    ######################################################################
    ## ChildRef Page Options
    ######################################################################
    ("options.page.childref.layout.tabbed", False),
    ("options.page.childref.layout.scrolled", False),
    ("options.page.childref.layout.groups", "citation,note,url"),
    ("options.page.childref.layout.citation.visible", True),
    ("options.page.childref.layout.citation.append", False),
    ("options.page.childref.layout.note.visible", True),
    ("options.page.childref.layout.note.append", False),
    ("options.page.childref.layout.url.visible", True),
    ("options.page.childref.layout.url.append", False),
    ######################################################################
    ## PersonRef Page Options
    ######################################################################
    ("options.page.personref.layout.tabbed", False),
    ("options.page.personref.layout.scrolled", False),
    ("options.page.personref.layout.groups", "citation,note,url"),
    ("options.page.personref.layout.citation.visible", True),
    ("options.page.personref.layout.citation.append", False),
    ("options.page.personref.layout.note.visible", True),
    ("options.page.personref.layout.note.append", False),
    ("options.page.personref.layout.url.visible", True),
    ("options.page.personref.layout.url.append", False),
    ######################################################################
    ## Person Page Options
    ######################################################################
    ("options.page.person.layout.tabbed", False),
    ("options.page.person.layout.scrolled", False),
    (
        "options.page.person.layout.groups",
        "parent,event,timeline,ldsord,spouse,name,attribute,association,"
        "citation,address,url,note,media,reference",
    ),
    ("options.page.person.layout.parent.visible", True),
    ("options.page.person.layout.parent.append", False),
    ("options.page.person.layout.event.visible", False),
    ("options.page.person.layout.event.append", False),
    ("options.page.person.layout.timeline.visible", True),
    ("options.page.person.layout.timeline.append", False),
    ("options.page.person.layout.ldsord.visible", False),
    ("options.page.person.layout.ldsord.append", False),
    ("options.page.person.layout.spouse.visible", True),
    ("options.page.person.layout.spouse.append", False),
    ("options.page.person.layout.name.visible", False),
    ("options.page.person.layout.name.append", False),
    ("options.page.person.layout.attribute.visible", False),
    ("options.page.person.layout.attribute.append", False),
    ("options.page.person.layout.association.visible", False),
    ("options.page.person.layout.association.append", False),
    ("options.page.person.layout.citation.visible", True),
    ("options.page.person.layout.citation.append", False),
    ("options.page.person.layout.address.visible", False),
    ("options.page.person.layout.address.append", False),
    ("options.page.person.layout.url.visible", False),
    ("options.page.person.layout.url.append", False),
    ("options.page.person.layout.note.visible", False),
    ("options.page.person.layout.note.append", False),
    ("options.page.person.layout.media.visible", False),
    ("options.page.person.layout.media.append", False),
    ("options.page.person.layout.reference.visible", False),
    ("options.page.person.layout.reference.append", False),
    ######################################################################
    ## Family Page Options
    ######################################################################
    ("options.page.family.layout.tabbed", False),
    ("options.page.family.layout.scrolled", False),
    (
        "options.page.family.layout.groups",
        "child,event,timeline,ldsord,attribute,citation,url,note,media,"
        "reference",
    ),
    ("options.page.family.layout.child.visible", True),
    ("options.page.family.layout.child.append", False),
    ("options.page.family.layout.event.visible", True),
    ("options.page.family.layout.event.append", False),
    ("options.page.family.layout.timeline.visible", True),
    ("options.page.family.layout.timeline.append", False),
    ("options.page.family.layout.ldsord.visible", False),
    ("options.page.family.layout.ldsord.append", False),
    ("options.page.family.layout.attribute.visible", False),
    ("options.page.family.layout.attribute.append", False),
    ("options.page.family.layout.citation.visible", True),
    ("options.page.family.layout.citation.append", False),
    ("options.page.family.layout.url.visible", False),
    ("options.page.family.layout.url.append", False),
    ("options.page.family.layout.note.visible", False),
    ("options.page.family.layout.note.append", False),
    ("options.page.family.layout.media.visible", False),
    ("options.page.family.layout.media.append", False),
    ("options.page.family.layout.reference.visible", False),
    ("options.page.family.layout.reference.append", False),
    ######################################################################
    ## Event Page Options
    ######################################################################
    ("options.page.event.layout.tabbed", False),
    ("options.page.event.layout.scrolled", False),
    (
        "options.page.event.layout.groups",
        "attribute,people,family,citation,url,note,media,reference",
    ),
    ("options.page.event.layout.attribute.visible", False),
    ("options.page.event.layout.attribute.append", False),
    ("options.page.event.layout.people.visible", True),
    ("options.page.event.layout.people.append", False),
    ("options.page.event.layout.family.visible", True),
    ("options.page.event.layout.family.append", False),
    ("options.page.event.layout.citation.visible", True),
    ("options.page.event.layout.citation.append", False),
    ("options.page.event.layout.url.visible", False),
    ("options.page.event.layout.url.append", False),
    ("options.page.event.layout.note.visible", False),
    ("options.page.event.layout.note.append", False),
    ("options.page.event.layout.media.visible", False),
    ("options.page.event.layout.media.append", False),
    ("options.page.event.layout.reference.visible", False),
    ("options.page.event.layout.reference.append", False),
    ######################################################################
    ## EventRef Page Options
    ######################################################################
    ("options.page.eventref.layout.tabbed", False),
    ("options.page.eventref.layout.scrolled", False),
    ("options.page.eventref.layout.groups", "attribute,note,url"),
    ("options.page.eventref.layout.attribute.visible", True),
    ("options.page.eventref.layout.attribute.append", False),
    ("options.page.eventref.layout.note.visible", True),
    ("options.page.eventref.layout.note.append", False),
    ("options.page.eventref.layout.url.visible", True),
    ("options.page.eventref.layout.url.append", False),
    ######################################################################
    ## LdsOrd Page Options
    ######################################################################
    ("options.page.ldsord.layout.tabbed", False),
    ("options.page.ldsord.layout.scrolled", False),
    (
        "options.page.ldsord.layout.groups",
        "citation,url,note",
    ),
    ("options.page.ldsord.layout.citation.visible", True),
    ("options.page.ldsord.layout.citation.append", False),
    ("options.page.ldsord.layout.url.visible", True),
    ("options.page.ldsord.layout.url.append", True),
    ("options.page.ldsord.layout.note.visible", True),
    ("options.page.ldsord.layout.note.append", False),
    ######################################################################
    ## Source Page Options
    ######################################################################
    ("options.page.source.layout.tabbed", False),
    ("options.page.source.layout.scrolled", False),
    (
        "options.page.source.layout.groups",
        "repository,media,citation,people,event,place,url,note,attribute,reference",
    ),
    ("options.page.source.layout.repository.visible", True),
    ("options.page.source.layout.repository.append", True),
    ("options.page.source.layout.citation.visible", True),
    ("options.page.source.layout.citation.append", False),
    ("options.page.source.layout.attribute.visible", False),
    ("options.page.source.layout.attribute.append", False),
    ("options.page.source.layout.url.visible", True),
    ("options.page.source.layout.url.append", True),
    ("options.page.source.layout.note.visible", True),
    ("options.page.source.layout.note.append", False),
    ("options.page.source.layout.people.visible", True),
    ("options.page.source.layout.people.append", True),
    ("options.page.source.layout.event.visible", True),
    ("options.page.source.layout.event.append", False),
    ("options.page.source.layout.place.visible", True),
    ("options.page.source.layout.place.append", False),
    ("options.page.source.layout.media.visible", True),
    ("options.page.source.layout.media.append", False),
    ("options.page.source.layout.reference.visible", False),
    ("options.page.source.layout.reference.append", False),
    ######################################################################
    ## Citation Page Options
    ######################################################################
    ("options.page.citation.layout.tabbed", False),
    ("options.page.citation.layout.scrolled", False),
    (
        "options.page.citation.layout.groups",
        "reference,attribute,url,note,media",
    ),
    ("options.page.citation.layout.reference.visible", True),
    ("options.page.citation.layout.reference.append", False),
    ("options.page.citation.layout.attribute.visible", False),
    ("options.page.citation.layout.attribute.append", False),
    ("options.page.citation.layout.url.visible", True),
    ("options.page.citation.layout.url.append", True),
    ("options.page.citation.layout.note.visible", True),
    ("options.page.citation.layout.note.append", False),
    ("options.page.citation.layout.media.visible", True),
    ("options.page.citation.layout.media.append", False),
    ######################################################################
    ## Repository Page Options
    ######################################################################
    ("options.page.repository.layout.tabbed", False),
    ("options.page.repository.layout.scrolled", False),
    ("options.page.repository.layout.groups", "reference,source,url,note"),
    ("options.page.repository.layout.source.visible", True),
    ("options.page.repository.layout.source.append", False),
    ("options.page.repository.layout.url.visible", True),
    ("options.page.repository.layout.url.append", True),
    ("options.page.repository.layout.note.visible", True),
    ("options.page.repository.layout.note.append", False),
    ("options.page.repository.layout.reference.visible", True),
    ("options.page.repository.layout.reference.append", False),
    ######################################################################
    ## RepoRef Page Options
    ######################################################################
    ("options.page.reporef.layout.tabbed", False),
    ("options.page.reporef.layout.scrolled", False),
    ("options.page.reporef.layout.groups", "note,url"),
    ("options.page.reporef.layout.note.visible", True),
    ("options.page.reporef.layout.note.append", False),
    ("options.page.reporef.layout.url.visible", True),
    ("options.page.reporef.layout.url.append", False),
    ######################################################################
    ## Note Page Options
    ######################################################################
    ("options.page.note.layout.tabbed", False),
    ("options.page.note.layout.scrolled", False),
    ("options.page.note.layout.groups", "reference"),
    ("options.page.note.layout.reference.visible", True),
    ("options.page.note.layout.reference.append", False),
    ######################################################################
    ## Media Page Options
    ######################################################################
    ("options.page.media.layout.tabbed", False),
    ("options.page.media.layout.scrolled", False),
    (
        "options.page.media.layout.groups",
        "reference,citation,attribute,url,note",
    ),
    ("options.page.media.layout.citation.visible", True),
    ("options.page.media.layout.citation.append", False),
    ("options.page.media.layout.attribute.visible", False),
    ("options.page.media.layout.attribute.append", False),
    ("options.page.media.layout.url.visible", True),
    ("options.page.media.layout.url.append", True),
    ("options.page.media.layout.note.visible", True),
    ("options.page.media.layout.note.append", False),
    ("options.page.media.layout.reference.visible", True),
    ("options.page.media.layout.reference.append", False),
    ######################################################################
    ## MediaRef Page Options
    ######################################################################
    ("options.page.mediaref.layout.tabbed", False),
    ("options.page.mediaref.layout.scrolled", False),
    ("options.page.mediaref.layout.groups", "attribute,citation,note,url"),
    ("options.page.mediaref.layout.attribute.visible", True),
    ("options.page.mediaref.layout.attribute.append", False),
    ("options.page.mediaref.layout.citation.visible", True),
    ("options.page.mediaref.layout.citation.append", False),
    ("options.page.mediaref.layout.note.visible", True),
    ("options.page.mediaref.layout.note.append", False),
    ("options.page.mediaref.layout.url.visible", True),
    ("options.page.mediaref.layout.url.append", False),
    ######################################################################
    ## Place Page Options
    ######################################################################
    ("options.page.place.layout.tabbed", False),
    ("options.page.place.layout.scrolled", False),
    (
        "options.page.place.layout.groups",
        "timeline,place,media,citation,url,note,reference",
    ),
    ("options.page.place.layout.timeline.visible", True),
    ("options.page.place.layout.timeline.append", False),
    ("options.page.place.layout.place.visible", True),
    ("options.page.place.layout.place.append", False),
    ("options.page.place.layout.media.visible", True),
    ("options.page.place.layout.media.append", False),
    ("options.page.place.layout.citation.visible", True),
    ("options.page.place.layout.citation.append", False),
    ("options.page.place.layout.url.visible", True),
    ("options.page.place.layout.url.append", True),
    ("options.page.place.layout.note.visible", True),
    ("options.page.place.layout.note.append", False),
    ("options.page.place.layout.reference.visible", False),
    ("options.page.place.layout.reference.append", False),
    ######################################################################
    ## Tag Page Options
    ######################################################################
    ("options.page.tag.layout.tabbed", False),
    ("options.page.tag.layout.scrolled", False),
    (
        "options.page.tag.layout.groups",
        "person,family,event,place,citation,source,repository,note,media",
    ),
    ("options.page.tag.layout.person.visible", True),
    ("options.page.tag.layout.person.append", True),
    ("options.page.tag.layout.family.visible", True),
    ("options.page.tag.layout.family.append", False),
    ("options.page.tag.layout.event.visible", True),
    ("options.page.tag.layout.event.append", True),
    ("options.page.tag.layout.place.visible", True),
    ("options.page.tag.layout.place.append", False),
    ("options.page.tag.layout.citation.visible", True),
    ("options.page.tag.layout.citation.append", True),
    ("options.page.tag.layout.source.visible", True),
    ("options.page.tag.layout.source.append", True),
    ("options.page.tag.layout.repository.visible", True),
    ("options.page.tag.layout.repository.append", False),
    ("options.page.tag.layout.note.visible", True),
    ("options.page.tag.layout.note.append", True),
    ("options.page.tag.layout.media.visible", True),
    ("options.page.tag.layout.media.append", False),
)
