# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2021       Christopher Horn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Profile Options
"""

CONFIGSETTINGS = (
    ######################################################################
    # Active State
    ######################################################################
    ("options.active.last_object", "None"),

    ######################################################################
    # Additional Color Schemes
    #
    ######################################################################    
    ## Confidence Color Scheme
    ######################################################################    
    ('options.colors.confidence.very-high', ["#99c1f1","#304918"]),
    ('options.colors.confidence.high', ["#8ff0a4","#454545"]),
    ('options.colors.confidence.normal', ["#f9f06b","#454545"]),
    ('options.colors.confidence.low', ["#ffbe6f","#454545"]),
    ('options.colors.confidence.very-low', ["#f66161","#454545"]),
    ('options.colors.confidence.border-very-high', ["#1a5fb4","#000000"]),
    ('options.colors.confidence.border-high', ["#26a269","#000000"]),
    ('options.colors.confidence.border-normal', ["#e5a50a","#000000"]),
    ('options.colors.confidence.border-low', ["#c64600","#000000"]),
    ('options.colors.confidence.border-very-low', ["#a51d2d","#000000"]),
    ######################################################################    
    ## Relationship Color Scheme
    ######################################################################    
    ('options.colors.relations.active', ["#bbe68e","#304918"]),
    ('options.colors.relations.spouse', ["#eeeeee","#454545"]),
    ('options.colors.relations.father', ["#eeeeee","#454545"]),
    ('options.colors.relations.mother', ["#eeeeee","#454545"]),
    ('options.colors.relations.brother', ["#eeeeee","#454545"]),
    ('options.colors.relations.sister', ["#eeeeee","#454545"]),
    ('options.colors.relations.son', ["#eeeeee","#454545"]),
    ('options.colors.relations.daughter', ["#eeeeee","#454545"]),
    ('options.colors.relations.none', ["#eeeeee","#454545"]),
    ('options.colors.relations.border-active', ["#cccccc","#000000"]),
    ('options.colors.relations.border-spouse', ["#cccccc","#000000"]),
    ('options.colors.relations.border-father', ["#cccccc","#000000"]),
    ('options.colors.relations.border-mother', ["#cccccc","#000000"]),
    ('options.colors.relations.border-brother', ["#cccccc","#000000"]),
    ('options.colors.relations.border-sister', ["#cccccc","#000000"]),
    ('options.colors.relations.border-son', ["#cccccc","#000000"]),
    ('options.colors.relations.border-daughter', ["#cccccc","#000000"]),
    ('options.colors.relations.border-none', ["#cccccc","#000000"]),
    ######################################################################    
    ## Event Category Color Scheme
    ######################################################################    
    ('options.colors.events.vital', ["#bbe68e","#304918"]),
    ('options.colors.events.family', ["#eeeeee","#454545"]),
    ('options.colors.events.religious', ["#eeeeee","#454545"]),
    ('options.colors.events.vocational', ["#eeeeee","#454545"]),
    ('options.colors.events.academic', ["#eeeeee","#454545"]),
    ('options.colors.events.travel', ["#eeeeee","#454545"]),
    ('options.colors.events.legal', ["#eeeeee","#454545"]),
    ('options.colors.events.residence', ["#eeeeee","#454545"]),
    ('options.colors.events.other', ["#eeeeee","#454545"]),
    ('options.colors.events.custom', ["#eeeeee","#454545"]),
    ('options.colors.events.border-vital', ["#cccccc","#000000"]),
    ('options.colors.events.border-family', ["#cccccc","#000000"]),
    ('options.colors.events.border-religious', ["#cccccc","#000000"]),
    ('options.colors.events.border-vocational', ["#cccccc","#000000"]),
    ('options.colors.events.border-academic', ["#cccccc","#000000"]),
    ('options.colors.events.border-travel', ["#cccccc","#000000"]),
    ('options.colors.events.border-legal', ["#cccccc","#000000"]),
    ('options.colors.events.border-residence', ["#cccccc","#000000"]),
    ('options.colors.events.border-other', ["#cccccc","#000000"]),
    ('options.colors.events.border-custom', ["#cccccc","#000000"]),

    ######################################################################
    # Global Options
    ######################################################################
    ("options.global.pin-header", True),
    ("options.global.use-color-scheme", True),
    ("options.global.use-smaller-detail-font", True),
    ("options.global.border-width", 2),
    ("options.global.media-bar-display-mode", 1),
    ("options.global.media-bar-sort-by-date", True),
    ("options.global.media-bar-group-by-type", True),
    ("options.global.media-bar-filter-non-photos", False),
    ("options.global.media-bar-page-link", True),
    ("options.global.enable-privacy", True),
    ("options.global.enable-bookmarks", True),
    ("options.global.enable-gramps-ids", True),
    ("options.global.link-citation-title-to-source", True),
    ("options.global.include-child-notes", True),
    ("options.global.include-note-urls", True),
    ("options.global.sort-tags-by-name", False),
    ("options.global.max-citations-per-group", 100),
    ("options.global.max-references-per-group", 100),
    ("options.global.enable-warnings", True),
    ("options.global.enable-tooltips", True),

    ######################################################################
    # Page Layout Options
    #
    ######################################################################
    ## Name Page Options
    ######################################################################    
    ("options.page.name.layout.tabbed", False),
    ("options.page.name.layout.scrolled", False),
    ("options.page.name.layout.groups", "citation,note,url"),
    ("options.page.name.layout.citation.visible", True),
    ("options.page.name.layout.citation.stacked", False),
    ("options.page.name.layout.citation.hideable", False),
    ("options.page.name.layout.note.visible", True),
    ("options.page.name.layout.note.stacked", False),
    ("options.page.name.layout.note.hideable", False),
    ("options.page.name.layout.url.visible", True),
    ("options.page.name.layout.url.stacked", False),
    ("options.page.name.layout.url.hideable", False),
    ######################################################################
    ## Attribute Page Options
    ######################################################################    
    ("options.page.attribute.layout.tabbed", False),
    ("options.page.attribute.layout.scrolled", False),
    ("options.page.attribute.layout.groups", "citation,note,url"),
    ("options.page.attribute.layout.citation.visible", True),
    ("options.page.attribute.layout.citation.stacked", False),
    ("options.page.attribute.layout.citation.hideable", False),
    ("options.page.attribute.layout.note.visible", True),
    ("options.page.attribute.layout.note.stacked", False),
    ("options.page.attribute.layout.note.hideable", False),
    ("options.page.attribute.layout.url.visible", True),
    ("options.page.attribute.layout.url.stacked", False),
    ("options.page.attribute.layout.url.hideable", False),
    ######################################################################
    ## Address Page Options
    ######################################################################    
    ("options.page.address.layout.tabbed", False),
    ("options.page.address.layout.scrolled", False),
    ("options.page.address.layout.groups", "citation,note,url"),
    ("options.page.address.layout.citation.visible", True),
    ("options.page.address.layout.citation.stacked", False),
    ("options.page.address.layout.citation.hideable", False),
    ("options.page.address.layout.note.visible", True),
    ("options.page.address.layout.note.stacked", False),
    ("options.page.address.layout.note.hideable", False),
    ("options.page.address.layout.url.visible", True),
    ("options.page.address.layout.url.stacked", False),
    ("options.page.address.layout.url.hideable", False),
    ######################################################################
    ## ChildRef Page Options
    ######################################################################
    ("options.page.childref.layout.tabbed", False),
    ("options.page.childref.layout.scrolled", False),
    ("options.page.childref.layout.groups", "citation,note,url"),
    ("options.page.childref.layout.citation.visible", True),
    ("options.page.childref.layout.citation.stacked", False),
    ("options.page.childref.layout.citation.hideable", False),
    ("options.page.childref.layout.note.visible", True),
    ("options.page.childref.layout.note.stacked", False),
    ("options.page.childref.layout.note.hideable", False),
    ("options.page.childref.layout.url.visible", True),
    ("options.page.childref.layout.url.stacked", False),
    ("options.page.childref.layout.url.hideable", False),
    ######################################################################
    ## PersonRef Page Options
    ######################################################################
    ("options.page.personref.layout.tabbed", False),
    ("options.page.personref.layout.scrolled", False),
    ("options.page.personref.layout.groups", "citation,note,url"),
    ("options.page.personref.layout.citation.visible", True),
    ("options.page.personref.layout.citation.stacked", False),
    ("options.page.personref.layout.citation.hideable", False),
    ("options.page.personref.layout.note.visible", True),
    ("options.page.personref.layout.note.stacked", False),
    ("options.page.personref.layout.note.hideable", False),
    ("options.page.personref.layout.url.visible", True),
    ("options.page.personref.layout.url.stacked", False),
    ("options.page.personref.layout.url.hideable", False),
    ######################################################################
    ## Person Page Options
    ######################################################################
    ("options.page.person.layout.tabbed", False),
    ("options.page.person.layout.scrolled", False),
    ("options.page.person.layout.groups", "parent,timeline,spouse,name,attribute,association,citation,address,url,note,media"),
    ("options.page.person.layout.parent.visible", True),
    ("options.page.person.layout.parent.stacked", False),
    ("options.page.person.layout.parent.hideable", False),
    ("options.page.person.layout.timeline.visible", True),
    ("options.page.person.layout.timeline.stacked", False),
    ("options.page.person.layout.timeline.hideable", False),
    ("options.page.person.layout.spouse.visible", True),
    ("options.page.person.layout.spouse.stacked", False),
    ("options.page.person.layout.spouse.hideable", False),
    ("options.page.person.layout.name.visible", True),
    ("options.page.person.layout.name.stacked", True),
    ("options.page.person.layout.name.hideable", False),
    ("options.page.person.layout.attribute.visible", True),
    ("options.page.person.layout.attribute.stacked", True),
    ("options.page.person.layout.attribute.hideable", False),
    ("options.page.person.layout.association.visible", True),
    ("options.page.person.layout.association.stacked", False),
    ("options.page.person.layout.association.hideable", False),
    ("options.page.person.layout.citation.visible", True),
    ("options.page.person.layout.citation.stacked", False),
    ("options.page.person.layout.citation.hideable", False),
    ("options.page.person.layout.address.visible", True),
    ("options.page.person.layout.address.stacked", True),
    ("options.page.person.layout.address.hideable", False),
    ("options.page.person.layout.url.visible", True),
    ("options.page.person.layout.url.stacked", True),
    ("options.page.person.layout.url.hideable", False),
    ("options.page.person.layout.note.visible", True),
    ("options.page.person.layout.note.stacked", False),
    ("options.page.person.layout.note.hideable", False),
    ("options.page.person.layout.media.visible", False),
    ("options.page.person.layout.media.stacked", False),
    ("options.page.person.layout.media.hideable", False),
    ######################################################################
    ## Family Page Options
    ######################################################################
    ("options.page.family.layout.tabbed", False),
    ("options.page.family.layout.scrolled", False),
    ("options.page.family.layout.groups", "child,timeline,attribute,citation,url,note,media"),
    ("options.page.family.layout.child.visible", True),
    ("options.page.family.layout.child.stacked", False),
    ("options.page.family.layout.child.hideable", False),
    ("options.page.family.layout.timeline.visible", True),
    ("options.page.family.layout.timeline.stacked", False),
    ("options.page.family.layout.timeline.hideable", False),
    ("options.page.family.layout.attribute.visible", True),
    ("options.page.family.layout.attribute.stacked", False),
    ("options.page.family.layout.attribute.hideable", False),
    ("options.page.family.layout.citation.visible", True),
    ("options.page.family.layout.citation.stacked", False),
    ("options.page.family.layout.citation.hideable", False),
    ("options.page.family.layout.url.visible", True),
    ("options.page.family.layout.url.stacked", True),
    ("options.page.family.layout.url.hideable", False),
    ("options.page.family.layout.note.visible", True),
    ("options.page.family.layout.note.stacked", False),
    ("options.page.family.layout.note.hideable", False),
    ("options.page.family.layout.media.visible", False),
    ("options.page.family.layout.media.stacked", False),
    ("options.page.family.layout.media.hideable", False),
    ######################################################################
    ## Event Page Options
    ######################################################################
    ("options.page.event.layout.tabbed", False),
    ("options.page.event.layout.scrolled", False),
    ("options.page.event.layout.groups", "attribute,people,family,citation,url,note,media"),
    ("options.page.event.layout.attribute.visible", True),
    ("options.page.event.layout.attribute.stacked", False),
    ("options.page.event.layout.attribute.hideable", False),
    ("options.page.event.layout.people.visible", True),
    ("options.page.event.layout.people.stacked", False),
    ("options.page.event.layout.people.hideable", False),
    ("options.page.event.layout.family.visible", True),
    ("options.page.event.layout.family.stacked", False),
    ("options.page.event.layout.family.hideable", False),
    ("options.page.event.layout.citation.visible", True),
    ("options.page.event.layout.citation.stacked", False),
    ("options.page.event.layout.citation.hideable", False),
    ("options.page.event.layout.url.visible", True),
    ("options.page.event.layout.url.stacked", True),
    ("options.page.event.layout.url.hideable", False),
    ("options.page.event.layout.note.visible", True),
    ("options.page.event.layout.note.stacked", False),
    ("options.page.event.layout.note.hideable", False),
    ("options.page.event.layout.media.visible", False),
    ("options.page.event.layout.media.stacked", False),
    ("options.page.event.layout.media.hideable", False),
    ######################################################################
    ## Source Page Options
    ######################################################################
    ("options.page.source.layout.tabbed", False),
    ("options.page.source.layout.scrolled", False),
    ("options.page.source.layout.groups", "repository,citation,attribute,url,note,people,event,media"),
    ("options.page.source.layout.repository.visible", True),
    ("options.page.source.layout.repository.stacked", False),
    ("options.page.source.layout.repository.hideable", False),
    ("options.page.source.layout.citation.visible", True),
    ("options.page.source.layout.citation.stacked", False),
    ("options.page.source.layout.citation.hideable", False),
    ("options.page.source.layout.attribute.visible", True),
    ("options.page.source.layout.attribute.stacked", True),
    ("options.page.source.layout.attribute.hideable", False),
    ("options.page.source.layout.url.visible", True),
    ("options.page.source.layout.url.stacked", True),
    ("options.page.source.layout.url.hideable", False),
    ("options.page.source.layout.note.visible", True),
    ("options.page.source.layout.note.stacked", False),
    ("options.page.source.layout.note.hideable", False),
    ("options.page.source.layout.people.visible", True),
    ("options.page.source.layout.people.stacked", False),
    ("options.page.source.layout.people.hideable", False),
    ("options.page.source.layout.event.visible", True),
    ("options.page.source.layout.event.stacked", False),
    ("options.page.source.layout.event.hideable", False),
    ("options.page.source.layout.media.visible", False),
    ("options.page.source.layout.media.stacked", False),
    ("options.page.source.layout.media.hideable", False),
    ######################################################################
    ## Citation Page Options
    ######################################################################
    ("options.page.citation.layout.tabbed", False),
    ("options.page.citation.layout.scrolled", False),
    ("options.page.citation.layout.groups", "reference,attribute,url,note,media"),
    ("options.page.citation.layout.reference.visible", True),
    ("options.page.citation.layout.reference.stacked", False),
    ("options.page.citation.layout.reference.hideable", False),
    ("options.page.citation.layout.attribute.visible", True),
    ("options.page.citation.layout.attribute.stacked", True),
    ("options.page.citation.layout.attribute.hideable", False),
    ("options.page.citation.layout.url.visible", True),
    ("options.page.citation.layout.url.stacked", True),
    ("options.page.citation.layout.url.hideable", False),
    ("options.page.citation.layout.note.visible", True),
    ("options.page.citation.layout.note.stacked", False),
    ("options.page.citation.layout.note.hideable", False),
    ("options.page.citation.layout.media.visible", False),
    ("options.page.citation.layout.media.stacked", False),
    ("options.page.citation.layout.media.hideable", False),
    ######################################################################
    ## Repository Page Options
    ######################################################################
    ("options.page.repository.layout.tabbed", False),
    ("options.page.repository.layout.scrolled", False),
    ("options.page.repository.layout.groups", "source,url,note"),
    ("options.page.repository.layout.source.visible", True),
    ("options.page.repository.layout.source.stacked", False),
    ("options.page.repository.layout.source.hideable", False),
    ("options.page.repository.layout.url.visible", True),
    ("options.page.repository.layout.url.stacked", False),
    ("options.page.repository.layout.url.hideable", False),
    ("options.page.repository.layout.note.visible", True),
    ("options.page.repository.layout.note.stacked", False),
    ("options.page.repository.layout.note.hideable", False),
    ######################################################################
    ## Note Page Options
    ######################################################################
    ("options.page.note.layout.tabbed", False),
    ("options.page.note.layout.scrolled", False),
    ("options.page.note.layout.groups", "reference"),
    ("options.page.note.layout.reference.visible", True),
    ("options.page.note.layout.reference.stacked", False),
    ("options.page.note.layout.reference.hideable", False),
    ######################################################################
    ## Media Page Options
    ######################################################################
    ("options.page.media.layout.tabbed", False),
    ("options.page.media.layout.scrolled", False),
    ("options.page.media.layout.groups", "citation,attribute,url,note,reference"),
    ("options.page.media.layout.citation.visible", True),
    ("options.page.media.layout.citation.stacked", False),
    ("options.page.media.layout.citation.hideable", False),
    ("options.page.media.layout.attribute.visible", True),
    ("options.page.media.layout.attribute.stacked", True),
    ("options.page.media.layout.attribute.hideable", False),
    ("options.page.media.layout.url.visible", True),
    ("options.page.media.layout.url.stacked", True),
    ("options.page.media.layout.url.hideable", False),
    ("options.page.media.layout.note.visible", True),
    ("options.page.media.layout.note.stacked", False),
    ("options.page.media.layout.note.hideable", False),
    ("options.page.media.layout.reference.visible", True),
    ("options.page.media.layout.reference.stacked", False),
    ("options.page.media.layout.reference.hideable", False),
    ######################################################################
    ## Place Page Options
    ######################################################################
    ("options.page.place.layout.tabbed", False),
    ("options.page.place.layout.scrolled", False),
    ("options.page.place.layout.groups", "citation,url,note,media,reference"),
    ("options.page.place.layout.citation.visible", True),
    ("options.page.place.layout.citation.stacked", False),
    ("options.page.place.layout.citation.hideable", False),
    ("options.page.place.layout.url.visible", True),
    ("options.page.place.layout.url.stacked", True),
    ("options.page.place.layout.url.hideable", False),
    ("options.page.place.layout.note.visible", True),
    ("options.page.place.layout.note.stacked", False),
    ("options.page.place.layout.note.hideable", False),
    ("options.page.place.layout.media.visible", False),
    ("options.page.place.layout.media.stacked", False),
    ("options.page.place.layout.media.hideable", False),
    ("options.page.place.layout.reference.visible", True),
    ("options.page.place.layout.reference.stacked", False),
    ("options.page.place.layout.reference.hideable", False),
    ######################################################################
    ## Tag Page Options
    ######################################################################
    ("options.page.tag.layout.tabbed", False),
    ("options.page.tag.layout.scrolled", False),
    ("options.page.tag.layout.groups", "person,family,event,place,citation,source,repository,note,media"),
    ("options.page.tag.layout.person.visible", True),
    ("options.page.tag.layout.person.stacked", False),
    ("options.page.tag.layout.person.hideable", False),
    ("options.page.tag.layout.family.visible", True),
    ("options.page.tag.layout.family.stacked", False),
    ("options.page.tag.layout.family.hideable", False),
    ("options.page.tag.layout.event.visible", True),
    ("options.page.tag.layout.event.stacked", False),
    ("options.page.tag.layout.event.hideable", False),
    ("options.page.tag.layout.place.visible", True),
    ("options.page.tag.layout.place.stacked", False),
    ("options.page.tag.layout.place.hideable", False),
    ("options.page.tag.layout.citation.visible", True),
    ("options.page.tag.layout.citation.stacked", True),
    ("options.page.tag.layout.citation.hideable", False),
    ("options.page.tag.layout.source.visible", True),
    ("options.page.tag.layout.source.stacked", True),
    ("options.page.tag.layout.source.hideable", False),
    ("options.page.tag.layout.repository.visible", True),
    ("options.page.tag.layout.repository.stacked", False),
    ("options.page.tag.layout.repository.hideable", False),
    ("options.page.tag.layout.note.visible", True),
    ("options.page.tag.layout.note.stacked", True),
    ("options.page.tag.layout.note.hideable", False),
    ("options.page.tag.layout.media.visible", True),
    ("options.page.tag.layout.media.stacked", False),
    ("options.page.tag.layout.media.hideable", False),

    ######################################################################
    # Frame Level Options
    # These apply when the frame is in the page header and not a group
    #
    ######################################################################
    ## Person Options
    ######################################################################
    ("options.active.person.event-format", 1),
    ("options.active.person.show-age", True),
    ("options.active.person.sex-mode", 1),
    ("options.active.person.image-mode", 3),
    ("options.active.person.tag-format", 1),
    ("options.active.person.tag-width", 10),
    ("options.active.person.facts-field-skip-birth-alternates", False),
    ("options.active.person.facts-field-skip-death-alternates", False),
    ("options.active.person.facts-field-1", "Event:Birth:False"),
    ("options.active.person.facts-field-2", "Event:Baptism:False"),
    ("options.active.person.facts-field-3", "Event:Christening:False"),
    ("options.active.person.facts-field-4", "Event:Death:False"),
    ("options.active.person.facts-field-5", "Event:Burial:False"),
    ("options.active.person.facts-field-6", "Event:Cremation:False"),
    ("options.active.person.facts-field-7", "Event:Probate:False"),
    ("options.active.person.facts-field-8", "None"),
    ("options.active.person.extra-field-skip-birth-alternates", False),
    ("options.active.person.extra-field-skip-death-alternates", False),
    ("options.active.person.extra-field-1", "None"),
    ("options.active.person.extra-field-2", "None"),
    ("options.active.person.extra-field-3", "None"),
    ("options.active.person.extra-field-4", "None"),
    ("options.active.person.extra-field-5", "None"),
    ("options.active.person.extra-field-6", "None"),
    ("options.active.person.extra-field-7", "None"),
    ("options.active.person.extra-field-8", "None"),
    ("options.active.person.metadata-attribute-1", "None"),
    ("options.active.person.metadata-attribute-2", "None"),
    ("options.active.person.metadata-attribute-3", "None"),
    ("options.active.person.metadata-attribute-4", "None"),
    ("options.active.person.metadata-attribute-5", "None"),
    ("options.active.person.metadata-attribute-6", "None"),
    ("options.active.person.metadata-attribute-7", "None"),
    ("options.active.person.metadata-attribute-8", "None"),
    ######################################################################    
    ## Parent Options
    ######################################################################
    ("options.active.parent.event-format", 1),
    ("options.active.parent.show-age", False),
    ("options.active.parent.sex-mode", 1),
    ("options.active.parent.image-mode", 3),
    ("options.active.parent.tag-format", 1),
    ("options.active.parent.tag-width", 10),
    ("options.active.parent.show-matrilineal", False),
    ("options.active.parent.expand-children", True),
    ("options.active.parent.show-divorce", True),
    ("options.active.parent.facts-field-skip-birth-alternates", True),
    ("options.active.parent.facts-field-skip-death-alternates", True),
    ("options.active.parent.facts-field-1", "Event:Birth:False"),
    ("options.active.parent.facts-field-2", "Event:Baptism:False"),
    ("options.active.parent.facts-field-3", "Event:Christening:False"),
    ("options.active.parent.facts-field-4", "Event:Death:False"),
    ("options.active.parent.facts-field-5", "Event:Burial:False"),
    ("options.active.parent.facts-field-6", "Event:Cremation:False"),
    ("options.active.parent.facts-field-7", "Event:Probate:False"),
    ("options.active.parent.facts-field-8", "None"),
    ("options.active.parent.metadata-attribute-1", "None"),
    ("options.active.parent.metadata-attribute-2", "None"),
    ("options.active.parent.metadata-attribute-3", "None"),
    ("options.active.parent.metadata-attribute-4", "None"),
    ("options.active.parent.metadata-attribute-5", "None"),
    ("options.active.parent.metadata-attribute-6", "None"),
    ("options.active.parent.metadata-attribute-7", "None"),
    ("options.active.parent.metadata-attribute-8", "None"),
    ######################################################################    
    ## Spouse Options
    ######################################################################
    ("options.active.spouse.event-format", 1),
    ("options.active.spouse.show-age", False),
    ("options.active.spouse.sex-mode", 1),
    ("options.active.spouse.image-mode", 3),
    ("options.active.spouse.tag-format", 1),
    ("options.active.spouse.tag-width", 10),
    ("options.active.spouse.expand-children", True),
    ("options.active.spouse.show-spouse-only", True),
    ("options.active.spouse.show-divorce", True),
    ("options.active.spouse.facts-field-skip-birth-alternates", True),
    ("options.active.spouse.facts-field-skip-death-alternates", True),
    ("options.active.spouse.facts-field-1", "Event:Birth:False"),
    ("options.active.spouse.facts-field-2", "Event:Baptism:False"),
    ("options.active.spouse.facts-field-3", "Event:Christening:False"),
    ("options.active.spouse.facts-field-4", "Event:Death:False"),
    ("options.active.spouse.facts-field-5", "Event:Burial:False"),
    ("options.active.spouse.facts-field-6", "Event:Cremation:False"),
    ("options.active.spouse.facts-field-7", "Event:Probate:False"),
    ("options.active.spouse.facts-field-8", "None"),
    ("options.active.spouse.metadata-attribute-1", "None"),
    ("options.active.spouse.metadata-attribute-2", "None"),
    ("options.active.spouse.metadata-attribute-3", "None"),
    ("options.active.spouse.metadata-attribute-4", "None"),
    ("options.active.spouse.metadata-attribute-5", "None"),
    ("options.active.spouse.metadata-attribute-6", "None"),
    ("options.active.spouse.metadata-attribute-7", "None"),
    ("options.active.spouse.metadata-attribute-8", "None"),
    ######################################################################
    ## Association Options
    ######################################################################
    ("options.active.association.event-format", 1),
    ("options.active.association.show-age", False),
    ("options.active.association.sex-mode", 1),
    ("options.active.association.image-mode", 3),
    ("options.active.association.tag-format", 1),
    ("options.active.association.tag-width", 10),
    ("options.active.association.facts-field-skip-birth-alternates", True),
    ("options.active.association.facts-field-skip-death-alternates", True),
    ("options.active.association.facts-field-1", "Event:Birth:False"),
    ("options.active.association.facts-field-2", "Event:Baptism:False"),
    ("options.active.association.facts-field-3", "Event:Christening:False"),
    ("options.active.association.facts-field-4", "Event:Death:False"),
    ("options.active.association.facts-field-5", "Event:Burial:False"),
    ("options.active.association.facts-field-6", "Event:Cremation:False"),
    ("options.active.association.facts-field-7", "Event:Probate:False"),
    ("options.active.association.facts-field-8", "None"),
    ("options.active.association.metadata-attribute-1", "None"),
    ("options.active.association.metadata-attribute-2", "None"),
    ("options.active.association.metadata-attribute-3", "None"),
    ("options.active.association.metadata-attribute-4", "None"),
    ("options.active.association.metadata-attribute-5", "None"),
    ("options.active.association.metadata-attribute-6", "None"),
    ("options.active.association.metadata-attribute-7", "None"),
    ("options.active.association.metadata-attribute-8", "None"),
    ######################################################################
    ## Participant Options
    ######################################################################
    ("options.active.participant.event-format", 1),
    ("options.active.participant.show-age", False),
    ("options.active.participant.sex-mode", 1),
    ("options.active.participant.image-mode", 3),
    ("options.active.participant.tag-format", 1),
    ("options.active.participant.tag-width", 10),
    ("options.active.participant.facts-field-skip-birth-alternates", True),
    ("options.active.participant.facts-field-skip-death-alternates", True),
    ("options.active.participant.facts-field-1", "Event:Birth:False"),
    ("options.active.participant.facts-field-2", "Event:Baptism:False"),
    ("options.active.participant.facts-field-3", "Event:Christening:False"),
    ("options.active.participant.facts-field-4", "Event:Death:False"),
    ("options.active.participant.facts-field-5", "Event:Burial:False"),
    ("options.active.participant.facts-field-6", "Event:Cremation:False"),
    ("options.active.participant.facts-field-7", "Event:Probate:False"),
    ("options.active.participant.facts-field-8", "None"),
    ("options.active.participant.metadata-attribute-1", "None"),
    ("options.active.participant.metadata-attribute-2", "None"),
    ("options.active.participant.metadata-attribute-3", "None"),
    ("options.active.participant.metadata-attribute-4", "None"),
    ("options.active.participant.metadata-attribute-5", "None"),
    ("options.active.participant.metadata-attribute-6", "None"),
    ("options.active.participant.metadata-attribute-7", "None"),
    ("options.active.participant.metadata-attribute-8", "None"),
    ######################################################################
    ## Family Options
    ######################################################################
    ("options.active.family.event-format", 1),
    ("options.active.family.show-age", True),
    ("options.active.family.sex-mode", 1),
    ("options.active.family.image-mode", 3),
    ("options.active.family.tag-format", 1),
    ("options.active.family.tag-width", 10),
    ("options.active.family.facts-field-skip-birth-alternates", False),
    ("options.active.family.facts-field-skip-death-alternates", False),
    ("options.active.family.facts-field-1", "Event:Birth:False"),
    ("options.active.family.facts-field-2", "Event:Baptism:False"),
    ("options.active.family.facts-field-3", "Event:Christening:False"),
    ("options.active.family.facts-field-4", "Event:Death:False"),
    ("options.active.family.facts-field-5", "Event:Burial:False"),
    ("options.active.family.facts-field-6", "Event:Cremation:False"),
    ("options.active.family.facts-field-7", "Event:Probate:False"),
    ("options.active.family.facts-field-8", "None"),
    ("options.active.family.metadata-attribute-1", "None"),
    ("options.active.family.metadata-attribute-2", "None"),
    ("options.active.family.metadata-attribute-3", "None"),
    ("options.active.family.metadata-attribute-4", "None"),
    ("options.active.family.metadata-attribute-5", "None"),
    ("options.active.family.metadata-attribute-6", "None"),
    ("options.active.family.metadata-attribute-7", "None"),
    ("options.active.family.metadata-attribute-8", "None"),
    ######################################################################
    ## Event Options
    ######################################################################
    ("options.active.event.event-format", 1),
    ("options.active.event.image-mode", 3),
    ("options.active.event.tag-format", 1),
    ("options.active.event.tag-width", 10),
    ("options.active.event.metadata-attribute-1", "None"),
    ("options.active.event.metadata-attribute-2", "None"),
    ("options.active.event.metadata-attribute-3", "None"),
    ("options.active.event.metadata-attribute-4", "None"),
    ("options.active.event.show-description", True),
    ("options.active.event.show-participants", True),
    ("options.active.event.show-role-always", False),
    ("options.active.event.show-source-count", True),
    ("options.active.event.show-citation-count", True),
    ("options.active.event.show-best-confidence", True),
    ######################################################################
    ## Place Options
    ######################################################################
    ("options.active.place.tag-format", 1),
    ("options.active.place.tag-width", 10),
    ######################################################################
    ## Citation Options
    ######################################################################
    ("options.active.citation.tag-format", 1),
    ("options.active.citation.tag-width", 10),
    ("options.active.citation.image-mode", 0),
    ("options.active.citation.sort-by-date", False),
    ("options.active.citation.include-indirect", True),
    ("options.active.citation.include-parent-family", True),
    ("options.active.citation.include-family", True),
    ("options.active.citation.include-family-indirect", True),
    ("options.active.citation.show-date", True),
    ("options.active.citation.show-publisher", True),
    ("options.active.citation.show-reference-type", True),
    ("options.active.citation.show-reference-description", True),
    ("options.active.citation.show-confidence", True),
    ("options.active.citation.metadata-attribute-1", "None"),
    ("options.active.citation.metadata-attribute-2", "None"),
    ("options.active.citation.metadata-attribute-3", "None"),
    ("options.active.citation.metadata-attribute-4", "None"),
    ######################################################################
    ## Source Options
    ######################################################################
    ("options.active.source.event-format", 1),
    ("options.active.source.image-mode", 3),
    ("options.active.source.tag-format", 1),
    ("options.active.source.tag-width", 10),
    ("options.active.source.metadata-attribute-1", "None"),
    ("options.active.source.metadata-attribute-2", "None"),
    ("options.active.source.metadata-attribute-3", "None"),
    ("options.active.source.metadata-attribute-4", "None"),
    ######################################################################
    ## Repository Options
    ######################################################################
    ("options.active.repository.tag-format", 1),
    ("options.active.repository.tag-width", 10),
    ("options.active.repository.show-call-number", True),
    ("options.active.repository.show-media-type", True),
    ("options.active.repository.show-repository-type", True),
    ######################################################################
    ## Media Options
    ######################################################################    
    ("options.active.media.tag-format", 1),
    ("options.active.media.tag-width", 10),
    ("options.active.media.image-mode", 2),
    ("options.active.media.show-date", True),
    ("options.active.media.metadata-attribute-1", "None"),
    ("options.active.media.metadata-attribute-2", "None"),
    ("options.active.media.metadata-attribute-3", "None"),
    ("options.active.media.metadata-attribute-4", "None"),

    ######################################################################
    ## Note Options
    ######################################################################
    ("options.active.note.preview-mode", True),
    ("options.active.note.preview-lines", 4),
    ("options.active.note.tag-format", 1),
    ("options.active.note.tag-width", 10),


    ######################################################################
    # Group Level Options
    # These apply when the frame is in a group and not the page header
    #
    ######################################################################
    ## Person Options
    ######################################################################
    ("options.group.person.event-format", 1),
    ("options.group.person.show-age", True),
    ("options.group.person.sex-mode", 1),
    ("options.group.person.image-mode", 3),
    ("options.group.person.tag-format", 1),
    ("options.group.person.tag-width", 10),
    ("options.group.person.facts-field-skip-birth-alternates", False),
    ("options.group.person.facts-field-skip-death-alternates", False),
    ("options.group.person.facts-field-1", "Event:Birth:False"),
    ("options.group.person.facts-field-2", "Event:Baptism:False"),
    ("options.group.person.facts-field-3", "Event:Christening:False"),
    ("options.group.person.facts-field-4", "Event:Death:False"),
    ("options.group.person.facts-field-5", "Event:Burial:False"),
    ("options.group.person.facts-field-6", "Event:Cremation:False"),
    ("options.group.person.facts-field-7", "Event:Probate:False"),
    ("options.group.person.facts-field-8", "None"),
    ("options.group.person.extra-field-skip-birth-alternates", False),
    ("options.group.person.extra-field-skip-death-alternates", False),
    ("options.group.person.extra-field-1", "None"),
    ("options.group.person.extra-field-2", "None"),
    ("options.group.person.extra-field-3", "None"),
    ("options.group.person.extra-field-4", "None"),
    ("options.group.person.extra-field-5", "None"),
    ("options.group.person.extra-field-6", "None"),
    ("options.group.person.extra-field-7", "None"),
    ("options.group.person.extra-field-8", "None"),
    ("options.group.person.metadata-attribute-1", "None"),
    ("options.group.person.metadata-attribute-2", "None"),
    ("options.group.person.metadata-attribute-3", "None"),
    ("options.group.person.metadata-attribute-4", "None"),
    ("options.group.person.metadata-attribute-5", "None"),
    ("options.group.person.metadata-attribute-6", "None"),
    ("options.group.person.metadata-attribute-7", "None"),
    ("options.group.person.metadata-attribute-8", "None"),
    ######################################################################    
    ## Parent Options
    ######################################################################
    ("options.group.parent.event-format", 1),
    ("options.group.parent.show-age", False),
    ("options.group.parent.sex-mode", 1),
    ("options.group.parent.image-mode", 3),
    ("options.group.parent.tag-format", 1),
    ("options.group.parent.tag-width", 10),
    ("options.group.parent.show-matrilineal", False),
    ("options.group.parent.expand-children", True),
    ("options.group.parent.show-divorce", True),
    ("options.group.parent.facts-field-skip-birth-alternates", True),
    ("options.group.parent.facts-field-skip-death-alternates", True),
    ("options.group.parent.facts-field-1", "Event:Birth:False"),
    ("options.group.parent.facts-field-2", "Event:Baptism:False"),
    ("options.group.parent.facts-field-3", "Event:Christening:False"),
    ("options.group.parent.facts-field-4", "Event:Death:False"),
    ("options.group.parent.facts-field-5", "Event:Burial:False"),
    ("options.group.parent.facts-field-6", "Event:Cremation:False"),
    ("options.group.parent.facts-field-7", "Event:Probate:False"),
    ("options.group.parent.facts-field-8", "None"),
    ("options.group.parent.metadata-attribute-1", "None"),
    ("options.group.parent.metadata-attribute-2", "None"),
    ("options.group.parent.metadata-attribute-3", "None"),
    ("options.group.parent.metadata-attribute-4", "None"),
    ("options.group.parent.metadata-attribute-5", "None"),
    ("options.group.parent.metadata-attribute-6", "None"),
    ("options.group.parent.metadata-attribute-7", "None"),
    ("options.group.parent.metadata-attribute-8", "None"),
    ######################################################################
    ## Sibling Options
    ######################################################################
    ("options.group.sibling.event-format", 1),
    ("options.group.sibling.show-age", False),
    ("options.group.sibling.sex-mode", 1),
    ("options.group.sibling.image-mode", 3),
    ("options.group.sibling.tag-format", 1),
    ("options.group.sibling.tag-width", 10),
    ("options.group.sibling.number-children", True),
    ("options.group.sibling.facts-field-skip-birth-alternates", True),
    ("options.group.sibling.facts-field-skip-death-alternates", True),
    ("options.group.sibling.facts-field-1", "Event:Birth:False"),
    ("options.group.sibling.facts-field-2", "Event:Baptism:False"),
    ("options.group.sibling.facts-field-3", "Event:Christening:False"),
    ("options.group.sibling.facts-field-4", "Event:Death:False"),
    ("options.group.sibling.facts-field-5", "Event:Burial:False"),
    ("options.group.sibling.facts-field-6", "Event:Cremation:False"),
    ("options.group.sibling.facts-field-7", "Event:Probate:False"),
    ("options.group.sibling.facts-field-8", "None"),
    ("options.group.sibling.metadata-attribute-1", "None"),
    ("options.group.sibling.metadata-attribute-2", "None"),
    ("options.group.sibling.metadata-attribute-3", "None"),
    ("options.group.sibling.metadata-attribute-4", "None"),
    ("options.group.sibling.metadata-attribute-5", "None"),
    ("options.group.sibling.metadata-attribute-6", "None"),
    ("options.group.sibling.metadata-attribute-7", "None"),
    ("options.group.sibling.metadata-attribute-8", "None"),
    ######################################################################    
    ## Spouse Options
    ######################################################################
    ("options.group.spouse.event-format", 1),
    ("options.group.spouse.show-age", False),
    ("options.group.spouse.sex-mode", 1),
    ("options.group.spouse.image-mode", 3),
    ("options.group.spouse.tag-format", 1),
    ("options.group.spouse.tag-width", 10),
    ("options.group.spouse.expand-children", True),
    ("options.group.spouse.show-spouse-only", True),
    ("options.group.spouse.show-divorce", True),
    ("options.group.spouse.facts-field-skip-birth-alternates", True),
    ("options.group.spouse.facts-field-skip-death-alternates", True),
    ("options.group.spouse.facts-field-1", "Event:Birth:False"),
    ("options.group.spouse.facts-field-2", "Event:Baptism:False"),
    ("options.group.spouse.facts-field-3", "Event:Christening:False"),
    ("options.group.spouse.facts-field-4", "Event:Death:False"),
    ("options.group.spouse.facts-field-5", "Event:Burial:False"),
    ("options.group.spouse.facts-field-6", "Event:Cremation:False"),
    ("options.group.spouse.facts-field-7", "Event:Probate:False"),
    ("options.group.spouse.facts-field-8", "None"),
    ("options.group.spouse.metadata-attribute-1", "None"),
    ("options.group.spouse.metadata-attribute-2", "None"),
    ("options.group.spouse.metadata-attribute-3", "None"),
    ("options.group.spouse.metadata-attribute-4", "None"),
    ("options.group.spouse.metadata-attribute-5", "None"),
    ("options.group.spouse.metadata-attribute-6", "None"),
    ("options.group.spouse.metadata-attribute-7", "None"),
    ("options.group.spouse.metadata-attribute-8", "None"),
    ######################################################################
    ## Child Options
    ######################################################################
    ("options.group.child.event-format", 1),
    ("options.group.child.show-age", False),
    ("options.group.child.sex-mode", 1),
    ("options.group.child.image-mode", 3),
    ("options.group.child.tag-format", 1),
    ("options.group.child.tag-width", 10),
    ("options.group.child.number-children", True),
    ("options.group.child.facts-field-skip-birth-alternates", True),
    ("options.group.child.facts-field-skip-death-alternates", True),
    ("options.group.child.facts-field-1", "Event:Birth:False"),
    ("options.group.child.facts-field-2", "Event:Baptism:False"),
    ("options.group.child.facts-field-3", "Event:Christening:False"),
    ("options.group.child.facts-field-4", "Event:Death:False"),
    ("options.group.child.facts-field-5", "Event:Burial:False"),
    ("options.group.child.facts-field-6", "Event:Cremation:False"),
    ("options.group.child.facts-field-7", "Event:Probate:False"),
    ("options.group.child.facts-field-8", "None"),
    ("options.group.child.metadata-attribute-1", "None"),
    ("options.group.child.metadata-attribute-2", "None"),
    ("options.group.child.metadata-attribute-3", "None"),
    ("options.group.child.metadata-attribute-4", "None"),
    ("options.group.child.metadata-attribute-5", "None"),
    ("options.group.child.metadata-attribute-6", "None"),
    ("options.group.child.metadata-attribute-7", "None"),
    ("options.group.child.metadata-attribute-8", "None"),
    ######################################################################
    ## Association Options
    ######################################################################
    ("options.group.association.event-format", 1),
    ("options.group.association.show-age", False),
    ("options.group.association.sex-mode", 1),
    ("options.group.association.image-mode", 3),
    ("options.group.association.tag-format", 1),
    ("options.group.association.tag-width", 10),
    ("options.group.association.facts-field-skip-birth-alternates", True),
    ("options.group.association.facts-field-skip-death-alternates", True),
    ("options.group.association.facts-field-1", "Event:Birth:False"),
    ("options.group.association.facts-field-2", "Event:Baptism:False"),
    ("options.group.association.facts-field-3", "Event:Christening:False"),
    ("options.group.association.facts-field-4", "Event:Death:False"),
    ("options.group.association.facts-field-5", "Event:Burial:False"),
    ("options.group.association.facts-field-6", "Event:Cremation:False"),
    ("options.group.association.facts-field-7", "Event:Probate:False"),
    ("options.group.association.facts-field-8", "None"),
    ("options.group.association.metadata-attribute-1", "None"),
    ("options.group.association.metadata-attribute-2", "None"),
    ("options.group.association.metadata-attribute-3", "None"),
    ("options.group.association.metadata-attribute-4", "None"),
    ("options.group.association.metadata-attribute-5", "None"),
    ("options.group.association.metadata-attribute-6", "None"),
    ("options.group.association.metadata-attribute-7", "None"),
    ("options.group.association.metadata-attribute-8", "None"),
    ######################################################################
    ## Participant Options
    ######################################################################
    ("options.group.participant.event-format", 1),
    ("options.group.participant.show-age", False),
    ("options.group.participant.sex-mode", 1),
    ("options.group.participant.image-mode", 3),
    ("options.group.participant.tag-format", 1),
    ("options.group.participant.tag-width", 10),
    ("options.group.participant.facts-field-skip-birth-alternates", True),
    ("options.group.participant.facts-field-skip-death-alternates", True),
    ("options.group.participant.facts-field-1", "Event:Birth:False"),
    ("options.group.participant.facts-field-2", "Event:Baptism:False"),
    ("options.group.participant.facts-field-3", "Event:Christening:False"),
    ("options.group.participant.facts-field-4", "Event:Death:False"),
    ("options.group.participant.facts-field-5", "Event:Burial:False"),
    ("options.group.participant.facts-field-6", "Event:Cremation:False"),
    ("options.group.participant.facts-field-7", "Event:Probate:False"),
    ("options.group.participant.facts-field-8", "None"),
    ("options.group.participant.metadata-attribute-1", "None"),
    ("options.group.participant.metadata-attribute-2", "None"),
    ("options.group.participant.metadata-attribute-3", "None"),
    ("options.group.participant.metadata-attribute-4", "None"),
    ("options.group.participant.metadata-attribute-5", "None"),
    ("options.group.participant.metadata-attribute-6", "None"),
    ("options.group.participant.metadata-attribute-7", "None"),
    ("options.group.participant.metadata-attribute-8", "None"),
    ######################################################################
    ## Family Options
    ######################################################################
    ("options.group.family.event-format", 1),
    ("options.group.family.show-age", True),
    ("options.group.family.sex-mode", 1),
    ("options.group.family.image-mode", 3),
    ("options.group.family.tag-format", 1),
    ("options.group.family.tag-width", 10),
    ("options.group.family.facts-field-skip-birth-alternates", False),
    ("options.group.family.facts-field-skip-death-alternates", False),
    ("options.group.family.facts-field-1", "Event:Birth:False"),
    ("options.group.family.facts-field-2", "Event:Baptism:False"),
    ("options.group.family.facts-field-3", "Event:Christening:False"),
    ("options.group.family.facts-field-4", "Event:Death:False"),
    ("options.group.family.facts-field-5", "Event:Burial:False"),
    ("options.group.family.facts-field-6", "Event:Cremation:False"),
    ("options.group.family.facts-field-7", "Event:Probate:False"),
    ("options.group.family.facts-field-8", "None"),
    ("options.group.family.metadata-attribute-1", "None"),
    ("options.group.family.metadata-attribute-2", "None"),
    ("options.group.family.metadata-attribute-3", "None"),
    ("options.group.family.metadata-attribute-4", "None"),
    ("options.group.family.metadata-attribute-5", "None"),
    ("options.group.family.metadata-attribute-6", "None"),
    ("options.group.family.metadata-attribute-7", "None"),
    ("options.group.family.metadata-attribute-8", "None"),
    ######################################################################
    ## Event Options
    ######################################################################
    ("options.group.event.event-format", 1),
    ("options.group.event.image-mode", 3),
    ("options.group.event.tag-format", 1),
    ("options.group.event.tag-width", 10),
    ("options.group.event.metadata-attribute-1", "None"),
    ("options.group.event.metadata-attribute-2", "None"),
    ("options.group.event.metadata-attribute-3", "None"),
    ("options.group.event.metadata-attribute-4", "None"),
    ("options.group.event.show-description", True),
    ("options.group.event.show-participants", True),
    ("options.group.event.show-role-always", False),
    ("options.group.event.show-source-count", True),
    ("options.group.event.show-citation-count", True),
    ("options.group.event.show-best-confidence", True),
    ######################################################################
    ## Place Options
    ######################################################################
    ("options.group.place.tag-format", 1),
    ("options.group.place.tag-width", 10),
    ######################################################################
    ## Citation Options
    ######################################################################
    ("options.group.citation.tag-format", 1),
    ("options.group.citation.tag-width", 10),
    ("options.group.citation.image-mode", 0),
    ("options.group.citation.sort-by-date", False),
    ("options.group.citation.include-indirect", True),
    ("options.group.citation.include-parent-family", True),
    ("options.group.citation.include-family", True),
    ("options.group.citation.include-family-indirect", True),
    ("options.group.citation.show-date", True),
    ("options.group.citation.show-publisher", True),
    ("options.group.citation.show-reference-type", True),
    ("options.group.citation.show-reference-description", True),
    ("options.group.citation.show-confidence", True),
    ("options.group.citation.metadata-attribute-1", "None"),
    ("options.group.citation.metadata-attribute-2", "None"),
    ("options.group.citation.metadata-attribute-3", "None"),
    ("options.group.citation.metadata-attribute-4", "None"),
    ######################################################################
    ## Source Options
    ######################################################################
    ("options.group.source.event-format", 1),
    ("options.group.source.image-mode", 3),
    ("options.group.source.tag-format", 1),
    ("options.group.source.tag-width", 10),
    ("options.group.source.metadata-attribute-1", "None"),
    ("options.group.source.metadata-attribute-2", "None"),
    ("options.group.source.metadata-attribute-3", "None"),
    ("options.group.source.metadata-attribute-4", "None"),
    ######################################################################
    ## Repository Options
    ######################################################################
    ("options.group.repository.tag-format", 1),
    ("options.group.repository.tag-width", 10),
    ("options.group.repository.show-call-number", True),
    ("options.group.repository.show-media-type", True),
    ("options.group.repository.show-repository-type", True),
    ######################################################################
    ## Media Options
    ######################################################################    
    ("options.group.media.sort-by-date", False),
    ("options.group.media.group-by-type", False),
    ("options.group.media.filter-non-photos", False),
    ("options.group.media.tag-format", 1),
    ("options.group.media.tag-width", 10),
    ("options.group.media.image-mode", 2),
    ("options.group.media.show-date", True),
    ("options.group.media.metadata-attribute-1", "None"),
    ("options.group.media.metadata-attribute-2", "None"),
    ("options.group.media.metadata-attribute-3", "None"),
    ("options.group.media.metadata-attribute-4", "None"),
    ######################################################################
    ## Note Options
    ######################################################################
    ("options.group.note.preview-mode", True),
    ("options.group.note.preview-lines", 4),
    ("options.group.note.tag-format", 1),
    ("options.group.note.tag-width", 10),

    ######################################################################
    # Timeline Options
    #
    ######################################################################
    ## Person Timeline
    ######################################################################
    ("options.timeline.person.tag-format", 1),
    ("options.timeline.person.tag-width", 10),
    ("options.timeline.person.image-mode", 0),
    ("options.timeline.person.color-scheme", 0),
    ("options.timeline.person.include-media", False),
    ("options.timeline.person.include-names", False),
    ("options.timeline.person.include-addresses", False),
    ("options.timeline.person.include-citations", False),
    ("options.timeline.person.show-description", True),
    ("options.timeline.person.show-participants", True),
    ("options.timeline.person.show-role-always", False),
    ("options.timeline.person.show-source-count", True),
    ("options.timeline.person.show-citation-count", True),
    ("options.timeline.person.show-best-confidence", True),
    ("options.timeline.person.show-age", True),
    ("options.timeline.person.metadata-attribute-1", "None"),
    ("options.timeline.person.metadata-attribute-2", "None"),
    ("options.timeline.person.metadata-attribute-3", "None"),
    ("options.timeline.person.metadata-attribute-4", "None"),
    ("options.timeline.person.show-class-vital", True),
    ("options.timeline.person.show-class-family", True),
    ("options.timeline.person.show-class-religious", True),
    ("options.timeline.person.show-class-vocational", True),
    ("options.timeline.person.show-class-academic", True),
    ("options.timeline.person.show-class-travel", True),
    ("options.timeline.person.show-class-legal", True),
    ("options.timeline.person.show-class-residence", True),
    ("options.timeline.person.show-class-other", True),
    ("options.timeline.person.show-class-custom", True),
    ("options.timeline.person.generations-ancestors", 1),
    ("options.timeline.person.generations-offspring", 1),
    ("options.timeline.person.show-family-father", True),
    ("options.timeline.person.show-family-mother", True),
    ("options.timeline.person.show-family-brother", True),
    ("options.timeline.person.show-family-sister", True),
    ("options.timeline.person.show-family-wife", True),
    ("options.timeline.person.show-family-husband", True),
    ("options.timeline.person.show-family-son", True),
    ("options.timeline.person.show-family-daughter", True),
    ("options.timeline.person.show-family-class-vital", False),
    ("options.timeline.person.show-family-class-family", False),
    ("options.timeline.person.show-family-class-religious", False),
    ("options.timeline.person.show-family-class-vocational", False),
    ("options.timeline.person.show-family-class-academic", False),
    ("options.timeline.person.show-family-class-travel", False),
    ("options.timeline.person.show-family-class-legal", False),
    ("options.timeline.person.show-family-class-residence", False),
    ("options.timeline.person.show-family-class-other", False),
    ("options.timeline.person.show-family-class-custom", False),
    ######################################################################
    ## Family Timeline
    ######################################################################
    ("options.timeline.family.tag-format", 1),
    ("options.timeline.family.tag-width", 10),
    ("options.timeline.family.image-mode", 0),
    ("options.timeline.family.color-scheme", 0),
    ("options.timeline.family.include-media", False),
    ("options.timeline.family.include-names", False),
    ("options.timeline.family.include-addresses", False),
    ("options.timeline.family.include-citations", False),
    ("options.timeline.family.show-description", True),
    ("options.timeline.family.show-participants", True),
    ("options.timeline.family.show-role-always", False),
    ("options.timeline.family.show-source-count", True),
    ("options.timeline.family.show-citation-count", True),
    ("options.timeline.family.show-best-confidence", True),
    ("options.timeline.family.show-age", True),
    ("options.timeline.family.metadata-attribute-1", "None"),
    ("options.timeline.family.metadata-attribute-2", "None"),
    ("options.timeline.family.metadata-attribute-3", "None"),
    ("options.timeline.family.metadata-attribute-4", "None"),
    ("options.timeline.family.show-class-vital", True),
    ("options.timeline.family.show-class-family", True),
    ("options.timeline.family.show-class-religious", True),
    ("options.timeline.family.show-class-vocational", True),
    ("options.timeline.family.show-class-academic", True),
    ("options.timeline.family.show-class-travel", True),
    ("options.timeline.family.show-class-legal", True),
    ("options.timeline.family.show-class-residence", True),
    ("options.timeline.family.show-class-other", True),
    ("options.timeline.family.show-class-custom", True),
    ("options.timeline.family.generations-ancestors", 1),
    ("options.timeline.family.generations-offspring", 1),
    ######################################################################
    ## Place Timeline
    ######################################################################
    ("options.timeline.place.tag-format", 1),
    ("options.timeline.place.tag-width", 10),
    ("options.timeline.place.image-mode", 0),
    ("options.timeline.place.color-scheme", 0),
    ("options.timeline.place.show-description", True),
    ("options.timeline.place.show-participants", True),
    ("options.timeline.place.show-role-always", False),
    ("options.timeline.place.show-source-count", True),
    ("options.timeline.place.show-citation-count", True),
    ("options.timeline.place.show-best-confidence", True),
    ("options.timeline.place.show-age", True),
    ("options.timeline.place.metadata-attribute-1", "None"),
    ("options.timeline.place.metadata-attribute-2", "None"),
    ("options.timeline.place.metadata-attribute-3", "None"),
    ("options.timeline.place.metadata-attribute-4", "None"),
    ("options.timeline.place.show-class-vital", True),
    ("options.timeline.place.show-class-family", True),
    ("options.timeline.place.show-class-religious", True),
    ("options.timeline.place.show-class-vocational", True),
    ("options.timeline.place.show-class-academic", True),
    ("options.timeline.place.show-class-travel", True),
    ("options.timeline.place.show-class-legal", True),
    ("options.timeline.place.show-class-residence", True),
    ("options.timeline.place.show-class-other", True),
    ("options.timeline.place.show-class-custom", True),
    ("options.timeline.place.generations-ancestors", 1),
    ("options.timeline.place.generations-offspring", 1),    
)
