# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2021       Christopher Horn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Profile Options
"""

CONFIGSETTINGS = (
    ######################################################################
    # Active State
    ######################################################################
    ("options.active.last_object", "None"),
    ######################################################################
    # Additional Color Schemes
    #
    ######################################################################
    ## Confidence Color Scheme
    ######################################################################
    ("options.colors.confidence.very-high", ["#bbe68a", "#304918"]),
    ("options.colors.confidence.high", ["#b8cee6", "#1f344a"]),
    ("options.colors.confidence.normal", ["#f3dbb6", "#75507b"]),
    ("options.colors.confidence.low", ["#feccf0", "#62242d"]),
    ("options.colors.confidence.very-low", ["#ffdede", "#5c3636"]),
    ("options.colors.confidence.border-very-high", ["#304918", "#bbe68a"]),
    ("options.colors.confidence.border-high", ["#1f4986", "#171d26"]),
    ("options.colors.confidence.border-normal", ["#8e5801", "#8e5801"]),
    ("options.colors.confidence.border-low", ["#861f69", "#261111"]),
    ("options.colors.confidence.border-very-low", ["#ff7373", "#720b0b"]),
    ######################################################################
    ## Relationship Color Scheme
    ######################################################################
    ("options.colors.relations.active", ["#bbe68e", "#304918"]),
    ("options.colors.relations.spouse", ["#bbe68e", "#304918"]),
    ("options.colors.relations.father", ["#feccf0", "#62242d"]),
    ("options.colors.relations.mother", ["#feccf0", "#62242d"]),
    ("options.colors.relations.brother", ["#f3dbb6", "#75507b"]),
    ("options.colors.relations.sister", ["#f3dbb6", "#75507b"]),
    ("options.colors.relations.son", ["#b8cee6", "#1f344a"]),
    ("options.colors.relations.daughter", ["#b8cee6", "#1f344a"]),
    ("options.colors.relations.none", ["#ffdede", "#5c3636"]),
    ("options.colors.relations.border-active", ["#304918", "#bbe68a"]),
    ("options.colors.relations.border-spouse", ["#304918", "#bbe68a"]),
    ("options.colors.relations.border-father", ["#861f69", "#261111"]),
    ("options.colors.relations.border-mother", ["#861f69", "#261111"]),
    ("options.colors.relations.border-brother", ["#8e5801", "#8e5801"]),
    ("options.colors.relations.border-sister", ["#8e5801", "#8e5801"]),
    ("options.colors.relations.border-son", ["#1f4986", "#171d26"]),
    ("options.colors.relations.border-daughter", ["#1f4986", "#171d26"]),
    ("options.colors.relations.border-none", ["#ff7373", "#720b0b"]),
    ######################################################################
    ## Event Category Color Scheme
    ######################################################################
    ("options.colors.events.vital", ["#bbe68e", "#304918"]),
    ("options.colors.events.family", ["#b8cee6", "#1f344a"]),
    ("options.colors.events.religious", ["#bbe68e", "#304918"]),
    ("options.colors.events.vocational", ["#feccf0", "#62242d"]),
    ("options.colors.events.academic", ["#feccf0", "#62242d"]),
    ("options.colors.events.travel", ["#f3dbb6", "#75507b"]),
    ("options.colors.events.legal", ["#f3dbb6", "#75507b"]),
    ("options.colors.events.residence", ["#f3dbb6", "#75507b"]),
    ("options.colors.events.other", ["#ffdede", "#5c3636"]),
    ("options.colors.events.custom", ["#eeeeee", "#454545"]),
    ("options.colors.events.border-vital", ["#304918", "#bbe68a"]),
    ("options.colors.events.border-family", ["#1f4986", "#171d26"]),
    ("options.colors.events.border-religious", ["#304918", "#bbe68a"]),
    ("options.colors.events.border-vocational", ["#861f69", "#261111"]),
    ("options.colors.events.border-academic", ["#861f69", "#261111"]),
    ("options.colors.events.border-travel", ["#8e5801", "#8e5801"]),
    ("options.colors.events.border-legal", ["#8e5801", "#8e5801"]),
    ("options.colors.events.border-residence", ["#8e5801", "#8e5801"]),
    ("options.colors.events.border-other", ["#ff7373", "#720b0b"]),
    ("options.colors.events.border-custom", ["#cccccc", "#252525"]),
    ######################################################################
    ## Event Role Color Scheme
    ######################################################################
    ("options.colors.roles.primary", ["#bbe68e", "#304918"]),
    ("options.colors.roles.secondary", ["#f3dbb6", "#75507b"]),
    ("options.colors.roles.family", ["#b8cee6", "#1f344a"]),
    ("options.colors.roles.implicit", ["#eeeeee", "#454545"]),
    ("options.colors.roles.unknown", ["#ffdede", "#5c3636"]),
    ("options.colors.roles.border-primary", ["#304918", "#bbe68a"]),
    ("options.colors.roles.border-secondary", ["#8e5801", "#8e5801"]),
    ("options.colors.roles.border-family", ["#1f4986", "#171d26"]),
    ("options.colors.roles.border-implicit", ["#cccccc", "#252525"]),
    ("options.colors.roles.border-unknown", ["#ff7373", "#720b0b"]),
    ######################################################################
    # Global Options
    ######################################################################
    ("options.global.pin-header", True),
    ("options.global.use-color-scheme", True),
    ("options.global.use-smaller-detail-font", True),
    ("options.global.border-width", 2),
    ("options.global.privacy-mode", 1),
    ("options.global.enable-bookmarks", True),
    ("options.global.enable-home", True),
    ("options.global.enable-gramps-ids", True),
    ("options.global.link-citation-title-to-source", True),
    ("options.global.image-page-link", True),
    ("options.global.include-child-notes", True),
    ("options.global.include-note-urls", True),
    ("options.global.create-reciprocal-associations", True),
    ("options.global.sort-tags-by-name", False),
    ("options.global.max-citations-per-group", 100),
    ("options.global.max-references-per-group", 100),
    ("options.global.enable-warnings", True),
    ("options.global.enable-tooltips", True),
    ("options.global.media-bar-display-mode", 0),
    ("options.global.media-bar-sort-by-date", True),
    ("options.global.media-bar-group-by-type", True),
    ("options.global.media-bar-filter-non-photos", False),
    ("options.global.media-bar-page-link", True),
    ("options.global.max-group-windows", 4),
    ("options.global.icons-active-width", 24),
    ("options.global.icons-group-width", 12),
    ("options.global.icons-enable-tags", True),
    ("options.global.icons-enable-indicators", True),
    ("options.global.indicate-names", True),
    ("options.global.indicate-parents", True),
    ("options.global.indicate-spouses", True),
    ("options.global.indicate-children", True),
    ("options.global.indicate-associations", True),
    ("options.global.indicate-events", True),
    ("options.global.indicate-ordinances", True),
    ("options.global.indicate-media", True),
    ("options.global.indicate-attributes", True),
    ("options.global.indicate-addresses", True),
    ("options.global.indicate-citations", True),
    ("options.global.indicate-notes", True),
    ("options.global.indicate-urls", True),
    ######################################################################
    # Page Layout Options
    #
    ######################################################################
    ## Name Page Options
    ######################################################################
    ("options.page.name.layout.tabbed", False),
    ("options.page.name.layout.scrolled", False),
    ("options.page.name.layout.groups", "citation,note,url"),
    ("options.page.name.layout.citation.visible", True),
    ("options.page.name.layout.citation.stacked", False),
    ("options.page.name.layout.citation.hideable", False),
    ("options.page.name.layout.note.visible", True),
    ("options.page.name.layout.note.stacked", False),
    ("options.page.name.layout.note.hideable", False),
    ("options.page.name.layout.url.visible", True),
    ("options.page.name.layout.url.stacked", False),
    ("options.page.name.layout.url.hideable", False),
    ######################################################################
    ## Attribute Page Options
    ######################################################################
    ("options.page.attribute.layout.tabbed", False),
    ("options.page.attribute.layout.scrolled", False),
    ("options.page.attribute.layout.groups", "citation,note,url"),
    ("options.page.attribute.layout.citation.visible", True),
    ("options.page.attribute.layout.citation.stacked", False),
    ("options.page.attribute.layout.citation.hideable", False),
    ("options.page.attribute.layout.note.visible", True),
    ("options.page.attribute.layout.note.stacked", False),
    ("options.page.attribute.layout.note.hideable", False),
    ("options.page.attribute.layout.url.visible", True),
    ("options.page.attribute.layout.url.stacked", False),
    ("options.page.attribute.layout.url.hideable", False),
    ######################################################################
    ## Address Page Options
    ######################################################################
    ("options.page.address.layout.tabbed", False),
    ("options.page.address.layout.scrolled", False),
    ("options.page.address.layout.groups", "citation,note,url"),
    ("options.page.address.layout.citation.visible", True),
    ("options.page.address.layout.citation.stacked", False),
    ("options.page.address.layout.citation.hideable", False),
    ("options.page.address.layout.note.visible", True),
    ("options.page.address.layout.note.stacked", False),
    ("options.page.address.layout.note.hideable", False),
    ("options.page.address.layout.url.visible", True),
    ("options.page.address.layout.url.stacked", False),
    ("options.page.address.layout.url.hideable", False),
    ######################################################################
    ## ChildRef Page Options
    ######################################################################
    ("options.page.childref.layout.tabbed", False),
    ("options.page.childref.layout.scrolled", False),
    ("options.page.childref.layout.groups", "citation,note,url"),
    ("options.page.childref.layout.citation.visible", True),
    ("options.page.childref.layout.citation.stacked", False),
    ("options.page.childref.layout.citation.hideable", False),
    ("options.page.childref.layout.note.visible", True),
    ("options.page.childref.layout.note.stacked", False),
    ("options.page.childref.layout.note.hideable", False),
    ("options.page.childref.layout.url.visible", True),
    ("options.page.childref.layout.url.stacked", False),
    ("options.page.childref.layout.url.hideable", False),
    ######################################################################
    ## PersonRef Page Options
    ######################################################################
    ("options.page.personref.layout.tabbed", False),
    ("options.page.personref.layout.scrolled", False),
    ("options.page.personref.layout.groups", "citation,note,url"),
    ("options.page.personref.layout.citation.visible", True),
    ("options.page.personref.layout.citation.stacked", False),
    ("options.page.personref.layout.citation.hideable", False),
    ("options.page.personref.layout.note.visible", True),
    ("options.page.personref.layout.note.stacked", False),
    ("options.page.personref.layout.note.hideable", False),
    ("options.page.personref.layout.url.visible", True),
    ("options.page.personref.layout.url.stacked", False),
    ("options.page.personref.layout.url.hideable", False),
    ######################################################################
    ## Person Page Options
    ######################################################################
    ("options.page.person.layout.tabbed", False),
    ("options.page.person.layout.scrolled", False),
    (
        "options.page.person.layout.groups",
        "parent,event,timeline,ldsord,spouse,name,attribute,association,"
        "citation,address,url,note,media,reference",
    ),
    ("options.page.person.layout.parent.visible", True),
    ("options.page.person.layout.parent.stacked", False),
    ("options.page.person.layout.parent.hideable", False),
    ("options.page.person.layout.event.visible", True),
    ("options.page.person.layout.event.stacked", False),
    ("options.page.person.layout.event.hideable", False),
    ("options.page.person.layout.timeline.visible", True),
    ("options.page.person.layout.timeline.stacked", False),
    ("options.page.person.layout.timeline.hideable", False),
    ("options.page.person.layout.ldsord.visible", False),
    ("options.page.person.layout.ldsord.stacked", False),
    ("options.page.person.layout.ldsord.hideable", False),
    ("options.page.person.layout.spouse.visible", True),
    ("options.page.person.layout.spouse.stacked", False),
    ("options.page.person.layout.spouse.hideable", False),
    ("options.page.person.layout.name.visible", False),
    ("options.page.person.layout.name.stacked", False),
    ("options.page.person.layout.name.hideable", False),
    ("options.page.person.layout.attribute.visible", False),
    ("options.page.person.layout.attribute.stacked", False),
    ("options.page.person.layout.attribute.hideable", False),
    ("options.page.person.layout.association.visible", False),
    ("options.page.person.layout.association.stacked", False),
    ("options.page.person.layout.association.hideable", False),
    ("options.page.person.layout.citation.visible", True),
    ("options.page.person.layout.citation.stacked", False),
    ("options.page.person.layout.citation.hideable", False),
    ("options.page.person.layout.address.visible", False),
    ("options.page.person.layout.address.stacked", False),
    ("options.page.person.layout.address.hideable", False),
    ("options.page.person.layout.url.visible", False),
    ("options.page.person.layout.url.stacked", False),
    ("options.page.person.layout.url.hideable", False),
    ("options.page.person.layout.note.visible", False),
    ("options.page.person.layout.note.stacked", False),
    ("options.page.person.layout.note.hideable", False),
    ("options.page.person.layout.media.visible", False),
    ("options.page.person.layout.media.stacked", False),
    ("options.page.person.layout.media.hideable", False),
    ("options.page.person.layout.reference.visible", False),
    ("options.page.person.layout.reference.stacked", False),
    ("options.page.person.layout.reference.hideable", False),
    ######################################################################
    ## Family Page Options
    ######################################################################
    ("options.page.family.layout.tabbed", False),
    ("options.page.family.layout.scrolled", False),
    (
        "options.page.family.layout.groups",
        "child,event,timeline,ldsord,attribute,citation,url,note,media,"
        "reference",
    ),
    ("options.page.family.layout.child.visible", True),
    ("options.page.family.layout.child.stacked", False),
    ("options.page.family.layout.child.hideable", False),
    ("options.page.family.layout.event.visible", True),
    ("options.page.family.layout.event.stacked", False),
    ("options.page.family.layout.event.hideable", False),
    ("options.page.family.layout.timeline.visible", True),
    ("options.page.family.layout.timeline.stacked", False),
    ("options.page.family.layout.timeline.hideable", False),
    ("options.page.family.layout.ldsord.visible", False),
    ("options.page.family.layout.ldsord.stacked", False),
    ("options.page.family.layout.ldsord.hideable", False),
    ("options.page.family.layout.attribute.visible", False),
    ("options.page.family.layout.attribute.stacked", False),
    ("options.page.family.layout.attribute.hideable", False),
    ("options.page.family.layout.citation.visible", True),
    ("options.page.family.layout.citation.stacked", False),
    ("options.page.family.layout.citation.hideable", False),
    ("options.page.family.layout.url.visible", False),
    ("options.page.family.layout.url.stacked", False),
    ("options.page.family.layout.url.hideable", False),
    ("options.page.family.layout.note.visible", False),
    ("options.page.family.layout.note.stacked", False),
    ("options.page.family.layout.note.hideable", False),
    ("options.page.family.layout.media.visible", False),
    ("options.page.family.layout.media.stacked", False),
    ("options.page.family.layout.media.hideable", False),
    ("options.page.family.layout.reference.visible", False),
    ("options.page.family.layout.reference.stacked", False),
    ("options.page.family.layout.reference.hideable", False),
    ######################################################################
    ## Event Page Options
    ######################################################################
    ("options.page.event.layout.tabbed", False),
    ("options.page.event.layout.scrolled", False),
    (
        "options.page.event.layout.groups",
        "attribute,people,family,citation,url,note,media,reference",
    ),
    ("options.page.event.layout.attribute.visible", False),
    ("options.page.event.layout.attribute.stacked", False),
    ("options.page.event.layout.attribute.hideable", False),
    ("options.page.event.layout.people.visible", True),
    ("options.page.event.layout.people.stacked", False),
    ("options.page.event.layout.people.hideable", False),
    ("options.page.event.layout.family.visible", True),
    ("options.page.event.layout.family.stacked", False),
    ("options.page.event.layout.family.hideable", False),
    ("options.page.event.layout.citation.visible", True),
    ("options.page.event.layout.citation.stacked", False),
    ("options.page.event.layout.citation.hideable", False),
    ("options.page.event.layout.url.visible", False),
    ("options.page.event.layout.url.stacked", False),
    ("options.page.event.layout.url.hideable", False),
    ("options.page.event.layout.note.visible", False),
    ("options.page.event.layout.note.stacked", False),
    ("options.page.event.layout.note.hideable", False),
    ("options.page.event.layout.media.visible", False),
    ("options.page.event.layout.media.stacked", False),
    ("options.page.event.layout.media.hideable", False),
    ("options.page.event.layout.reference.visible", False),
    ("options.page.event.layout.reference.stacked", False),
    ("options.page.event.layout.reference.hideable", False),
    ######################################################################
    ## EventRef Page Options
    ######################################################################
    ("options.page.eventref.layout.tabbed", False),
    ("options.page.eventref.layout.scrolled", False),
    ("options.page.eventref.layout.groups", "attribute,note,url"),
    ("options.page.eventref.layout.attribute.visible", True),
    ("options.page.eventref.layout.attribute.stacked", False),
    ("options.page.eventref.layout.attribute.hideable", False),
    ("options.page.eventref.layout.note.visible", True),
    ("options.page.eventref.layout.note.stacked", False),
    ("options.page.eventref.layout.note.hideable", False),
    ("options.page.eventref.layout.url.visible", True),
    ("options.page.eventref.layout.url.stacked", False),
    ("options.page.eventref.layout.url.hideable", False),
    ######################################################################
    ## LdsOrd Page Options
    ######################################################################
    ("options.page.ldsord.layout.tabbed", False),
    ("options.page.ldsord.layout.scrolled", False),
    (
        "options.page.ldsord.layout.groups",
        "citation,url,note",
    ),
    ("options.page.ldsord.layout.citation.visible", True),
    ("options.page.ldsord.layout.citation.stacked", False),
    ("options.page.ldsord.layout.citation.hideable", False),
    ("options.page.ldsord.layout.url.visible", True),
    ("options.page.ldsord.layout.url.stacked", True),
    ("options.page.ldsord.layout.url.hideable", False),
    ("options.page.ldsord.layout.note.visible", True),
    ("options.page.ldsord.layout.note.stacked", False),
    ("options.page.ldsord.layout.note.hideable", False),
    ######################################################################
    ## Source Page Options
    ######################################################################
    ("options.page.source.layout.tabbed", False),
    ("options.page.source.layout.scrolled", False),
    (
        "options.page.source.layout.groups",
        "repository,media,citation,people,event,url,note,attribute,reference",
    ),
    ("options.page.source.layout.repository.visible", True),
    ("options.page.source.layout.repository.stacked", True),
    ("options.page.source.layout.repository.hideable", False),
    ("options.page.source.layout.citation.visible", True),
    ("options.page.source.layout.citation.stacked", False),
    ("options.page.source.layout.citation.hideable", False),
    ("options.page.source.layout.attribute.visible", False),
    ("options.page.source.layout.attribute.stacked", False),
    ("options.page.source.layout.attribute.hideable", False),
    ("options.page.source.layout.url.visible", True),
    ("options.page.source.layout.url.stacked", True),
    ("options.page.source.layout.url.hideable", False),
    ("options.page.source.layout.note.visible", True),
    ("options.page.source.layout.note.stacked", False),
    ("options.page.source.layout.note.hideable", False),
    ("options.page.source.layout.people.visible", True),
    ("options.page.source.layout.people.stacked", True),
    ("options.page.source.layout.people.hideable", False),
    ("options.page.source.layout.event.visible", True),
    ("options.page.source.layout.event.stacked", False),
    ("options.page.source.layout.event.hideable", False),
    ("options.page.source.layout.media.visible", True),
    ("options.page.source.layout.media.stacked", False),
    ("options.page.source.layout.media.hideable", False),
    ("options.page.source.layout.reference.visible", False),
    ("options.page.source.layout.reference.stacked", False),
    ("options.page.source.layout.reference.hideable", False),
    ######################################################################
    ## Citation Page Options
    ######################################################################
    ("options.page.citation.layout.tabbed", False),
    ("options.page.citation.layout.scrolled", False),
    (
        "options.page.citation.layout.groups",
        "reference,attribute,url,note,media",
    ),
    ("options.page.citation.layout.reference.visible", True),
    ("options.page.citation.layout.reference.stacked", False),
    ("options.page.citation.layout.reference.hideable", False),
    ("options.page.citation.layout.attribute.visible", False),
    ("options.page.citation.layout.attribute.stacked", False),
    ("options.page.citation.layout.attribute.hideable", False),
    ("options.page.citation.layout.url.visible", True),
    ("options.page.citation.layout.url.stacked", True),
    ("options.page.citation.layout.url.hideable", False),
    ("options.page.citation.layout.note.visible", True),
    ("options.page.citation.layout.note.stacked", False),
    ("options.page.citation.layout.note.hideable", False),
    ("options.page.citation.layout.media.visible", True),
    ("options.page.citation.layout.media.stacked", False),
    ("options.page.citation.layout.media.hideable", False),
    ######################################################################
    ## Repository Page Options
    ######################################################################
    ("options.page.repository.layout.tabbed", False),
    ("options.page.repository.layout.scrolled", False),
    ("options.page.repository.layout.groups", "reference,source,url,note"),
    ("options.page.repository.layout.source.visible", True),
    ("options.page.repository.layout.source.stacked", False),
    ("options.page.repository.layout.source.hideable", False),
    ("options.page.repository.layout.url.visible", True),
    ("options.page.repository.layout.url.stacked", True),
    ("options.page.repository.layout.url.hideable", False),
    ("options.page.repository.layout.note.visible", True),
    ("options.page.repository.layout.note.stacked", False),
    ("options.page.repository.layout.note.hideable", False),
    ("options.page.repository.layout.reference.visible", True),
    ("options.page.repository.layout.reference.stacked", False),
    ("options.page.repository.layout.reference.hideable", False),
    ######################################################################
    ## RepoRef Page Options
    ######################################################################
    ("options.page.reporef.layout.tabbed", False),
    ("options.page.reporef.layout.scrolled", False),
    ("options.page.reporef.layout.groups", "note,url"),
    ("options.page.reporef.layout.note.visible", True),
    ("options.page.reporef.layout.note.stacked", False),
    ("options.page.reporef.layout.note.hideable", False),
    ("options.page.reporef.layout.url.visible", True),
    ("options.page.reporef.layout.url.stacked", False),
    ("options.page.reporef.layout.url.hideable", False),
    ######################################################################
    ## Note Page Options
    ######################################################################
    ("options.page.note.layout.tabbed", False),
    ("options.page.note.layout.scrolled", False),
    ("options.page.note.layout.groups", "reference"),
    ("options.page.note.layout.reference.visible", True),
    ("options.page.note.layout.reference.stacked", False),
    ("options.page.note.layout.reference.hideable", False),
    ######################################################################
    ## Media Page Options
    ######################################################################
    ("options.page.media.layout.tabbed", False),
    ("options.page.media.layout.scrolled", False),
    (
        "options.page.media.layout.groups",
        "reference,citation,attribute,url,note",
    ),
    ("options.page.media.layout.citation.visible", True),
    ("options.page.media.layout.citation.stacked", False),
    ("options.page.media.layout.citation.hideable", False),
    ("options.page.media.layout.attribute.visible", False),
    ("options.page.media.layout.attribute.stacked", False),
    ("options.page.media.layout.attribute.hideable", False),
    ("options.page.media.layout.url.visible", True),
    ("options.page.media.layout.url.stacked", True),
    ("options.page.media.layout.url.hideable", False),
    ("options.page.media.layout.note.visible", True),
    ("options.page.media.layout.note.stacked", False),
    ("options.page.media.layout.note.hideable", False),
    ("options.page.media.layout.reference.visible", True),
    ("options.page.media.layout.reference.stacked", False),
    ("options.page.media.layout.reference.hideable", False),
    ######################################################################
    ## MediaRef Page Options
    ######################################################################
    ("options.page.mediaref.layout.tabbed", False),
    ("options.page.mediaref.layout.scrolled", False),
    ("options.page.mediaref.layout.groups", "attribute,citation,note,url"),
    ("options.page.mediaref.layout.attribute.visible", True),
    ("options.page.mediaref.layout.attribute.stacked", False),
    ("options.page.mediaref.layout.attribute.hideable", False),
    ("options.page.mediaref.layout.citation.visible", True),
    ("options.page.mediaref.layout.citation.stacked", False),
    ("options.page.mediaref.layout.citation.hideable", False),
    ("options.page.mediaref.layout.note.visible", True),
    ("options.page.mediaref.layout.note.stacked", False),
    ("options.page.mediaref.layout.note.hideable", False),
    ("options.page.mediaref.layout.url.visible", True),
    ("options.page.mediaref.layout.url.stacked", False),
    ("options.page.mediaref.layout.url.hideable", False),
    ######################################################################
    ## Place Page Options
    ######################################################################
    ("options.page.place.layout.tabbed", False),
    ("options.page.place.layout.scrolled", False),
    ("options.page.place.layout.groups", "reference,media,citation,url,note"),
    ("options.page.place.layout.citation.visible", True),
    ("options.page.place.layout.citation.stacked", False),
    ("options.page.place.layout.citation.hideable", False),
    ("options.page.place.layout.url.visible", True),
    ("options.page.place.layout.url.stacked", True),
    ("options.page.place.layout.url.hideable", False),
    ("options.page.place.layout.note.visible", True),
    ("options.page.place.layout.note.stacked", False),
    ("options.page.place.layout.note.hideable", False),
    ("options.page.place.layout.media.visible", True),
    ("options.page.place.layout.media.stacked", False),
    ("options.page.place.layout.media.hideable", False),
    ("options.page.place.layout.reference.visible", True),
    ("options.page.place.layout.reference.stacked", False),
    ("options.page.place.layout.reference.hideable", False),
    ######################################################################
    ## Tag Page Options
    ######################################################################
    ("options.page.tag.layout.tabbed", False),
    ("options.page.tag.layout.scrolled", False),
    (
        "options.page.tag.layout.groups",
        "person,family,event,place,citation,source,repository,note,media",
    ),
    ("options.page.tag.layout.person.visible", True),
    ("options.page.tag.layout.person.stacked", True),
    ("options.page.tag.layout.person.hideable", False),
    ("options.page.tag.layout.family.visible", True),
    ("options.page.tag.layout.family.stacked", False),
    ("options.page.tag.layout.family.hideable", False),
    ("options.page.tag.layout.event.visible", True),
    ("options.page.tag.layout.event.stacked", True),
    ("options.page.tag.layout.event.hideable", False),
    ("options.page.tag.layout.place.visible", True),
    ("options.page.tag.layout.place.stacked", False),
    ("options.page.tag.layout.place.hideable", False),
    ("options.page.tag.layout.citation.visible", True),
    ("options.page.tag.layout.citation.stacked", True),
    ("options.page.tag.layout.citation.hideable", False),
    ("options.page.tag.layout.source.visible", True),
    ("options.page.tag.layout.source.stacked", True),
    ("options.page.tag.layout.source.hideable", False),
    ("options.page.tag.layout.repository.visible", True),
    ("options.page.tag.layout.repository.stacked", False),
    ("options.page.tag.layout.repository.hideable", False),
    ("options.page.tag.layout.note.visible", True),
    ("options.page.tag.layout.note.stacked", True),
    ("options.page.tag.layout.note.hideable", False),
    ("options.page.tag.layout.media.visible", True),
    ("options.page.tag.layout.media.stacked", False),
    ("options.page.tag.layout.media.hideable", False),
    ######################################################################
    # Frame Level Options
    # These apply when the frame is in the page header and not a group
    #
    ######################################################################
    ## Person Options
    ######################################################################
    ("options.active.person.event-format", 1),
    ("options.active.person.show-age", True),
    ("options.active.person.sex-mode", 1),
    ("options.active.person.image-mode", 3),
    ("options.active.person.facts-field-skip-birth-alternates", False),
    ("options.active.person.facts-field-skip-death-alternates", False),
    ("options.active.person.facts-field-1", "Event:Birth:False"),
    ("options.active.person.facts-field-2", "Event:Baptism:False"),
    ("options.active.person.facts-field-3", "Event:Christening:False"),
    ("options.active.person.facts-field-4", "Event:Death:False"),
    ("options.active.person.facts-field-5", "Event:Burial:False"),
    ("options.active.person.facts-field-6", "Event:Cremation:False"),
    ("options.active.person.facts-field-7", "Event:Probate:False"),
    ("options.active.person.facts-field-8", "None"),
    ("options.active.person.extra-field-skip-birth-alternates", False),
    ("options.active.person.extra-field-skip-death-alternates", False),
    ("options.active.person.extra-field-1", "None"),
    ("options.active.person.extra-field-2", "None"),
    ("options.active.person.extra-field-3", "None"),
    ("options.active.person.extra-field-4", "None"),
    ("options.active.person.extra-field-5", "None"),
    ("options.active.person.extra-field-6", "None"),
    ("options.active.person.extra-field-7", "None"),
    ("options.active.person.extra-field-8", "None"),
    ("options.active.person.attributes-field-show-labels", False),
    ("options.active.person.attributes-field-1", "None"),
    ("options.active.person.attributes-field-2", "None"),
    ("options.active.person.attributes-field-3", "None"),
    ("options.active.person.attributes-field-4", "None"),
    ("options.active.person.attributes-field-5", "None"),
    ("options.active.person.attributes-field-6", "None"),
    ("options.active.person.attributes-field-7", "None"),
    ("options.active.person.attributes-field-8", "None"),
    ######################################################################
    ## Parent Options
    ######################################################################
    ("options.active.parent.event-format", 1),
    ("options.active.parent.show-age", False),
    ("options.active.parent.sex-mode", 1),
    ("options.active.parent.image-mode", 3),
    ("options.active.parent.show-matrilineal", False),
    ("options.active.parent.expand-children", True),
    ("options.active.parent.show-divorce", True),
    ("options.active.parent.facts-field-skip-birth-alternates", True),
    ("options.active.parent.facts-field-skip-death-alternates", True),
    ("options.active.parent.facts-field-1", "Event:Birth:False"),
    ("options.active.parent.facts-field-2", "Event:Baptism:False"),
    ("options.active.parent.facts-field-3", "Event:Christening:False"),
    ("options.active.parent.facts-field-4", "Event:Death:False"),
    ("options.active.parent.facts-field-5", "Event:Burial:False"),
    ("options.active.parent.facts-field-6", "Event:Cremation:False"),
    ("options.active.parent.facts-field-7", "Event:Probate:False"),
    ("options.active.parent.facts-field-8", "None"),
    ("options.active.parent.attributes-field-show-labels", False),
    ("options.active.parent.attributes-field-1", "None"),
    ("options.active.parent.attributes-field-2", "None"),
    ("options.active.parent.attributes-field-3", "None"),
    ("options.active.parent.attributes-field-4", "None"),
    ("options.active.parent.attributes-field-5", "None"),
    ("options.active.parent.attributes-field-6", "None"),
    ("options.active.parent.attributes-field-7", "None"),
    ("options.active.parent.attributes-field-8", "None"),
    ######################################################################
    ## Spouse Options
    ######################################################################
    ("options.active.spouse.event-format", 1),
    ("options.active.spouse.show-age", False),
    ("options.active.spouse.sex-mode", 1),
    ("options.active.spouse.image-mode", 3),
    ("options.active.spouse.expand-children", True),
    ("options.active.spouse.show-spouse-only", True),
    ("options.active.spouse.show-divorce", True),
    ("options.active.spouse.facts-field-skip-birth-alternates", True),
    ("options.active.spouse.facts-field-skip-death-alternates", True),
    ("options.active.spouse.facts-field-1", "Event:Birth:False"),
    ("options.active.spouse.facts-field-2", "Event:Baptism:False"),
    ("options.active.spouse.facts-field-3", "Event:Christening:False"),
    ("options.active.spouse.facts-field-4", "Event:Death:False"),
    ("options.active.spouse.facts-field-5", "Event:Burial:False"),
    ("options.active.spouse.facts-field-6", "Event:Cremation:False"),
    ("options.active.spouse.facts-field-7", "Event:Probate:False"),
    ("options.active.spouse.facts-field-8", "None"),
    ("options.active.spouse.attributes-field-show-labels", False),
    ("options.active.spouse.attributes-field-1", "None"),
    ("options.active.spouse.attributes-field-2", "None"),
    ("options.active.spouse.attributes-field-3", "None"),
    ("options.active.spouse.attributes-field-4", "None"),
    ("options.active.spouse.attributes-field-5", "None"),
    ("options.active.spouse.attributes-field-6", "None"),
    ("options.active.spouse.attributes-field-7", "None"),
    ("options.active.spouse.attributes-field-8", "None"),
    ######################################################################
    ## Association Options
    ######################################################################
    ("options.active.association.event-format", 1),
    ("options.active.association.show-age", False),
    ("options.active.association.sex-mode", 1),
    ("options.active.association.image-mode", 3),
    ("options.active.association.facts-field-skip-birth-alternates", True),
    ("options.active.association.facts-field-skip-death-alternates", True),
    ("options.active.association.facts-field-1", "Event:Birth:False"),
    ("options.active.association.facts-field-2", "Event:Baptism:False"),
    ("options.active.association.facts-field-3", "Event:Christening:False"),
    ("options.active.association.facts-field-4", "Event:Death:False"),
    ("options.active.association.facts-field-5", "Event:Burial:False"),
    ("options.active.association.facts-field-6", "Event:Cremation:False"),
    ("options.active.association.facts-field-7", "Event:Probate:False"),
    ("options.active.association.facts-field-8", "None"),
    ("options.active.association.attributes-field-show-labels", False),
    ("options.active.association.attributes-field-1", "None"),
    ("options.active.association.attributes-field-2", "None"),
    ("options.active.association.attributes-field-3", "None"),
    ("options.active.association.attributes-field-4", "None"),
    ("options.active.association.attributes-field-5", "None"),
    ("options.active.association.attributes-field-6", "None"),
    ("options.active.association.attributes-field-7", "None"),
    ("options.active.association.attributes-field-8", "None"),
    ######################################################################
    ## Participant Options
    ######################################################################
    ("options.active.participant.event-format", 1),
    ("options.active.participant.show-age", False),
    ("options.active.participant.sex-mode", 1),
    ("options.active.participant.image-mode", 3),
    ("options.active.participant.facts-field-skip-birth-alternates", True),
    ("options.active.participant.facts-field-skip-death-alternates", True),
    ("options.active.participant.facts-field-1", "Event:Birth:False"),
    ("options.active.participant.facts-field-2", "Event:Baptism:False"),
    ("options.active.participant.facts-field-3", "Event:Christening:False"),
    ("options.active.participant.facts-field-4", "Event:Death:False"),
    ("options.active.participant.facts-field-5", "Event:Burial:False"),
    ("options.active.participant.facts-field-6", "Event:Cremation:False"),
    ("options.active.participant.facts-field-7", "Event:Probate:False"),
    ("options.active.participant.facts-field-8", "None"),
    ("options.active.participant.attributes-field-show-labels", False),
    ("options.active.participant.attributes-field-1", "None"),
    ("options.active.participant.attributes-field-2", "None"),
    ("options.active.participant.attributes-field-3", "None"),
    ("options.active.participant.attributes-field-4", "None"),
    ("options.active.participant.attributes-field-5", "None"),
    ("options.active.participant.attributes-field-6", "None"),
    ("options.active.participant.attributes-field-7", "None"),
    ("options.active.participant.attributes-field-8", "None"),
    ######################################################################
    ## Family Options
    ######################################################################
    ("options.active.family.event-format", 1),
    ("options.active.family.image-mode", 3),
    ("options.active.family.show-years", True),
    ("options.active.family.show-matrilineal", False),
    ("options.active.family.show-relationship", True),
    ("options.active.family.facts-field-skip-marriage-alternates", False),
    ("options.active.family.facts-field-skip-divorce-alternates", False),
    ("options.active.family.facts-field-1", "Event:Marriage Banns:False"),
    ("options.active.family.facts-field-2", "Event:Marriage License:False"),
    ("options.active.family.facts-field-3", "Event:Marriage Contract:False"),
    ("options.active.family.facts-field-4", "Event:Marriage Settlement:False"),
    ("options.active.family.facts-field-5", "Event:Marriage:False"),
    ("options.active.family.facts-field-6", "Event:Divorce Filing:False"),
    ("options.active.family.facts-field-7", "Event:Divorce:False"),
    ("options.active.family.facts-field-8", "Event:Annulment:False"),
    ("options.active.family.extra-field-skip-marriage-alternates", False),
    ("options.active.family.extra-field-skip-divorce-alternates", False),
    ("options.active.family.extra-field-1", "None"),
    ("options.active.family.extra-field-2", "None"),
    ("options.active.family.extra-field-3", "None"),
    ("options.active.family.extra-field-4", "None"),
    ("options.active.family.extra-field-5", "None"),
    ("options.active.family.extra-field-6", "None"),
    ("options.active.family.extra-field-7", "None"),
    ("options.active.family.extra-field-8", "None"),
    ("options.active.family.attributes-field-show-labels", False),
    ("options.active.family.attributes-field-1", "None"),
    ("options.active.family.attributes-field-2", "None"),
    ("options.active.family.attributes-field-3", "None"),
    ("options.active.family.attributes-field-4", "None"),
    ("options.active.family.attributes-field-5", "None"),
    ("options.active.family.attributes-field-6", "None"),
    ("options.active.family.attributes-field-7", "None"),
    ("options.active.family.attributes-field-8", "None"),
    ######################################################################
    ## Event Options
    ######################################################################
    ("options.active.event.event-format", 1),
    ("options.active.event.image-mode", 3),
    ("options.active.event.color-scheme", 1),
    ("options.active.event.attributes-field-show-labels", False),
    ("options.active.event.attributes-field-1", "None"),
    ("options.active.event.attributes-field-2", "None"),
    ("options.active.event.attributes-field-3", "None"),
    ("options.active.event.attributes-field-4", "None"),
    ("options.active.event.show-description", True),
    ("options.active.event.show-participants", True),
    ("options.active.event.show-role-always", False),
    ("options.active.event.show-source-count", True),
    ("options.active.event.show-citation-count", True),
    ("options.active.event.show-best-confidence", True),
    ######################################################################
    ## Place Options
    ######################################################################
    ######################################################################
    ## Citation Options
    ######################################################################
    ("options.active.citation.image-mode", 3),
    ("options.active.citation.sort-by-date", False),
    ("options.active.citation.include-indirect", True),
    ("options.active.citation.include-parent-family", True),
    ("options.active.citation.include-family", True),
    ("options.active.citation.include-family-indirect", True),
    ("options.active.citation.show-date", True),
    ("options.active.citation.show-publisher", True),
    ("options.active.citation.show-reference-type", True),
    ("options.active.citation.show-reference-description", True),
    ("options.active.citation.show-confidence", True),
    ("options.active.citation.attributes-field-show-labels", False),
    ("options.active.citation.attributes-field-1", "None"),
    ("options.active.citation.attributes-field-2", "None"),
    ("options.active.citation.attributes-field-3", "None"),
    ("options.active.citation.attributes-field-4", "None"),
    ######################################################################
    ## Source Options
    ######################################################################
    ("options.active.source.event-format", 1),
    ("options.active.source.image-mode", 3),
    ("options.active.source.attributes-field-show-labels", False),
    ("options.active.source.attributes-field-1", "None"),
    ("options.active.source.attributes-field-2", "None"),
    ("options.active.source.attributes-field-3", "None"),
    ("options.active.source.attributes-field-4", "None"),
    ######################################################################
    ## Repository Options
    ######################################################################
    ("options.active.repository.show-call-number", True),
    ("options.active.repository.show-media-type", True),
    ("options.active.repository.show-repository-type", True),
    ######################################################################
    ## Media Options
    ######################################################################
    ("options.active.media.image-mode", 3),
    ("options.active.media.show-date", True),
    ("options.active.media.show-path", True),
    ("options.active.media.show-mime-type", True),
    ("options.active.media.attributes-field-show-labels", False),
    ("options.active.media.attributes-field-1", "None"),
    ("options.active.media.attributes-field-2", "None"),
    ("options.active.media.attributes-field-3", "None"),
    ("options.active.media.attributes-field-4", "None"),
    ######################################################################
    ## Note Options
    ######################################################################
    ("options.active.note.text-on-top", False),
    ("options.active.note.preview-mode", False),
    ("options.active.note.preview-lines", 3),
    ######################################################################
    # Group Level Options
    # These apply when the frame is in a group and not the page header
    #
    ######################################################################
    ## Person Options
    ######################################################################
    ("options.group.person.event-format", 1),
    ("options.group.person.show-age", True),
    ("options.group.person.sex-mode", 1),
    ("options.group.person.image-mode", 1),
    ("options.group.person.facts-field-skip-birth-alternates", False),
    ("options.group.person.facts-field-skip-death-alternates", False),
    ("options.group.person.facts-field-1", "Event:Birth:False"),
    ("options.group.person.facts-field-2", "Event:Baptism:False"),
    ("options.group.person.facts-field-3", "Event:Christening:False"),
    ("options.group.person.facts-field-4", "Event:Death:False"),
    ("options.group.person.facts-field-5", "Event:Burial:False"),
    ("options.group.person.facts-field-6", "Event:Cremation:False"),
    ("options.group.person.facts-field-7", "Event:Probate:False"),
    ("options.group.person.facts-field-8", "None"),
    ("options.group.person.extra-field-skip-birth-alternates", False),
    ("options.group.person.extra-field-skip-death-alternates", False),
    ("options.group.person.extra-field-1", "None"),
    ("options.group.person.extra-field-2", "None"),
    ("options.group.person.extra-field-3", "None"),
    ("options.group.person.extra-field-4", "None"),
    ("options.group.person.extra-field-5", "None"),
    ("options.group.person.extra-field-6", "None"),
    ("options.group.person.extra-field-7", "None"),
    ("options.group.person.extra-field-8", "None"),
    ("options.group.person.attributes-field-show-labels", False),
    ("options.group.person.attributes-field-1", "None"),
    ("options.group.person.attributes-field-2", "None"),
    ("options.group.person.attributes-field-3", "None"),
    ("options.group.person.attributes-field-4", "None"),
    ("options.group.person.attributes-field-5", "None"),
    ("options.group.person.attributes-field-6", "None"),
    ("options.group.person.attributes-field-7", "None"),
    ("options.group.person.attributes-field-8", "None"),
    ######################################################################
    ## Parent Options
    ######################################################################
    ("options.group.parent.event-format", 1),
    ("options.group.parent.show-age", False),
    ("options.group.parent.sex-mode", 1),
    ("options.group.parent.image-mode", 1),
    ("options.group.parent.show-matrilineal", False),
    ("options.group.parent.expand-children", True),
    ("options.group.parent.show-divorce", True),
    ("options.group.parent.facts-field-skip-birth-alternates", True),
    ("options.group.parent.facts-field-skip-death-alternates", True),
    ("options.group.parent.facts-field-1", "Event:Birth:False"),
    ("options.group.parent.facts-field-2", "Event:Baptism:False"),
    ("options.group.parent.facts-field-3", "Event:Christening:False"),
    ("options.group.parent.facts-field-4", "Event:Death:False"),
    ("options.group.parent.facts-field-5", "Event:Burial:False"),
    ("options.group.parent.facts-field-6", "Event:Cremation:False"),
    ("options.group.parent.facts-field-7", "Event:Probate:False"),
    ("options.group.parent.facts-field-8", "None"),
    ("options.group.parent.attributes-field-show-labels", False),
    ("options.group.parent.attributes-field-1", "None"),
    ("options.group.parent.attributes-field-2", "None"),
    ("options.group.parent.attributes-field-3", "None"),
    ("options.group.parent.attributes-field-4", "None"),
    ("options.group.parent.attributes-field-5", "None"),
    ("options.group.parent.attributes-field-6", "None"),
    ("options.group.parent.attributes-field-7", "None"),
    ("options.group.parent.attributes-field-8", "None"),
    ######################################################################
    ## Sibling Options
    ######################################################################
    ("options.group.sibling.event-format", 1),
    ("options.group.sibling.show-age", False),
    ("options.group.sibling.sex-mode", 1),
    ("options.group.sibling.image-mode", 1),
    ("options.group.sibling.number-children", True),
    ("options.group.sibling.reference-mode", 1),
    ("options.group.sibling.facts-field-skip-birth-alternates", True),
    ("options.group.sibling.facts-field-skip-death-alternates", True),
    ("options.group.sibling.facts-field-1", "Event:Birth:False"),
    ("options.group.sibling.facts-field-2", "Event:Baptism:False"),
    ("options.group.sibling.facts-field-3", "Event:Christening:False"),
    ("options.group.sibling.facts-field-4", "Event:Death:False"),
    ("options.group.sibling.facts-field-5", "Event:Burial:False"),
    ("options.group.sibling.facts-field-6", "Event:Cremation:False"),
    ("options.group.sibling.facts-field-7", "Event:Probate:False"),
    ("options.group.sibling.facts-field-8", "None"),
    ("options.group.sibling.attributes-field-show-labels", False),
    ("options.group.sibling.attributes-field-1", "None"),
    ("options.group.sibling.attributes-field-2", "None"),
    ("options.group.sibling.attributes-field-3", "None"),
    ("options.group.sibling.attributes-field-4", "None"),
    ("options.group.sibling.attributes-field-5", "None"),
    ("options.group.sibling.attributes-field-6", "None"),
    ("options.group.sibling.attributes-field-7", "None"),
    ("options.group.sibling.attributes-field-8", "None"),
    ######################################################################
    ## Spouse Options
    ######################################################################
    ("options.group.spouse.event-format", 1),
    ("options.group.spouse.show-age", False),
    ("options.group.spouse.sex-mode", 1),
    ("options.group.spouse.image-mode", 1),
    ("options.group.spouse.expand-children", True),
    ("options.group.spouse.show-spouse-only", True),
    ("options.group.spouse.show-divorce", True),
    ("options.group.spouse.facts-field-skip-birth-alternates", True),
    ("options.group.spouse.facts-field-skip-death-alternates", True),
    ("options.group.spouse.facts-field-1", "Event:Birth:False"),
    ("options.group.spouse.facts-field-2", "Event:Baptism:False"),
    ("options.group.spouse.facts-field-3", "Event:Christening:False"),
    ("options.group.spouse.facts-field-4", "Event:Death:False"),
    ("options.group.spouse.facts-field-5", "Event:Burial:False"),
    ("options.group.spouse.facts-field-6", "Event:Cremation:False"),
    ("options.group.spouse.facts-field-7", "Event:Probate:False"),
    ("options.group.spouse.facts-field-8", "None"),
    ("options.group.spouse.attributes-field-show-labels", False),
    ("options.group.spouse.attributes-field-1", "None"),
    ("options.group.spouse.attributes-field-2", "None"),
    ("options.group.spouse.attributes-field-3", "None"),
    ("options.group.spouse.attributes-field-4", "None"),
    ("options.group.spouse.attributes-field-5", "None"),
    ("options.group.spouse.attributes-field-6", "None"),
    ("options.group.spouse.attributes-field-7", "None"),
    ("options.group.spouse.attributes-field-8", "None"),
    ######################################################################
    ## Child Options
    ######################################################################
    ("options.group.child.event-format", 1),
    ("options.group.child.show-age", False),
    ("options.group.child.sex-mode", 1),
    ("options.group.child.image-mode", 1),
    ("options.group.child.number-children", True),
    ("options.group.child.reference-mode", 1),
    ("options.group.child.facts-field-skip-birth-alternates", True),
    ("options.group.child.facts-field-skip-death-alternates", True),
    ("options.group.child.facts-field-1", "Event:Birth:False"),
    ("options.group.child.facts-field-2", "Event:Baptism:False"),
    ("options.group.child.facts-field-3", "Event:Christening:False"),
    ("options.group.child.facts-field-4", "Event:Death:False"),
    ("options.group.child.facts-field-5", "Event:Burial:False"),
    ("options.group.child.facts-field-6", "Event:Cremation:False"),
    ("options.group.child.facts-field-7", "Event:Probate:False"),
    ("options.group.child.facts-field-8", "None"),
    ("options.group.child.attributes-field-show-labels", False),
    ("options.group.child.attributes-field-1", "None"),
    ("options.group.child.attributes-field-2", "None"),
    ("options.group.child.attributes-field-3", "None"),
    ("options.group.child.attributes-field-4", "None"),
    ("options.group.child.attributes-field-5", "None"),
    ("options.group.child.attributes-field-6", "None"),
    ("options.group.child.attributes-field-7", "None"),
    ("options.group.child.attributes-field-8", "None"),
    ######################################################################
    ## Association Options
    ######################################################################
    ("options.group.association.event-format", 1),
    ("options.group.association.show-age", False),
    ("options.group.association.sex-mode", 1),
    ("options.group.association.image-mode", 1),
    ("options.group.association.reference-mode", 1),
    ("options.group.association.facts-field-skip-birth-alternates", True),
    ("options.group.association.facts-field-skip-death-alternates", True),
    ("options.group.association.facts-field-1", "Event:Birth:False"),
    ("options.group.association.facts-field-2", "Event:Baptism:False"),
    ("options.group.association.facts-field-3", "Event:Christening:False"),
    ("options.group.association.facts-field-4", "Event:Death:False"),
    ("options.group.association.facts-field-5", "Event:Burial:False"),
    ("options.group.association.facts-field-6", "Event:Cremation:False"),
    ("options.group.association.facts-field-7", "Event:Probate:False"),
    ("options.group.association.facts-field-8", "None"),
    ("options.group.association.attributes-field-show-labels", False),
    ("options.group.association.attributes-field-1", "None"),
    ("options.group.association.attributes-field-2", "None"),
    ("options.group.association.attributes-field-3", "None"),
    ("options.group.association.attributes-field-4", "None"),
    ("options.group.association.attributes-field-5", "None"),
    ("options.group.association.attributes-field-6", "None"),
    ("options.group.association.attributes-field-7", "None"),
    ("options.group.association.attributes-field-8", "None"),
    ######################################################################
    ## Participant Options
    ######################################################################
    ("options.group.participant.event-format", 1),
    ("options.group.participant.show-age", False),
    ("options.group.participant.sex-mode", 1),
    ("options.group.participant.image-mode", 1),
    ("options.group.participant.facts-field-skip-birth-alternates", True),
    ("options.group.participant.facts-field-skip-death-alternates", True),
    ("options.group.participant.facts-field-1", "Event:Birth:False"),
    ("options.group.participant.facts-field-2", "Event:Baptism:False"),
    ("options.group.participant.facts-field-3", "Event:Christening:False"),
    ("options.group.participant.facts-field-4", "Event:Death:False"),
    ("options.group.participant.facts-field-5", "Event:Burial:False"),
    ("options.group.participant.facts-field-6", "Event:Cremation:False"),
    ("options.group.participant.facts-field-7", "Event:Probate:False"),
    ("options.group.participant.facts-field-8", "None"),
    ("options.group.participant.attributes-field-show-labels", False),
    ("options.group.participant.attributes-field-1", "None"),
    ("options.group.participant.attributes-field-2", "None"),
    ("options.group.participant.attributes-field-3", "None"),
    ("options.group.participant.attributes-field-4", "None"),
    ("options.group.participant.attributes-field-5", "None"),
    ("options.group.participant.attributes-field-6", "None"),
    ("options.group.participant.attributes-field-7", "None"),
    ("options.group.participant.attributes-field-8", "None"),
    ######################################################################
    ## Name Options
    ######################################################################
    ("options.group.name.show-age", False),
    ######################################################################
    ## Address Options
    ######################################################################
    ("options.group.address.show-age", False),
    ######################################################################
    ## Family Options
    ######################################################################
    ("options.group.family.event-format", 1),
    ("options.group.family.image-mode", 1),
    ("options.group.family.show-years", True),
    ("options.group.family.show-matrilineal", False),
    ("options.group.family.show-spouse-only", True),
    ("options.group.family.show-relationship", True),
    ("options.group.family.facts-field-skip-marriage-alternates", False),
    ("options.group.family.facts-field-skip-divorce-alternates", False),
    ("options.group.family.facts-field-1", "Event:Marriage Banns:False"),
    ("options.group.family.facts-field-2", "Event:Marriage License:False"),
    ("options.group.family.facts-field-3", "Event:Marriage Contract:False"),
    ("options.group.family.facts-field-4", "Event:Marriage Settlement:False"),
    ("options.group.family.facts-field-5", "Event:Marriage:False"),
    ("options.group.family.facts-field-6", "Event:Divorce Filing:False"),
    ("options.group.family.facts-field-7", "Event:Divorce:False"),
    ("options.group.family.facts-field-8", "Event:Annulment:False"),
    ("options.group.family.attributes-field-show-labels", False),
    ("options.group.family.attributes-field-1", "None"),
    ("options.group.family.attributes-field-2", "None"),
    ("options.group.family.attributes-field-3", "None"),
    ("options.group.family.attributes-field-4", "None"),
    ("options.group.family.attributes-field-5", "None"),
    ("options.group.family.attributes-field-6", "None"),
    ("options.group.family.attributes-field-7", "None"),
    ("options.group.family.attributes-field-8", "None"),
    ######################################################################
    ## Event Options
    ######################################################################
    ("options.group.event.event-format", 1),
    ("options.group.event.show-age", False),
    ("options.group.event.image-mode", 0),
    ("options.group.event.reference-mode", 1),
    ("options.group.event.color-scheme", 1),
    ("options.group.event.attributes-field-show-labels", False),
    ("options.group.event.attributes-field-1", "None"),
    ("options.group.event.attributes-field-2", "None"),
    ("options.group.event.attributes-field-3", "None"),
    ("options.group.event.attributes-field-4", "None"),
    ("options.group.event.show-description", True),
    ("options.group.event.show-participants", True),
    ("options.group.event.show-role-always", False),
    ("options.group.event.show-source-count", True),
    ("options.group.event.show-citation-count", True),
    ("options.group.event.show-best-confidence", True),
    ######################################################################
    ## Ordinance Options
    ######################################################################
    ("options.group.ldsord.show-age", False),
    ######################################################################
    ## Place Options
    ######################################################################
    ("options.group.place.image-mode", 0),
    ######################################################################
    ## Citation Options
    ######################################################################
    ("options.group.citation.image-mode", 0),
    ("options.group.citation.show-age", False),
    ("options.group.citation.sort-by-date", False),
    ("options.group.citation.include-indirect", True),
    ("options.group.citation.include-parent-family", True),
    ("options.group.citation.include-family", True),
    ("options.group.citation.include-family-indirect", True),
    ("options.group.citation.show-date", True),
    ("options.group.citation.show-publisher", True),
    ("options.group.citation.show-reference-type", True),
    ("options.group.citation.show-reference-description", True),
    ("options.group.citation.show-confidence", True),
    ("options.group.citation.attributes-field-show-labels", False),
    ("options.group.citation.attributes-field-1", "None"),
    ("options.group.citation.attributes-field-2", "None"),
    ("options.group.citation.attributes-field-3", "None"),
    ("options.group.citation.attributes-field-4", "None"),
    ######################################################################
    ## Source Options
    ######################################################################
    ("options.group.source.event-format", 1),
    ("options.group.source.image-mode", 0),
    ("options.group.source.attributes-field-show-labels", False),
    ("options.group.source.attributes-field-1", "None"),
    ("options.group.source.attributes-field-2", "None"),
    ("options.group.source.attributes-field-3", "None"),
    ("options.group.source.attributes-field-4", "None"),
    ######################################################################
    ## Repository Options
    ######################################################################
    ("options.group.repository.reference-mode", 1),
    ("options.group.repository.show-call-number", True),
    ("options.group.repository.show-media-type", True),
    ("options.group.repository.show-repository-type", True),
    ######################################################################
    ## Media Options
    ######################################################################
    ("options.group.media.show-age", False),
    ("options.group.media.sort-by-date", False),
    ("options.group.media.group-by-type", False),
    ("options.group.media.filter-non-photos", False),
    ("options.group.media.image-mode", 2),
    ("options.group.media.reference-mode", 1),
    ("options.group.media.show-date", True),
    ("options.group.media.show-path", True),
    ("options.group.media.show-mime-type", True),
    ("options.group.media.attributes-field-show-labels", False),
    ("options.group.media.attributes-field-1", "None"),
    ("options.group.media.attributes-field-2", "None"),
    ("options.group.media.attributes-field-3", "None"),
    ("options.group.media.attributes-field-4", "None"),
    ######################################################################
    ## Note Options
    ######################################################################
    ("options.group.note.text-on-top", False),
    ("options.group.note.preview-mode", True),
    ("options.group.note.preview-lines", 3),
    ######################################################################
    # Timeline Options
    #
    ######################################################################
    ## Person Timeline
    ######################################################################
    ("options.timeline.person.image-mode", 0),
    ("options.timeline.person.reference-mode", 1),
    ("options.timeline.person.color-scheme", 1),
    ("options.timeline.person.include-media", False),
    ("options.timeline.person.include-names", False),
    ("options.timeline.person.include-addresses", False),
    ("options.timeline.person.include-ldsords", False),
    ("options.timeline.person.include-citations", False),
    ("options.timeline.person.show-description", True),
    ("options.timeline.person.show-participants", True),
    ("options.timeline.person.show-role-always", False),
    ("options.timeline.person.show-source-count", True),
    ("options.timeline.person.show-citation-count", True),
    ("options.timeline.person.show-best-confidence", True),
    ("options.timeline.person.show-age", True),
    ("options.timeline.person.attributes-field-show-labels", False),
    ("options.timeline.person.attributes-field-1", "None"),
    ("options.timeline.person.attributes-field-2", "None"),
    ("options.timeline.person.attributes-field-3", "None"),
    ("options.timeline.person.attributes-field-4", "None"),
    ("options.timeline.person.show-class-vital", True),
    ("options.timeline.person.show-class-family", True),
    ("options.timeline.person.show-class-religious", True),
    ("options.timeline.person.show-class-vocational", True),
    ("options.timeline.person.show-class-academic", True),
    ("options.timeline.person.show-class-travel", True),
    ("options.timeline.person.show-class-legal", True),
    ("options.timeline.person.show-class-residence", True),
    ("options.timeline.person.show-class-other", True),
    ("options.timeline.person.show-class-custom", True),
    ("options.timeline.person.generations-ancestors", 1),
    ("options.timeline.person.generations-offspring", 1),
    ("options.timeline.person.show-family-father", True),
    ("options.timeline.person.show-family-mother", True),
    ("options.timeline.person.show-family-brother", True),
    ("options.timeline.person.show-family-sister", True),
    ("options.timeline.person.show-family-wife", True),
    ("options.timeline.person.show-family-husband", True),
    ("options.timeline.person.show-family-son", True),
    ("options.timeline.person.show-family-daughter", True),
    ("options.timeline.person.show-family-class-vital", False),
    ("options.timeline.person.show-family-class-family", False),
    ("options.timeline.person.show-family-class-religious", False),
    ("options.timeline.person.show-family-class-vocational", False),
    ("options.timeline.person.show-family-class-academic", False),
    ("options.timeline.person.show-family-class-travel", False),
    ("options.timeline.person.show-family-class-legal", False),
    ("options.timeline.person.show-family-class-residence", False),
    ("options.timeline.person.show-family-class-other", False),
    ("options.timeline.person.show-family-class-custom", False),
    ######################################################################
    ## Family Timeline
    ######################################################################
    ("options.timeline.family.image-mode", 0),
    ("options.timeline.family.reference-mode", 1),
    ("options.timeline.family.color-scheme", 1),
    ("options.timeline.family.include-media", False),
    ("options.timeline.family.include-names", False),
    ("options.timeline.family.include-addresses", False),
    ("options.timeline.family.include-ldsords", False),
    ("options.timeline.family.include-citations", False),
    ("options.timeline.family.show-description", True),
    ("options.timeline.family.show-participants", True),
    ("options.timeline.family.show-role-always", False),
    ("options.timeline.family.show-source-count", True),
    ("options.timeline.family.show-citation-count", True),
    ("options.timeline.family.show-best-confidence", True),
    ("options.timeline.family.show-age", True),
    ("options.timeline.family.attributes-field-show-labels", False),
    ("options.timeline.family.attributes-field-1", "None"),
    ("options.timeline.family.attributes-field-2", "None"),
    ("options.timeline.family.attributes-field-3", "None"),
    ("options.timeline.family.attributes-field-4", "None"),
    ("options.timeline.family.show-class-vital", True),
    ("options.timeline.family.show-class-family", True),
    ("options.timeline.family.show-class-religious", True),
    ("options.timeline.family.show-class-vocational", True),
    ("options.timeline.family.show-class-academic", True),
    ("options.timeline.family.show-class-travel", True),
    ("options.timeline.family.show-class-legal", True),
    ("options.timeline.family.show-class-residence", True),
    ("options.timeline.family.show-class-other", True),
    ("options.timeline.family.show-class-custom", True),
    ("options.timeline.family.generations-ancestors", 1),
    ("options.timeline.family.generations-offspring", 1),
    ######################################################################
    ## Place Timeline
    ######################################################################
    ("options.timeline.place.image-mode", 0),
    ("options.timeline.place.reference-mode", 3),
    ("options.timeline.place.color-scheme", 0),
    ("options.timeline.place.show-description", True),
    ("options.timeline.place.show-participants", True),
    ("options.timeline.place.show-role-always", False),
    ("options.timeline.place.show-source-count", True),
    ("options.timeline.place.show-citation-count", True),
    ("options.timeline.place.show-best-confidence", True),
    ("options.timeline.place.show-age", True),
    ("options.timeline.place.attributes-field-show-labels", False),
    ("options.timeline.place.attributes-field-1", "None"),
    ("options.timeline.place.attributes-field-2", "None"),
    ("options.timeline.place.attributes-field-3", "None"),
    ("options.timeline.place.attributes-field-4", "None"),
    ("options.timeline.place.show-class-vital", True),
    ("options.timeline.place.show-class-family", True),
    ("options.timeline.place.show-class-religious", True),
    ("options.timeline.place.show-class-vocational", True),
    ("options.timeline.place.show-class-academic", True),
    ("options.timeline.place.show-class-travel", True),
    ("options.timeline.place.show-class-legal", True),
    ("options.timeline.place.show-class-residence", True),
    ("options.timeline.place.show-class-other", True),
    ("options.timeline.place.show-class-custom", True),
    ("options.timeline.place.generations-ancestors", 1),
    ("options.timeline.place.generations-offspring", 1),
    ######################################################################
    # Display Group Options
    #
    ######################################################################
    ("interface.width", 500),
    ("interface.height", 500),
    ("interface.horiz-position", 10),
    ("interface.vert-position", 10),
)
